### ISSUE TITLE
dates from... to... setting should be removed

### ISSUE THREAD

**Issue by theokonings** [Wunderbyte-GmbH/moodle-mod_booking#109]
We installed the booking-module about half a year ago and are pleased with all the possebilities the mod offers.
Only one part of the settings is from the start obselete:
open from ... to...
still the bold text that the setting should not be used and will be removed; only it isn't removed (although we had already 3 updates).
For some users it's a confusing part en therefore it would be good to remove the setting completely.

Thanks in advance

Theo Konings

**Comment by dasistwas** [comment]
Thanks for the notice. Will remove in the next release. I had to wait until all the clients do not use the feature anymore. That takes a little time....

**Comment by theokonings** [comment]
Thanx for the response (very fast [😊] )


Kind regards,



Theo Konings

________________________________
Van: David Bogner <notifications@github.com>
Verzonden: donderdag 21 december 2017 09:24:20
Aan: dasistwas/moodle-mod_booking
CC: Konings, MAP (Theo); Author
Onderwerp: Re: [dasistwas/moodle-mod_booking] dates from... to... setting should be removed (#109)


Thanks for the notice. Will remove in the next release. I had to wait until all the clients do not use the feature anymore. That takes a little time....

**Comment by dasistwas** [comment]
It is now removed in the latest published version.
Kind regards,
David
