### ISSUE TITLE
Max current bookings per user - it counts against this limit even though the event has passed

### ISSUE THREAD

**Issue by demontech** [Wunderbyte-GmbH/moodle-mod_booking#111]
Hi David,

This setting is not doing what it's supposed to "Max current bookings per user" - "...After an event end time has passed, it is no longer counted against this limit."

![image](https://user-images.githubusercontent.com/8148238/35368904-8e5e56f6-013a-11e8-92cf-9b01f3280dfc.png)

I have a max of 1 on a group of booking options where students have the option to book only on one, but when the event time has passed it is still counted against this limit. Teachers have to manually removing the students from past bookings, so students can enroll on future ones. This is an issue to later check who booked on past events.

Thank you in advance for taking a look at this!

**Comment by dasistwas** [comment]
Hi,
I will have a look at that. 
Kind regards,
David

**Comment by dasistwas** [comment]
This should be fixed in the latest release
