### ISSUE TITLE
Debug info: Missing version.php file. Error code: detectedbrokenplugin

### ISSUE THREAD

**Issue by KofanAlexandr** [Wunderbyte-GmbH/moodle-mod_booking#112]
Hello,

Please update your plugin for Moodle v3.4

Debug info: Missing version.php file.
Error code: detectedbrokenplugin

Stack trace:
line 876 of /lib/upgradelib.php: plugin_defective_exception thrown
line 510 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
line 1850 of /lib/upgradelib.php: call to upgrade_plugins()
line 694 of /admin/index.php: call to upgrade_noncore()

**Comment by dasistwas** [comment]
Probably you did not give the permission to read files to your server or you did not tansfer all files to /mod/booking/. That is 100% not a issue of the booking module.

**Comment by KofanAlexandr** [comment]
Thank you for attention to my problem

How can I fix it?

**Comment by dasistwas** [comment]
I am not sure what system you use. But supposing you are on linux server like Ubuntut, then go to
moodleroot/mod/boooking
have a look if everything is there (including version.php)
then you could maybe change the owner of the whole folder like that:
cd ../mod
chown www-data booking -R (That's when you are on ubuntu, www-data can be different depending on your operating system). But there may be 100 other solutions for your problem, depending on how you did install Moodle and the plugins and depending on your operating system, etc...

**Comment by KofanAlexandr** [comment]
You're right))
I'm using a Linux server on Ubuntut
I can provide more information

**Comment by KofanAlexandr** [comment]
<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Book plugin version info
 *
 * @package    mod_book
 * @copyright  2004-2012 Petr Skoda {@link http://skodak.org}
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die;

$plugin->component = 'mod_book'; // Full name of the plugin (used for diagnostics)
$plugin->version   = 2017111300; // The current module version (Date: YYYYMMDDXX)
$plugin->requires  = 2017110800; // Requires this Moodle version
$plugin->cron      = 0;          // Period for cron to check this module (secs)

**Comment by KofanAlexandr** [comment]
<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * MOODLE VERSION INFORMATION
 *
 * This file defines the current version of the core Moodle code being used.
 * This is compared against the values stored in the database to determine
 * whether upgrades should be performed (see lib/db/*.php)
 *
 * @package    core
 * @copyright  1999 onwards Martin Dougiamas (http://dougiamas.com)
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$version  = 2017111301.01;              // 20171113      = branching date YYYYMMDD - do not modify!
