### ISSUE TITLE
icalendar attachment for cancellation in Outlook

### ISSUE THREAD

**Issue by monsieurmonsieur** [Wunderbyte-GmbH/moodle-mod_booking#113]
1. A user makes a booking and receives a confirmation e-mail with an .ics attachment
2. The user opens the .ics attachment in Microsoft Outlook 365 Pro and saves the appointment in his/her calendar
3. The user cancels the booking in Moodle
4. The user receives a cancellation confirmation e-mail with an .ics attachment
5. When the user opens the .ics attachment in Microsoft Outlook 365 Pro and saves, it adds another appointment in his/her calendar instead of cancelling the previous one.

This feature used to work before version 2.8 Audrey Horne (2018061700)

**Comment by dasistwas** [comment]
Thank you for reporting that bug. Fixed with this commit:
https://github.com/dasistwas/moodle-mod_booking/commit/dacf65ba370b0feb729907344817b58cf4e61b54
