### ISSUE TITLE
Sign-in-sheet: teachers

### ISSUE THREAD

**Issue by gemguardian** [Wunderbyte-GmbH/moodle-mod_booking#114]
Hi David,

In a case you have a lot of teachers and have a logo uploaded on the sign in sheet. 
The names of the teachers will not have a "break" just show in 1 line and will go through the logo. 

Is there a way to prevent this from happening??

Gemma
![image001](https://user-images.githubusercontent.com/16559999/42160269-e05ac3fc-7df6-11e8-80b8-a56ac57a3002.png)

**Comment by dasistwas** [comment]
OK, that can be fixed. Should not last too long.

**Comment by dasistwas** [comment]
Hi Gemma,
the problem is now fixed with https://github.com/dasistwas/moodle-mod_booking/commit/7c858655fc9cb78cabe282c6426c1965373fdf18
New version already published on moodle.org.

Kind regards,
David
