### ISSUE TITLE
Add booking option to calendar and choosing a course don't work together

### ISSUE THREAD

**Issue by demontech** [Wunderbyte-GmbH/moodle-mod_booking#115]
Hi David,

1. When you create a booking option and select "Add to calendar" don't work the first time you need to edit it a select it again to make it work.
2. If you select to choose a course in the booking option the event disappears from the calendar, even though "Add to Calendar" is marked. 
![image](https://user-images.githubusercontent.com/8148238/44494021-174e3b00-a61f-11e8-9c01-0bfa865170f9.png)
![image](https://user-images.githubusercontent.com/8148238/44494049-2fbe5580-a61f-11e8-88b0-1151d3acbc2d.png)

but if you remove the course 
![image](https://user-images.githubusercontent.com/8148238/44494104-6b591f80-a61f-11e8-9999-6cc703577442.png) then the booking option gets added to the calendar. This used to work fine before.

Thank you in advance for taking care of this!

**Comment by gemguardian** [comment]
Hi, 

I am not sure if there been work done on this issue, but some extra information regarding  **number 1**: When you create a booking option and select add to calendar. WHich I think makes sense in number 2 as well. 

When checking the option it creates a calendarid in de the Database, but does not turn the 0 to 1 for the add to calendar. See video: https://ltnc.screencasthost.com/watch/cFlw6tr9Ai
Password: Booking

@dasistwas  could you tell me if it possible to "add to calendar" option to the CSV upload? I have not figured that out yet. 

Gemma

**Comment by dasistwas** [comment]
Hi,

I fixed the issue and added the addtocalendar to csv import in master branch. Please test before I publish it in moodle.org. Attached an example import as xlsx (csv is not supported by github)
[testimport.xlsx](https://github.com/dasistwas/moodle-mod_booking/files/2728629/testimport.xlsx)
.



Kind regards,
David
