### ISSUE TITLE
Participant transfer KO

### ISSUE THREAD

**Issue by IsaQuinot** [Wunderbyte-GmbH/moodle-mod_booking#117]
Hi,

When I transfer participants, they disappear from the initial session but don't appear in the new one. However, they receive the confirmation email.
Our moodle version is 3.4.3+ and our booking version is 3.1

Thank you for you help

**Comment by dasistwas** [comment]
Hi,
I just tested with the current version and can not reproduce the described problem. I am closing this bug until you provide further information. Example: Course backup with anonymous users.

Kind regards,
David
