### ISSUE TITLE
Comments - brackets codes

### ISSUE THREAD

**Issue by demontech** [Wunderbyte-GmbH/moodle-mod_booking#119]
Hi David,

In the comments section this is what is showing: M3.5 booking 3.4

![image](https://user-images.githubusercontent.com/8148238/47055712-a5e9bf00-d16d-11e8-8771-be51d118b002.png)

Thanks

**Comment by atlet** [comment]
Try clearing cache.

**Comment by dasistwas** [comment]
Fixed in latest release
