### ISSUE TITLE
PostgreSQL syntax error

### ISSUE THREAD

**Issue by a-ttila** [Wunderbyte-GmbH/moodle-mod_booking#120]
When I want to upgrade under Moodle 3.5.2, the upgrade process fails with SQL syntax error.

**Comment by atlet** [comment]
Can you paste the error?

**Comment by a-ttila** [comment]
It happened in production environment :-(
I have to reproduce it in test environment, but it takes some time.

**Comment by a-ttila** [comment]
Debug info: ERROR: syntax error at or near "bt"
LINE 1: DELETE bt FROM mdl_booking_teachers bt
^
DELETE bt FROM mdl_booking_teachers bt
LEFT JOIN
mdl_booking_options bo ON bo.id = bt.optionid
WHERE
bo.id IS NULL
[array (
)]
Error code: dmlwriteexception

**Comment by a-ttila** [comment]
Stack trace:
line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 248 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 708 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1788 of /mod/booking/db/upgrade.php: call to pgsql_native_moodle_database->execute()
line 806 of /lib/upgradelib.php: call to xmldb_booking_upgrade()
line 512 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1857 of /lib/upgradelib.php: call to upgrade_plugins()
line 694 of /admin/index.php: call to upgrade_noncore()

**Comment by dasistwas** [comment]
Fix in  24b656b
