### ISSUE TITLE
TCPDF constants already defined

### ISSUE THREAD

**Issue by alex-rowe** [Wunderbyte-GmbH/moodle-mod_booking#121]
I am receiving the below errors message with debugging on as the booking module is trying to require the tcpdf library even though it's already been called.

```
Notice: Constant K_PATH_MAIN already defined in {sitedir}/lib/pdflib.php on line 126
Notice: Constant K_PATH_URL already defined in {sitedir}/lib/pdflib.php on line 129
Notice: Constant K_PATH_CACHE already defined in {sitedir}/lib/pdflib.php on line 132
Notice: Constant K_PATH_IMAGES already defined in {sitedir}/lib/pdflib.php on line 135
Notice: Constant K_BLANK_IMAGE already defined in {sitedir}/lib/pdflib.php on line 138
Notice: Constant K_CELL_HEIGHT_RATIO already defined in {sitedir}/lib/pdflib.php on line 141
Notice: Constant K_SMALL_RATIO already defined in {sitedir}/lib/pdflib.php on line 144
Notice: Constant K_TCPDF_THROW_EXCEPTION_ERROR already defined in {sitedir}/lib/pdflib.php on line 147 
```

**Comment by dasistwas** [comment]
Hi,
sorry can not reproduce. Your notices do not indicate any implication of the booking module.

**Comment by alex-rowe** [comment]
What version did you test this on?

We received this error on Moodle 3.5 after upgrading (with full debugging enabled) and it could only be removed after we commented out  `require_once($CFG->libdir . '/tcpdf/tcpdf.php');` in `/mod/booking/classes/booking.php` and `/mod/booking/locallib.php`.

Searching our code base, only mod_booking is using TCPDF in this way as Moodle should have already defined everything as part of `/lib/pdflib/php`.

**Comment by dasistwas** [comment]
Thank you for the additional information. Actually TCPDF is not used  anymore in the locallib. So removed it from there. Fixed in the latest commit.

**Comment by alex-rowe** [comment]
Does it also need to be removed from `classes/booking.php`?

**Comment by dasistwas** [comment]
I will have a look
