### ISSUE TITLE
Ordering boekingsoptions

### ISSUE THREAD

**Issue by gemguardian** [Wunderbyte-GmbH/moodle-mod_booking#122]
I notice it is possible for a user to order de bookingsoptions by clicking on the "headings" 
![2018-10-24_11-04-17](https://user-images.githubusercontent.com/16559999/47419578-cbce1f80-d77c-11e8-9f12-5092065706f7.png)

Though most questions I get is that bookingsmanagers find it "strange" that the bookingsoption are standard orderded on _last made_ while it would be more logic to have it standard orderded by "date". 

I am not sure if there is a specific reason why bookingsoption are placed based in the orderded they have been created. But if there is none, could it be possbile to change the order to "date" or even let the bookingsmanager choice _how the ordering should be_?

**Comment by dasistwas** [comment]
Implemented in latest release. It is a booking instance setting "Sort by"
