### ISSUE TITLE
DELETE from LEFT JOIN does not work in PostrgesSQL

### ISSUE THREAD

**Issue by pavelsokolov** [Wunderbyte-GmbH/moodle-mod_booking#124]
https://github.com/dasistwas/moodle-mod_booking/blob/5192c9971ef0f36037a53d95ba29a2c954cfa87e/db/upgrade.php#L1783

You can't LEFT JOIN directly in a DELETE statement. Therefore module fires an error when updating.

Stackoverflow think that USING can be used to do such a join, e.g.:

```
        $sql = "DELETE FROM {booking_teachers}
USING {booking_teachers} AS bt
            LEFT JOIN
                {booking_options} bo ON bo.id = bt.optionid
            WHERE
                bo.id IS NULL AND booking_teachers.id = bt.id"
```

Debug info: ERROR: syntax error at or near "bt"
LINE 1: DELETE bt FROM mdl_booking_teachers bt
^
DELETE bt FROM mdl_booking_teachers bt
LEFT JOIN
mdl_booking_options bo ON bo.id = bt.optionid
WHERE
bo.id IS NULL
[array (
)]
Error code: dmlwriteexception

**Comment by dasistwas** [comment]
This issue has already been fixed. https://github.com/dasistwas/moodle-mod_booking/issues/120

**Comment by pavelsokolov** [comment]
Thanks. Waiting for integration into master as well.

**Comment by dasistwas** [comment]
Will happen soon ;-).
