### ISSUE TITLE
3.6: Eventslib.php is deprecated and removed

### ISSUE THREAD

**Issue by pavelsokolov** [Wunderbyte-GmbH/moodle-mod_booking#126]
https://github.com/dasistwas/moodle-mod_booking/blob/dc9a9cd0deb6093fbf2dbdc199644741de0da356/lib.php#L21

The eventslib.php file has been deleted and its functions have been moved to deprecatedlib.php.

**Comment by dasistwas** [comment]
Please read this:
https://moodle.org/plugins/mod_booking

""The latest version is available for Moodle 3.4 and 3.5, but support for future versions needs funding. There are a lot of necessary tasks to be accomplished in order to keep the module working and up to date."

**Comment by pavelsokolov** [comment]
Okay, i see. However here it's just a matter of changing eventslib.php to deprecatedlib.php, not a big deal, and the module will still be compatible with Moodle 3.6. Maybe worth to apply.

**Comment by dasistwas** [comment]
I think the eventslib is not used anymore since quite some time but the file was never removed from being included. So I will remove it.

**Comment by dasistwas** [comment]
Fixed in latest commit
