### ISSUE TITLE
Empty booking options table triggers an error

### ISSUE THREAD

**Issue by pavelsokolov** [Wunderbyte-GmbH/moodle-mod_booking#129]
When updating a module on a clean site where booking_options table is empty, DB error is triggered:

mod_fcgid: stderr: Default exception handler: Coding error detected, it must be fixed by a programmer: moodle_database::get_in_or_equal() does not accept empty arrays

Here: https://github.com/dasistwas/moodle-mod_booking/blob/30030958f583ce0d3606529275eaf1d257c82c2b/db/upgrade.php#L1784

**Comment by dasistwas** [comment]
Solved in most recent versions (soon available on moodle.org as well=
