### ISSUE TITLE
Question: Bookingsadministratie Activity completion

### ISSUE THREAD

**Issue by gemguardian** [Wunderbyte-GmbH/moodle-mod_booking#131]
Hello, 

I am not sure if it is a bug, or simply a misunderstanding in the context. 

When I set my activity completion "show activity as completed when conditions are met". I can choice 2 options. I never mark the "Enable manual activity compeletion in a booking option response" since it does not make sense in most cases. See also issue https://github.com/dasistwas/moodle-mod_booking/issues/40

**BUT** I noticed that the button Confirm activity completion _does_ show at the bookingsoption. Ergo: one of the teachers used it and well now my report is not correct anymore. 

I would kind of expect that when I **don't** mark the setting, that the button should not be there. 

Is it a bug? Or my misunderstanding? 

Please see this video for a more context: https://player.vimeo.com/external/345546148.hd.mp4?s=c61795aaeac149764832139306bae3a5f73f81b9&profile_id=175

Gemma

**Comment by atlet** [comment]
I'll fix this "bug".

**Comment by dasistwas** [comment]
As far as I understood the implementation, this was implemented in a non Moodle way. So even if completion is not activated, it is possible to mark a booking option as "completed", which is not related at all with the general completion framework of Moodle.

**Comment by gemguardian** [comment]
Hi David,
Yes you are right, when I turn of activity completion in the bookingsadministration the button stays. 

but when you look at the bookingsadministration you can see that the Manual activity completion is marked for the bookingsoption response. 

![2019-07-03_17-01-34](https://user-images.githubusercontent.com/16559999/60602608-670ba000-9db4-11e9-8bec-692aec3100e8.jpg)

There is no way to unmark it. 
When the indication is as in the setting, it does not appear in the activity report. 

But when I switch to Show activity as complete when conditions are met - by example it **does** appear as marked in the report. 

Once I did the acitvity marking at a bookingoption I cannot change anything. I cannot unmark, or switch my bookingsadministration setting. 

So in my mind they are some how being linked to each other. Maybe through out the development?

**Comment by atlet** [comment]
> As far as I understood the implementation, this was implemented in a non Moodle way. So even if completion is not activated, it is possible to mark a booking option as "completed", which is not related at all with the general completion framework of Moodle.

Yes, I checked, it uses Completion API, but needs some modifications in code to work properly.

**Comment by gemguardian** [comment]
> As far as I understood the implementation, this was implemented in a non Moodle way. So even if completion is not activated, it is possible to mark a booking option as "completed", which is not related at all with the general completion framework of Moodle.

This would make more sense than what is happening now :)

**Comment by atlet** [comment]
I fixed this issue in my repo.
