### ISSUE TITLE
Add booking option templates - Draft implementation

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#132]
In order to create booking options faster, it should be possible to create booking option templates. These can then be selected for a booking option. When I create a new booking instance I can select a default template there. The booking module will have a standard template preconfigured, which is selected per default. New templates can be added by users on a global or course scale. 

### Using templates

1) Apply a template dynimacally via JS to a booking_option form
2) Reload when selecting the template from dropdown
3) Create an intermediate page when creating a booking option: 1st step: select template, 2nd step: configure the option.
4) In the booking instance settings, there will be a setting which template is used for a newly created booking option. This can be changed in the booking option itself by selecting a different template.
5) **From a list of available templates select one in order to create a booking option.**

### Creating templates

Instead of creating a new db table the existing booking_options table can be used for storing templates there. Could be done like this:

- The field bookingid has to be set to 0 in order to mark it as a template
- Add field "courseid" in booking_options
- The field courseid uses 1 for sitewide useable template (1 is also frontpage course id)
- The field courseid uses courseid for templates available within a specific course
- The standard template (default template) can be specified in the admin settings of the booking module (settings.php)
- In the booking options form a new option is created: "Add as template" with a dropdown and the following selections: "Do not use as template", "Use as template in this course", "Use as global template".

In install.php add method to add  a first default template in booking_options
In upgrade.php execute the install.php method for adding the default template

### Site admin settings

There will be a default template used for new booking options delivered with the booking module. This default template can be edited by the site administrator (in the booking plugin settings maybe). The default template will be stored with id=0 in the booking_optiontemplate table.

### Other modifications

Right now 3 defaults can be configured in the booking instance settings, that are used as default values in the booking option:
Limit the number of participants
Max. number of participants
Max. number of places on waiting list 

These will be removed in future version, Instead values from default site template will be used, or the chosen template for the booking instance.

**Comment by atlet** [comment]
We can add to options menu new option "Add to template". So in this way we don't need to create a new form for templates. We reuse existing system. This option will be available only to users with proper permission - we introduce new permission for templates.

### Templates for new booking
#### Only Booking
This is simple.
#### Booking with booking options
This is tricky. We need to create new booking with booking options and consider dates - how to calculate new dates (start and end time of course and limit availability of booking option)?

**Comment by dasistwas** [comment]
I updated the global description with your comments. I do not understand your 2 points
"Only booking"
"Booking with booking options"

What do you mean by that? Do you want to create booking instance templates as well?

**Comment by dasistwas** [comment]
Still to clarify: How to apply a template to a booking option?

**Comment by dasistwas** [comment]
Concerning using templates: I marked the favourite approach in bold. Please comment on that as well.

**Comment by atlet** [comment]
For booking I refer to booking instance. So yes, templates for booking instances as well.

I thinking, that you select a template and this will fill the form. So you an modify and also, you need to add name to booking option. For recurring I'll create a new section in booking option form (only when adding a new one), where you can select, how many copies it makes. What do you think? I don't think, this will be ok to put it in templates - because of dates.

**Comment by dasistwas** [comment]
For booking instances I would choose another approach: Create json string from a booking instance object and save it somewhere in a db field. Otherwise you risk to interfere with moodle core in unintended ways. Or use the backup/restore feature for that and build a UI around it.

**Comment by atlet** [comment]
Doing UI for backup/restore is overkill. Storing JSON in DB is simple option to go.

> From a list of available templates select one in order to create a booking option.

I think this option is ok.

**Comment by atlet** [comment]
> From a list of available templates select one in order to create a booking option.

Where to put this?

**Comment by atlet** [comment]
I pushed working version to my develop branch. You can check and give some feedback.

**Comment by jharej** [comment]
Hi, I've tested both - creating a booking and creating booking option from a template. It works, but ... I would like it, to be implemented in the same way. I don't want to look booking option templates on pull-down menu all the time - it's frustrating as it's harder to find anything because of the longer menu.
