### ISSUE TITLE
Same name for booking options

### ISSUE THREAD

**Issue by jharej** [Wunderbyte-GmbH/moodle-mod_booking#139]
Hi, 

in the latest version, you force booking options to have different names. As our clients have used the same names for events that they have organized now they can not edit any previous option unless they change their name. That is very uncomfortable. Can you introduce an option on booking instance-level e.g. "Allow equal names for booking options"? This would solve our problems and also allow you achieve yours.

bye
Janko

**Comment by dasistwas** [comment]
Hi Janko,
having 2 booking options in the same booking instance is like having 2 different houses with one address. So delivering  a letter would be quite complicated and only 50% chance you will get it to the right house.
For the booking options this means, uploading users via CSV would cause problems, and so on. I can not imagine a usecase where this is helpful. I am also not a fan of introducing yet another option. Maybe people can just add numbers to the option names?

Kind regards,
David
