### ISSUE TITLE
Sort by date should be default

### ISSUE THREAD

**Issue by aspark21** [Wunderbyte-GmbH/moodle-mod_booking#14]
Sort by date from soonest to latest should be default display mode for bookings list or at least it should be a setting option

**Comment by dasistwas** [comment]
yes, that will be done in the next release.

**Comment by aspark21** [comment]
I don't mean to be rude or demanding but I'm unaware of your release schedule, when would the next release be scheduled for?

Thanks so much for including this in the next release!

**Comment by dasistwas** [comment]
There will be a release when somebody is hiring us for including a new feature or adapt the module to a new moodle version. So there is no release schedule, except if you want to have one, then you can hire us ;-). Sorting soonest to latest should be ready in a few weeks.

**Comment by aspark21** [comment]
@dasistwas Fair enough :)
