### ISSUE TITLE
Description not visible

### ISSUE THREAD

**Issue by behoof** [Wunderbyte-GmbH/moodle-mod_booking#142]
L.s.

The description is gone in moodle 3.7. Using Moodle 3.7.2+ (Build: 20191004) | v5.7-Nairobi
2019092601

See attachments,

Bert

![Booking Moodle 3 5](https://user-images.githubusercontent.com/4709219/66295923-b1894500-e8ec-11e9-9e5f-5a539b52d3c4.png)
![Booking Moodle 3 7](https://user-images.githubusercontent.com/4709219/66295924-b1894500-e8ec-11e9-9bbe-169381abce94.png)

**Comment by dasistwas** [comment]
Hi,
what settings do you have in " Booking instance settings -> Fields to display in different contexts -> Fields on the booking options overview page " 
Kind regards,
David

**Comment by behoof** [comment]
Hi David,

That selection field is empty (not showing description field)

Bert

[Image]
Hi David,


Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: David Bogner <notifications@github.com>
Verzonden: Monday, October 7, 2019 2:27:18 PM
Aan: dasistwas/moodle-mod_booking <moodle-mod_booking@noreply.github.com>
CC: Bert van der Hooft <bert@vanderhooft.com>; Author <author@noreply.github.com>
Onderwerp: Re: [dasistwas/moodle-mod_booking] Description not visible (#142)


Hi,
what settings do you have in " Booking instance settings -> Fields to display in different contexts -> Fields on the booking options overview page "
Kind regards,
David

**Comment by dasistwas** [comment]
Then you have to add all of them to fix the problem

**Comment by dasistwas** [comment]
There are 3 fields. You have to select all of them

**Comment by dasistwas** [comment]
@behoof could you please give feedback, if adding the fields resolved the problem?

Thank you,
David

**Comment by dasistwas** [comment]
Can not be reproduced and reporter @behoof seems to have disappeared. So closing this.
