### ISSUE TITLE
Add other users link disappeared

### ISSUE THREAD

**Issue by monsieurmonsieur** [Wunderbyte-GmbH/moodle-mod_booking#143]
Hello, 
In booking 5.7, the "add other users" link is no longer present in the list of participants page. This is a link that was used all the time in our organization, and could be clicked on even without having to access the cog icon on the reservations list page.
Is this link supposed to be no longer displayed ?

Thanks !

**Comment by dasistwas** [comment]
it has moved to the settings-icon dropdown, usually top right of the booking option page (depending on your theme)

**Comment by monsieurmonsieur** [comment]
Thanks for your reply ! 

The issue I have is that this drop-down menu is in a different permission rule (booking:updatebooking) with a lot of functionnalities attached to it other than add user (namely, the possibility to delete an option) whereas before we could just allow "booking:subscribeusers" for people to do this. 
I can't allow users who used to just subscribe other users to have the possibility to edit or even delete a booking option.

Thanks again

**Comment by monsieurmonsieur** [comment]
Hello again, is it possible to tell me if this issue will be adressed or if the loss of the subscribe user functionality will remain as it is ?

Thanks again

**Comment by gemguardian** [comment]
hi David, 

The capability "mod/booking: updatebooking controles if the "cog" is showing or not. 
Therefore even when a role has the cabaility "mod/booking:subscribeusers", there is NO way to access that option anymore. 

I also have a case where we have teachers-assistents that have certain rights within the bookingsoption, and now missing this option. 

I did some research / testing my suggestion is that the cog is not being controled by The capability "mod/booking: updatebooking, but only remove options from the dropdown. 

I think that this should be these options. 

- TO edit the bookingsoption. 
- To edit the teachers
- To remove the bookingsoption
- To duplicate the bookingsoption

The following options should stay in my opinion 
- Link to the bookingsurl 
- Subcribe users 

Though..

**Link to bookingsurl** if you are NO teacher and you don't have the mod/booking: updatebooking capability, that this setting should be removed from the cog

**subscribe users**
To be honest I am not really sure if "code-wise" there is a connection between the Cability mod/booking:subscribeusers and the _bookingsoption setting: Max. number of users_ a teacher assigned to the option can book

If there is a connection it does not make any sense when an user is ADDED as a teacher, has the  Cability mod/booking:subscribeusers, that there is NO option showing for him. 

If there is NO connection, I think it should be clear then that you need the capability mod/booking:subscribeusers to have a max. number of users set. 

Hope that this input works for you

Gemma

**Comment by dasistwas** [comment]
Hi @monsieurmonsieur and Gemma,

thank you for the detailed info about this issue. I will have a look at that und provide an update soon.

Kind regards,
David

**Comment by atlet** [comment]
@dasistwas this is fixed in my develop repository.

**Comment by dasistwas** [comment]
Added the link again in on the answers page for booking option teachers only.
