### ISSUE TITLE
Exception when user has Teacher role at Booking Option level, but Student's role at Course level.

### ISSUE THREAD

**Issue by johnnylupino** [Wunderbyte-GmbH/moodle-mod_booking#149]
![issue_with_teacher_vs_student_role](https://user-images.githubusercontent.com/7383318/68467921-59a96b00-0217-11ea-994a-3e42978cbff8.png)
Hello David,
I got "Exception - Call to undefined method mod_booking\booking_option::get_all_optionids_of_teacher()"
when my user is a Teacher at booking option level, but Student at course level.

Regards,
Archie

**Comment by dasistwas** [comment]
Thank you for posting this. Please also provide booking version und Moodle version.

**Comment by johnnylupino** [comment]
Hi David,

Moodle: 3.5.6
Plugin version: v5.7-Nairobi (2019092601)

**Comment by dasistwas** [comment]
@johnnylupino this is fixed in the commit above. release soon on moodle.org
