### ISSUE TITLE
Delete Categories? 

### ISSUE THREAD

**Issue by VOOM108** [Wunderbyte-GmbH/moodle-mod_booking#159]
I use Nairobi 5.9 in Moodle 3.6.4

Trying to delete categories, I get an error-message: 
Ein Vergleich der Textspaltenbedingungen ist nicht zugelassen. Bitte verwenden Sie in Ihrer Abfrage sql_compare_text() .
Weitere Informationen über diesen Fehler (http://docs.moodle.org/36/de/error/moodle/textconditionsnotallowed)

**Comment by dasistwas** [comment]
PostgreSQL or mySQL or MariaDB?

**Comment by dasistwas** [comment]
OK, can reproduce.

`Stack trace:

    line 677 of /lib/dml/moodle_database.php: dml_exception thrown
    line 1350 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
    line 58 of /mod/booking/categoryadd.php: call to moodle_database->get_records()`
