### ISSUE TITLE
Plugin upgrade fails

### ISSUE THREAD

**Issue by santimoral** [Wunderbyte-GmbH/moodle-mod_booking#16]
When I try to upgrade the plugin in Moodle 2.7.3 the database upgrade fails.

Booking /mod/booking

Current version 2014091600
New version 2015012100

Here is the message

mod_booking

DDL sql execution error

More information about this error

Debug info: Unknown column 'address' in 'mdl_booking_options'
ALTER TABLE mdl_booking_options ADD pollurlteachers VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci AFTER address
Error code: ddlexecuteerror
Stack trace:
line 449 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
line 908 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 76 of /lib/ddl/database_manager.php: call to mysqli_native_moodle_database->change_database_structure()
line 533 of /lib/ddl/database_manager.php: call to database_manager->execute_sql_arr()
line 512 of /mod/booking/db/upgrade.php: call to database_manager->add_field()
line 697 of /lib/upgradelib.php: call to xmldb_booking_upgrade()
line 420 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1615 of /lib/upgradelib.php: call to upgrade_plugins()
line 434 of /admin/index.php: call to upgrade_noncore()

**Comment by dasistwas** [comment]
Hi,

thank you for reporting this. I will have a look at it.

Best,
David

**Comment by nitro2010-zz** [comment]
In upgrade.php in 508 line, change address to pollurl

**Comment by dasistwas** [comment]
Hi,

only upgrades from versions released on moodle.org are supported. You might just fix your database structure by hand with phpmyadmin. The solution from nitro2010 might work, but could also lead to a corrupted database structure.

Best,
David
