### ISSUE TITLE
Untrusted data passed to unserialize() function - potential security issue

### ISSUE THREAD

**Issue by OlenaTatarintseva** [Wunderbyte-GmbH/moodle-mod_booking#163]
Hello,

First of all I want say thank you for your work with the plugin.

We noticed unserialize() function is used with passed untrusted data from $_POST/$_GET variable in mod/booking/sendmessage.php. 

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/blob/master/sendmessage.php#L57

It could cause security issue. It is safe to use json_encode and json_decode functions instead.

Could you please fix it?

**Comment by dasistwas** [comment]
Solved I develop branch.
