### ISSUE TITLE
Booking option calendar event types

### ISSUE THREAD

**Issue by bernhard-wunderbyte** [Wunderbyte-GmbH/moodle-mod_booking#166]
When creating a new booking option, one has the possibility to add the booking option to the Moodle calendar.

Currently, this will always create a calendar event of the type "course event" with a link to the course it was created from and a link to the booking option itself.

However, it should also be possible to create different event types than "course event". There should be support for the following event types:
- ~~Site event - implement global calendar events with no specific course attached to them so they will be shown to every user on the Moodle platform~~
- [x] Course event (current default - right now it will always use the course it was created from, no matter which course was specified under "Choose a course" in the "Edit booking option" form - @dasistwas / @georgmaisser should this behavior be changed?)

**[Update: 18.05.2021, 15:14] Won't be implemented:**
- User event: an easy implementation would be to use the currently logged in user - @dasistwas / @georgmaisser there could also be a field to select a specific user the event is for - however this doesn't make a lot of sense or does it?)
- Group event: will need an extra field to select the user group the calendar event should be displayed to - @georgmaisser / @dasistwas do we need to implement group booking options before implementing group calendar events?
- Category event: will need an extra field to select the course category the calendar event is for - @georgmaisser / @dasistwas do we need to implement category booking options before implementing category calendar events?

**Comment by dasistwas** [comment]
@bernhard-wunderbyte group and category events are not really needed as a feature. also the user event: that is only for booked options which is already implemented. so just add course and site event and leave the checkmark for adding the booked event to the users calendar. but rename it so that it is clear what it does (just lang file change)
