### ISSUE TITLE
Field "optionid" does not exist in table "booking_options"

### ISSUE THREAD

**Issue by klebann** [Wunderbyte-GmbH/moodle-mod_booking#173]
Code:
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/blob/79321f3c43287bd17d6316eb9689cb0363aa4f98/classes/booking_option.php#L174

Executing only with first parametr:
$bo = \mod_booking\booking_option::create_option_from_optionid($params['optionid']);

Causing problem:
Field "optionid" does not exist in table "booking_options"

This should be:
$boid = $DB->get_field('booking_options', 'bookingid', ['id' => $optionid]);

**Comment by dasistwas** [comment]
@klebann thank you for reporting this. Going to be fixed. soon.

**Comment by bernhard-wunderbyte** [comment]
@dasistwas fixed in Branch dev_bernhard
