### ISSUE TITLE
Class 'completion_info' not found.

### ISSUE THREAD

**Issue by klebann** [Wunderbyte-GmbH/moodle-mod_booking#174]
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/blob/79321f3c43287bd17d6316eb9689cb0363aa4f98/classes/booking_option.php#L825

Error:
_Class 'completion_info' not found._

My solution:
```php
global $CFG;
require_once("{$CFG->libdir}/completionlib.php"); //require missing?
$course = $DB->get_record('course', array('id' => $this->booking->settings->course));
$completion = new completion_info($course);
```

**Comment by dasistwas** [comment]
why does the use statement not work? https://github.com/Wunderbyte-GmbH/moodle-mod_booking/blob/79321f3c43287bd17d6316eb9689cb0363aa4f98/classes/booking_option.php#L17 require_once is not good practice.

**Comment by dasistwas** [comment]
... if require_once is used, it is better to put it at the beginning of the file. Example: https://github.com/moodle/moodle/blob/0a986fdf13a1a1642085cf2af800440454916d0f/completion/classes/external.php

**Comment by dasistwas** [comment]
@klebann Could you specify Moodle version and PHP version used. Maybe automatic class loading is different in Moodle versions.

**Comment by klebann** [comment]
Moodle: 3.9
PHP: 7.2.24

**Comment by klebann** [comment]
adding `require_once("{$CFG->libdir}/completionlib.php");` solves problem for me, but I hope you got better solution.

**Comment by klebann** [comment]
I must check plugin version, maybe I have version before `use completion_info;`

**Comment by bernhard-wunderbyte** [comment]
@dasistwas Should I add `require_once("{$CFG->libdir}/completionlib.php");` to class booking_option.php ?

**Comment by dasistwas** [comment]
First find out the cause of the problem. `use completion_info; `should work? Does it?

**Comment by klebann** [comment]
$plugin->version = 2020020700; so I got newest version

use completion_info; is present in my code and it doesn't work. Hmm why?

**Comment by klebann** [comment]
Maybe we need to require_once same as calendar/lib.

require_once($CFG->dirroot.'/calendar/lib.php'); <-- line 24

**Comment by dasistwas** [comment]
seems that it is old Moodle code without proper class definition so we have to use require_once @bernhard-wunderbyte
