### ISSUE TITLE
Add automatic release workflow

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#176]
Release automatically to moodle.org:
https://github.com/center-for-learning-management/moodle-local_webuntis/blob/main/.github/workflows/moodle-release.yml

## Documentation

https://github.com/moodlehq/moodle-plugin-release

**Comment by georgmaisser** [comment]
Done 7112f0635c3ae2c99fa87805a0d26bd0ecedcfdb
