### ISSUE TITLE
Selection and Date columns not visible after duplication of Booking instance

### ISSUE THREAD

**Issue by rundownrob1** [Wunderbyte-GmbH/moodle-mod_booking#178]
We recently upgraded our Booking Moodle site from 3.4.4 to 3.7.9. We run weekly tutorial sessions where we duplicate the previous weeks booking instance.  When we do this, the Selection and Date columns do not display for the copy.  Both are still listed in the "Fields to display in different contexts." If I remove either Selection or Date and add it back, the columns return.

We are using the plain Boost theme that was packaged with 3.7.9.

**Comment by dasistwas** [comment]
@bernhard-wunderbyte I had the same problem at virtuelle-ph.at could you investigate if the data structure has changed and ensure that duplication works as expected. 

- When editing the settings of the booking module, the saved values are displayed (example: booking option overview the selection (Auswahl))
- On the booking option overview the selection (option title) is not diesplayed
- Upon removing and adding the selection again and saving the booking instance settings, the selection is displayed.

**Comment by bernhard-wunderbyte** [comment]
@dasistwas Error could not be reproduced on my local Moodle instance (Moodle 3.10) with Booking v7.0.5. Please check, if it's a legacy problem and if we need to make changes to upgrade.php.

**Comment by rundownrob1** [comment]
I am using Booking 5.9. That is the most current version listed on the Moodle Plugins repository. We limited out Moodle upgrade to 3.7.9 because that was the most current version listed to work with Booking.  Is there a version that works with Moodle 3.10?

**Comment by dasistwas** [comment]
Tested with the newest version and the problem is solved even when the booking instance was created with an old version of booking. @rundownrob1 So I recommend to upgrade to the latest version.

**Comment by gemguardian** [comment]
Hi, 
just wondering - where can we find the newste version. Since the version in the master is the 5.9-Nairobi version .

**Comment by dasistwas** [comment]
Right now it is available in the develop branch. Working on a proper Moodle release:
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tree/develop

**Comment by gemguardian** [comment]
Thank you!

**Comment by rundownrob1** [comment]
Thank you.  Will the development branch work with Moodle 3.7.9?  We are using that Moodle version specifically since that is what Booking 5.9 works with.

**Comment by dasistwas** [comment]
@rundownrob1 I do not know. You might be lucky, but the lowest Moodle version we support is 3.9.

**Comment by dasistwas** [comment]
@rundownrob1 Did you test booking 5.9 with M3.9? I think it should work, maybe you get some deprecation notices, but that should not affect you Moodle. My suggestion would be to upgrade at the same time Moodle and booking to M3.9
