### ISSUE TITLE
DB error under Moodle 2.7.8

### ISSUE THREAD

**Issue by Marx1st** [Wunderbyte-GmbH/moodle-mod_booking#18]
Hi,

we've recently updated mod_booking from 2014062500 to 2015012100 (upgrade went smoothly).

When opening an existing "booking", though, we get the following error:

Debug info: FEHLER:  Spalte »bo.coursestarttime« muss in der GROUP-BY-Klausel erscheinen oder in einer Aggregatfunktion verwendet werden
LINE 1: ... 1432900897 OR bo.coursestarttime = 0)   ORDER BY bo.courses...
                                                             ^
SELECT COUNT(DISTINCT bo.id) AS count  FROM mdl_booking_options AS bo LEFT JOIN mdl_booking_answers AS ba ON bo.id = ba.optionid LEFT JOIN mdl_user AS u ON ba.userid = u.id WHERE  bo.bookingid = $1  AND (bo.coursestarttime > 1432900897 OR bo.coursestarttime = 0)   ORDER BY bo.coursestarttime DESC
[array (
  0 => '6',
)]
Error code: dmlreadexception
Stack trace: 
line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1476 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 768 of /mod/booking/locallib.php: call to moodle_database->get_record_sql()
line 379 of /mod/booking/view.php: call to booking_options->count()

**Comment by dasistwas** [comment]
That is a PostgreSQL problem. As we do not have any customer with that database, we do not have a high priority for that bug. But I will see, if it is possible to fix it, because it should be an easy fix.

**Comment by Marx1st** [comment]
Thanks for your reply!

A fix for it would be greatly appreciated! :)

If I can do anything to support you (testing, supplying info, etc.), just give me the word!

BR,
Tobias

**Comment by eberhardt** [comment]
I would like to bump that topic - we get the exactly the same because we're using postgres, too.

`Error code: dmlreadexception`
`Debug info: ERROR: column "bo.coursestarttime" must appear in the GROUP BY clause or be used in an aggregate function`

You must mention all selected fields in a GROUP BY clause / aggregate function.
Since it is more proper SQL code, your plugin would benefit from it in general.

**Comment by eberhardt** [comment]
Any comment on this from the authors?

**Comment by dasistwas** [comment]
Hi,
right now the module is not really supported anymore. If you create a pull request with the solution, I will update the module on moodle.org. 
Kind regards,
David

**Comment by aspark21** [comment]
@dasistwas if that is the case, maybe worth updating the plugin maintainer info on Moodle.org - from the looks of it @atlet has been the maintainer and developer of the plugin for quite a while now

**Comment by dasistwas** [comment]
@aspark21 Sorry you got me wrong: I still support the module, if someone is willing to pay for the work. I have put a lot of my free time in the module, but right now I have to feed 2 kids and earn some money to do so. I am in contact with @atlet and forwarding bug reports. But I am not sure if he wants to support PostgreSQL. And I still process pull requests, when I have time to do so. As I am living from Moodle programming I do not want to give away the maintenance completely. I hope that is understandable for you.
