### ISSUE TITLE
Delete customfields has wrong params

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#180]
There is a delete function in the observer, which does not make sense. 

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/blob/d6c75c8978d14398148b04d66d4af93eeeaacc93/classes/observer.php#L46

Could you fix that @bernhard-wunderbyte @georgmaisser

**Comment by bernhard-wunderbyte** [comment]
FIXED: Removed wrong deletion statement for booking_customfields and added missing deletion statement for booking_icalsequence.
