### ISSUE TITLE
Undefined properties

### ISSUE THREAD

**Issue by Tsheke** [Wunderbyte-GmbH/moodle-mod_booking#182]
Phpunit raise errors in the function booking_add_instance (booking/lib.php) for the use of properties that do not exist.

The null coalescing operator (??) is used with object properties that do not exist.

core_calendar_container_testcase::test_delete_module_delete_events
Undefined property: stdClass::$showviews

/var/www/html/mod/booking/lib.php:331
/var/www/html/course/modlib.php:128
/var/www/html/lib/testing/generator/module_generator.php:271
/var/www/html/mod/booking/tests/generator/lib.php:56
/var/www/html/calendar/tests/container_test.php:445
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
vendor/bin/phpunit "core_calendar_container_testcase" calendar/tests/container_test.php

....

 core_calendar_container_testcase::test_delete_module_delete_events
Undefined property: stdClass::$bookedtext

/var/www/html/mod/booking/lib.php:349
/var/www/html/course/modlib.php:128
/var/www/html/lib/testing/generator/module_generator.php:271
/var/www/html/mod/booking/tests/generator/lib.php:56
/var/www/html/calendar/tests/container_test.php:445
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
vendor/bin/phpunit "core_calendar_container_testcase" calendar/tests/container_test.php

ERRORS!

**Comment by dasistwas** [comment]
Thank you for the report @Tsheke. Could you specify booking version and moodle version you are using?

**Comment by Tsheke** [comment]
Hi @dasistwas ,
Sorry for forgetting to specify the plugin version. Here is it:

$plugin->version = 2021091400;
$plugin->requires = 2019111800; // Requires this Moodle version. Current: Moodle 3.8.
$plugin->release = 'v7.0.6';
$plugin->maturity = MATURITY_STABLE;
$plugin->cron = 60;
$plugin->component = 'mod_booking';

I'm running tests on moodle 3.9.

**Comment by dasistwas** [comment]
@bernhard-wunderbyte could you have a look at that. Also  `$plugin->cron = 60;` in version php is obsolete.

**Comment by georgmaisser** [comment]
Fixed in Commit 366ccb0 (currently only in dev_bernhard branch), will be in master branch soon. Thanks for reporting!
