### ISSUE TITLE
Inconsistancy between install.xml and upgrades

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#183]
Hi @georgmaisser , @bernhard-wunderbyte ,

the db/upgrade.php apparently is not consistent with changes in install.xml. Reports from mod booking user using

sudo -u www-data php admin/cli/check_database_schema.php

shows that:

-------------------------------------------------------------------------------

booking_instancetemplate

* column 'template' is not expected (B)

-------------------------------------------------------------------------------

booking_icalsequence

* column 'userid' should be NOT NULL (I)

* column 'userid' has default '0', expected 'NULL' (I)

* column 'optionid' should be NOT NULL (I)

* column 'optionid' has default '0', expected 'NULL' (I)

* column 'sequencevalue' should be NOT NULL (I)

* column 'sequencevalue' has default '0', expected 'NULL' (I)

-------------------------------------------------------------------------------

booking_userevents

* column 'userid' has default '0', expected 'NULL' (I)

* column 'optionid' has default '0', expected 'NULL' (I)

* column 'optiondateid' has default '0', expected 'NULL' (I)

* column 'eventid' has default '0', expected 'NULL' (I)

-------------------------------------------------------------------------------

**Comment by bernhard-wunderbyte** [comment]
booking_instancetemplate: column 'template' is not expected (B)
=> this is a Moodle error which was fixed in https://tracker.moodle.org/browse/MDL-73095

**Comment by bernhard-wunderbyte** [comment]
Fixed in Version 7.0.24 (2022021500)
