### ISSUE TITLE
Calendar-file (ics) is incomplete

### ISSUE THREAD

**Issue by AntonT76** [Wunderbyte-GmbH/moodle-mod_booking#184]
we are using 5.9 Nariobi on Moodle 3.9.12. After booking an event you will get a booking confirmation via email which includes a calendar file (ics). The file is incomplete, example:

```
BEGIN:VCALENDAR
VERSION:2.0
METHOD:PUBLISH
PRODID:Data::ICal 0.22
CALSCALE:GREGORIAN
END:VCALENDAR
```

a.) Maybe it is a bug or wrong setting in plugin configuration. I haven't found a way to customise the file in the plugin settings. Does anyone have an idea how to customise the file?
b.) It would be nice if there will also be a selection option in the booking settings: create & send ics-file: yes/no

br, Anton

**Comment by ChristFunk** [comment]
We have a similar problem. In our case, the .ics file remains empty. We have not yet found a way to change this.

**Comment by dasistwas** [comment]
Thank you for reporting that. Actually we do not support this version anymore. It is outdated since a long time. I would recommend to try an upgrade and see if the problem persists.
