### ISSUE TITLE
Exception - Class 'core_payment\helper' not found

### ISSUE THREAD

**Issue by atlet** [Wunderbyte-GmbH/moodle-mod_booking#186]
![image](https://user-images.githubusercontent.com/1223162/165776054-d4490b92-7670-4dcc-9731-7dd3e7c868a1.png)

After upgrade with your version I get this error.

**Comment by dasistwas** [comment]
@atlet might that it only works with 3.10 and newer. We are using a feature that was only introduced in 3.10. So backward compatibility for this newest release is only down to 3.10. 
Which Moodle version did you use?

Thank you for reporting the bug.
Kind regards,
David

**Comment by atlet** [comment]
3.9. 

Quick fix: https://github.com/atlet/moodle-mod_booking/commit/d98363b6c7da87f821415612484bf832ac37af2f
