### ISSUE TITLE
Paypal-Integration

### ISSUE THREAD

**Issue by pax77-dd** [Wunderbyte-GmbH/moodle-mod_booking#189]
Hello is there a possibility to integrate Paypal as a payment option?
Many greetings
Remo

**Comment by dasistwas** [comment]
yes. that's possible.

**Comment by pax77-dd** [comment]
How do I do that? Are there any instructions for this?
We use the "old" Paypal-only variant.

**Comment by dasistwas** [comment]
Sorry we can not provide free support for such requests.
