### ISSUE TITLE
Upgrade error: Field "eventtype" does not exist in table "booking"

### ISSUE THREAD

**Issue by leonstr** [Wunderbyte-GmbH/moodle-mod_booking#19]
Hi,
When trying to upgrade Moodle 2.2 with mod_booking 2013090500 to Moodle 2.7 with mod_booking 2015012100 using the upgrade.php script I get:

-->mod_booking
!!! Field "eventtype" does not exist in table "booking" !!!
!!
Error code: ddlfieldnotexist !!
!! Stack trace: \* line 637 of \lib\ddl\database_manager.php: ddl_field_missing_exception thrown
- line 421 of \mod\booking\db\upgrade.php: call to database_manager-&gt;change_field_default()
- line 697 of \lib\upgradelib.php: call to xmldb_booking_upgrade()
- line 420 of \lib\upgradelib.php: call to upgrade_plugins_modules()
- line 1615 of \lib\upgradelib.php: call to upgrade_plugins()
- line 171 of \admin\cli\upgrade.php: call to upgrade_noncore()
  !!

**Comment by leonstr** [comment]
It looks like this is because mod/booking/db/upgrade.php tries to change the default for column eventtype at line 421 (for $oldversion < 2014033101) but doesn't actually add this column until line 447 ($oldversion < 2014091600).

**Comment by leonstr** [comment]
It looks like this change in upgrade order (i.e. changing the column default before adding the column) occurred in commit 6ceb412ef34473f664f3581898174c51b4d72ccc. If I revert the add column back to the end of the changes for $oldversion < 2014033100 it fixes this issue for me.

I've created a pull request for this change. However, there may have been some specific issue that the re-ordering was originally trying to resolve so maybe this won't work for everyone?

**Comment by dasistwas** [comment]
Hi,
thank you for that pull request. I think that could create problems with other versions of the module. I do not have time to look at it right now so, I am closing this issue.
