### ISSUE TITLE
Stuck on settings page

### ISSUE THREAD

**Issue by atlet** [Wunderbyte-GmbH/moodle-mod_booking#193]
I installed version of plugin v7.0.30 on Moodle 4 to test if it's working fine (and fix what it's not working). Now I'm stuck on settings page:

![image](https://user-images.githubusercontent.com/1223162/175259396-4b5fde7d-f96c-40ee-8ebf-759d9b258964.png)

Any idea how to fix this issue?

Tnx.

**Comment by abkoch** [comment]
Hello, same problem with my Moodle installation, version 4.0.2. Is there a fix meanwhile?

**Comment by dasistwas** [comment]
I think you can just go back to the frontpage and ignore that.

**Comment by dasistwas** [comment]
@georgmaisser could you have a look at that or assign @winnidat?

**Comment by bernhard-wunderbyte** [comment]
@winnidat Has this already been fixed?

**Comment by abkoch** [comment]
I tried the latest version but the problem still exists. It would be great if this issue would be fixed.

**Comment by dasistwas** [comment]
@winnidat any news on that issue?

**Comment by georgmaisser** [comment]
The issue only occurred on instances which deleted the standard Paypal paygw_paypal plugin. There is a payment helper function which returns installed currencies, which relies on installed paygw plugins. when they are not there, an empty array is returned, this rendered the currency selector being invisible -> we were stuck.

To avoid this, Euro is hardcoded as option. If one adds a paygw_plugin later, more currency options will appear.
