### ISSUE TITLE
Backup/restore/delete of course with mod-booking entries failed (mod-booking 7.2)

### ISSUE THREAD

**Issue by baltaner** [Wunderbyte-GmbH/moodle-mod_booking#194]
Hello,
first I would like to say, that mod-booking is realy great! We use it to organize our internal trainings.

We are running Moodle4.0.1 and so I have to install your 7.0.26 Version - it worked (with some minor problems...)
Now I updated to mod-booking7.2 - it seems to work well for us.

But, when I want to copy a course or want to delete a course with a mod-booking activity inside, I get following error message (apache/error.log):
` Got error 'PHP message: Potential coding error - existing temptables found when disposing database. Must be dropped!`

I know, that you don't released an offical release for Moodle4.0 - but probably this information helps.

Thanks!
Bertold

**Comment by dasistwas** [comment]
@bernhard-wunderbyte when you do that : backup / restore a course with booking instance, does that throw the same error?

**Comment by baltaner** [comment]
@bernhard-wunderbyte
a backup throws the same error:
` Got error 'PHP message: Potential coding error - existing temptables found when disposing database. Must be dropped!', referer: https://XXXXXX/moodle/backup/backup.php`

**Comment by bernhard-wunderbyte** [comment]
@baltaner I just did a backup of a course containing a booking instance (v7.2) on my local development site (Moodle 4.0.1) without any problems. So I guess that this might not be not a mod_booking related problem but instead a problem with your database settings.

According to https://moodle.org/mod/forum/discuss.php?d=269128 , it's most likely a problem with your database settings. So please try the following:

1. Turn on Debugging in Moodle: Site administration > Development > Debugging
2. Now you should get a more helpful warning, probably something like "Access denied to  user 'xxxxxx'@'serveraddress' CREATE TEMPORARY TABLE ...."
3. If this is the problem, you need to give the appropriate rights to your database user...

**Comment by dasistwas** [comment]
Seems your user does not have the right to create tmp tables. I will close that isse.

**Comment by baltaner** [comment]
@bernhard-wunderbyte
Thank you for your help!
I changed the database-user to "admin" with full rights to all databses - same error!
With enabled debugging I get following error-messages when doing a course-backup
(it seems, that a database table is missing. I use MariaDB-1:10.5.12):
```
Table "local_entities_relations" does not exist

More information about this error

Debug info:
Error code: ddltablenotexist

#
Stack trace:
line 665 of /lib/dml/moodle_database.php: dml_exception thrown
line 1341 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
line 53 of /backup/util/dbops/backup_structure_dbops.class.php: call to moodle_database->get_recordset()
line 359 of /backup/util/structure/backup_nested_element.class.php: call to backup_structure_dbops::get_iterator()
line 77 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->get_iterator()
line 107 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->process()
line 107 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->process()
line 107 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->process()
line 107 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->process()
line 107 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->process()
line 97 of /backup/util/plan/backup_structure_step.class.php: call to backup_nested_element->process()
line 181 of /backup/util/plan/base_task.class.php: call to backup_structure_step->execute()
line 222 of /backup/moodle2/backup_activity_task.class.php: call to base_task->execute()
line 191 of /backup/util/plan/base_plan.class.php: call to backup_activity_task->execute()
line 145 of /backup/util/plan/backup_plan.class.php: call to base_plan->execute()
line 567 of /backup/controller/backup_controller.class.php: call to backup_plan->execute()
line 136 of /backup/util/ui/backup_ui.class.php: call to backup_controller->execute_plan()
line 176 of /backup/backup.php: call to backup_ui->execute()
```

**Comment by bernhard-wunderbyte** [comment]
I just pushed a commit that should fix this issue. Please check out the branch **feature_moodle4**

**Comment by bernhard-wunderbyte** [comment]
If you still have problems, please go to **_yourURL_/admin/settings.php?section=modsettingbooking**, scroll down to **Duplication, backup and restore** and deactivate the checkbox next to **Include entitities**.

**Comment by dasistwas** [comment]
@bernhard-wunderbyte the booking plugin should not in any way depend on local entities. Why do we need a new branch?

**Comment by bernhard-wunderbyte** [comment]
We don't. It's part of dev_bernhard too :-)

**Comment by baltaner** [comment]
@bernhard-wunderbyte
Thanks a lot! This fix works for me! I tested backup/restore/import/delete of a course with mod-booking.

**Comment by bernhard-wunderbyte** [comment]
@baltaner Great! I'm glad that I could help :-)

**Comment by dasistwas** [comment]
@bernhard-wunderbyte booking should auto-detect if entities is installed (for future versions=
