### ISSUE TITLE
Undesired cancellation of booking options

### ISSUE THREAD

**Issue by pax77-dd** [Wunderbyte-GmbH/moodle-mod_booking#199]
Hello all,
I have noticed that if a participant cancels one booking option in a booking that contains several booking options and cancellation is allowed, all other booking options that he has booked are also automatically cancelled. Is this intentional or a bug? 
Best regards
Remo

**Comment by dasistwas** [comment]
@pax77-dd could you specify which version you are using. Moodle and booking.

**Comment by pax77-dd** [comment]
Yes, of course: moodle: Moodle 3.10.11 (Build: 20220509); Booking: mod_booking v7.0.22.02 2021112902

**Comment by bernhard-wunderbyte** [comment]
@pax77-dd  I could not reproduce this. Could you please try it again and check if it continues to happen? If yes, I would need more information of the exact configuration of your booking instance and individual booking options (maybe screenshots).

**Comment by bernhard-wunderbyte** [comment]
One more thing: Maybe you are confusing multiple dates sessions with booking options here. A booking instance can contain booking options. Each booking options can contain multiple option dates (we can also call them "sessions"). The important thing is: Option dates (sessions) can only be deleted by an administrator. Cancellation always works on booking option level. It is not possible for a user to cancel for specific sessions. If a user cancels a booking option, he will therefore always cancel all sessions. This is intended this way.
