### ISSUE TITLE
Assign teacher to option not possible 

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#200]
Alessandro Carniato
Do, 14. Jul 2022, 15:33
Via
https://moodle.org/plugins/mod_booking
Good morning,
report a bug. When assigning a teacher to a booking option it is not possible to select a single teacher because the entire page is selected

**Comment by bernhard-wunderbyte** [comment]
I could not reproduce this (Moodle 4.0.2 / Booking 7.2.3).

**Comment by Sandrokkan** [comment]
The problem manifests itself with moodle 3.11.1 and Fordson Theme. Version plugin .7.0.22.02

**Comment by dasistwas** [comment]
@Sandrokkan it would be helpful to have a step by step description what you do, so we can reproduce it.

1) You click on the course page on the booking activity link as manager
2) on the booking options overview you select "manage x answers"
3) ....

**Comment by Sandrokkan** [comment]
I click on edith teacher

![Immagine 2022-07-15 153005](https://user-images.githubusercontent.com/109354224/179250191-f9d360be-e143-453c-8881-e91d77eaa3f2.png)

**Comment by Sandrokkan** [comment]
It is not possible to select a single user if the entire page is selected

![Immagine 2022-07-15 170259](https://user-images.githubusercontent.com/109354224/179250902-67fd08b6-767d-46db-bf9e-87afd69b2779.png)

**Comment by bernhard-wunderbyte** [comment]
Could you temporarily switch to another theme and test this again? I have a suspicion that this problem might be caused by the theme or by the CSS settings on your platform.

**Comment by Sandrokkan** [comment]
I have reset the Boost theme and uninstalled and reinstalled the plug in but the problem persists

**Comment by Sandrokkan** [comment]
I confirm that on another platform the problem does not occur

**Comment by bernhard-wunderbyte** [comment]
Okay, as this is not a general booking bug, I will close this issue. (If you need further help, we can of course offer you a paid support package.)
