### ISSUE TITLE
Stornierung mit Cent Beträgen: Guthaben wird nicht angerechnet

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#205]
Bei Preisen ohne Kommazahlen (natürliche Zahlen) funktioniert die Guthabenanrechnung für den User. Bei einer Zahl mit Cent Beträgen Beispiel: 40.50, wird kein Guthaben angerechnet.

**Comment by bernhard-wunderbyte** [comment]
Fix: 94e75d6b25a8ca32e2bca4bc8d6630b7e75b8343

**Comment by bernhard-wunderbyte** [comment]
Not a mod_booking but a local_shopping_cart issue: https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart
