### ISSUE TITLE
SQL error on creating booking option

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#207]
The following error message occurs when creating a new booking option, but also afterwards in the overview. The Moodle instance is a very fresh clone of the AllInOne repo and should also be compatible with the Postgres 14.4 and PHP 7.4

![Bildschirmfoto vom 2022-07-21 11-31-56](https://user-images.githubusercontent.com/1620975/180740781-d17e6446-4bb2-4eae-95ef-09092ef6df60.png)
.

**Comment by dasistwas** [comment]
there is an empty select field after bo.* or a comma that should not be there in the query.

**Comment by bernhard-wunderbyte** [comment]
Fixed in Booking 7.2.6 (2022072500)

**Comment by dasistwas** [comment]
Fix: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/0a9e31fc7581dd734ec52fb20c966f67112bcb9a
