### ISSUE TITLE
Booking with Moodle 404

### ISSUE THREAD

**Issue by alaasaeeddct** [Wunderbyte-GmbH/moodle-mod_booking#211]
Dears,
booking plugin showing error with version 4, hope that you can create new build for version 4 and above.

Exception - Class 'moodleform' not found

[More information about this error]

(https://docs.moodle.org/400/en/error/moodle/generalexceptionmessage)
![Screen Shot 2022-09-23 at 3 59 50 PM](https://user-images.githubusercontent.com/71432764/191955646-77e34ddf-97fb-4239-8dda-7d4b136df408.png)

**Comment by dasistwas** [comment]
Could you spedify which booking version you are using?

**Comment by alaasaeeddct** [comment]
v7.0.22.02
<img width="991" alt="Screen Shot 2022-09-25 at 10 45 57 PM" src="https://user-images.githubusercontent.com/71432764/192160105-d993b502-9c56-43a0-b246-0820afb0b516.png">

**Comment by dasistwas** [comment]
This version does not support M4. There will be a version for M4 in about three weeks. This is going to be a major rewrite of the plugin and therefore it is not yet ready to be used for M4.
![Screenshot 2022-09-25 at 20-50-05 Moodle plugins directory Booking](https://user-images.githubusercontent.com/1620975/192160243-5fc70f29-fdb7-431e-9b65-e0a8d8aad10b.png)

**Comment by alaasaeeddct** [comment]
Great so will wait for it thanks a lot for your support
