### ISSUE TITLE
privacy\provider // get_contexts_for_userid() // MariaDB, SQL doesn't work

### ISSUE THREAD

**Issue by ghost** [Wunderbyte-GmbH/moodle-mod_booking#213]
Following SQL works fine with PostgreSQL, but don't work with MariaDB. ???

CASE: // No field name available. ...

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UNION
            (SELECT DISTINCT c.id
            FROM mdl_context c
      ...' at line 10

              SELECT ctx.id AS ctxid, ctx.path AS ctxpath, ctx.depth AS ctxdepth, ctx.contextlevel AS ctxlevel, ctx.instanceid AS ctxinstance, ctx.locked AS ctxlocked
                FROM mdl_context ctx
               WHERE ctx.id IN ((SELECT DISTINCT c.id
            FROM mdl_context c
            INNER JOIN mdl_course_modules cm ON cm.id = c.instanceid AND c.contextlevel = ?
            INNER JOIN mdl_modules m ON m.id = cm.module AND m.name = ?
            INNER JOIN mdl_booking boo ON boo.id = cm.instance
            INNER JOIN mdl_booking_answers ans ON ans.bookingid = boo.id
            WHERE ans.userid = ?)
            UNION
            (SELECT DISTINCT c.id
            FROM mdl_context c
            INNER JOIN mdl_course_modules cm ON cm.id = c.instanceid AND c.contextlevel = ?
            INNER JOIN mdl_modules m ON m.id = cm.module AND m.name = ?
            INNER JOIN mdl_booking boo ON boo.id = cm.instance
            INNER JOIN mdl_booking_teachers tea ON tea.bookingid = boo.id
            WHERE tea.userid = ?))
[array (
  0 => 70,
  1 => 'booking',
  2 => 9026,
  3 => 70,
  4 => 'booking',
  5 => 9026,
)])

**Comment by dasistwas** [comment]
Thank you for reporting that. Could you provide booking version and Moodle version you use?

**Comment by ghost** [comment]
Moodle - 3.9.17
MariaDB - 10.3.36
mod_booking - v7.0.22.02

**Comment by bernhard-wunderbyte** [comment]
Fixed in mod_booking v7.6.2 (Branch: main)
