### ISSUE TITLE
Some placeholders in Booking confirmation are not working (Moodle4.1/mod_booking7.7.3)

### ISSUE THREAD

**Issue by baltaner** [Wunderbyte-GmbH/moodle-mod_booking#215]
Hi,
just a small issue of a short test of (Moodle4.1/mod_booking7.7.3).
Following placeholders don't work in the confirmation mail - they are displayed as shown below:
	•	{teacher}
	•	{teacherN} - N is number of teacher ex. {teacher1}
	•	{gr_id} - Insert QR code with user id
	•	{gr_username? - Insert QR code with user username
	•	{times} - Session times

Thanks for your great work!
Bertold

**Comment by dasistwas** [comment]
Just for information: The notifications are currently rewritten into a more general way so you can configure message triggers and message text in a more flexible way.

**Comment by bernhard-wunderbyte** [comment]
Hi, I just tested this. The placeholders, {qr_id} and {qr_username} are NOT broken, you just had a typo: The first letter is a "q" not a "g" ;-) I will repair the other ones.
@baltaner

**Comment by baltaner** [comment]
Hi,
thank you!
Yes, it was a typo!

**Comment by bernhard-wunderbyte** [comment]
All placeholders have been fixed now in **Version 7.7.4 (Branch: main).**

**Note:** We renamed {times} to **{dates}** now and also introduced the new placeholder **{teachers}** to show a list of teachers, whereas {teacher} will always show the full name of the first teacher and {teacherN} will show the name of a specific teacher (e.g. {teacher2} will show the full name of the second teacher).
