### ISSUE TITLE
Moodle 4.x version

### ISSUE THREAD

**Issue by francescor** [Wunderbyte-GmbH/moodle-mod_booking#216]
Hello!
thanks so much for your code!

we can't wait for the Moodle 4 version :) 

any news on when it may be available? 

thanks

**Comment by bernhard-wunderbyte** [comment]
It's already available! You can download it here: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/tags/v7.8.7.01.zip
