### ISSUE TITLE
Unsupported $module syntax detected in version.php of the mod_booking plugin.

### ISSUE THREAD

**Issue by nitro2010-zz** [Wunderbyte-GmbH/moodle-mod_booking#22]
Hello,

Please update your plugin for Moodle v3.0

While installating I get errors [all text with debugging option on]:

Unsupported $module syntax detected in version.php of the mod_booking plugin.
line 322 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 758 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 668 of /admin/index.php: call to core_plugin_manager->all_plugins_ok()
Plugin mod_booking does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 758 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 668 of /admin/index.php: call to core_plugin_manager->all_plugins_ok()
Skip to main content
sasas
Plugin "mod_booking" is defective or outdated, can not continue, sorry.

More information about this error

Debug info: Unsupported $module syntax detected in version.php
Error code: detectedbrokenplugin
Stack trace:
line 612 of /lib/upgradelib.php: plugin_defective_exception thrown
line 427 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1641 of /lib/upgradelib.php: call to upgrade_plugins()
line 677 of /admin/index.php: call to upgrade_noncore()
Continue
Purge all caches

**Comment by miotto** [comment]
Replace in File version.php following lines
$module->version = 2015082600;
$module->requires = 2013111800;  // Requires this Moodle 2.X version
$module->release = '2.7';
$module->maturity = MATURITY_STABLE;
$module->cron = 5;

with the following lines
$plugin->version = 2015082600;
$plugin->requires = 2013111800;  // Requires this Moodle 2.X version
$plugin->release = '2.7';
$plugin->maturity = MATURITY_STABLE;
$plugin->cron = 5;

and add line 
$plugin->component = 'mod_booking'; // Declare the type and name of this plugin

I think it could work.

**Comment by aspark21** [comment]
You will need to update the version.php to the following:

$plugin->version = 2015082600;
$plugin->requires = 2013111800;  // Requires this Moodle 2.X version
$plugin->release = '2.7';
$plugin->maturity = MATURITY_STABLE;
$plugin->cron = 5;
$plugin->component = 'mod_boking';

**Comment by nitro2010-zz** [comment]
ok, thanks, it works...

please accept my pull request...

**Comment by dasistwas** [comment]
Hi,

please note, that Moodle versions above 2.7 are currently not supported and that this issue might not be the only to solve. 

Kind regards,
David

**Comment by pavelsokolov** [comment]
It works very well in in Moodle 2.7-2.9. So far this issue is the only one that prevents to use the module in 3.0. You changed $module to $plugin, but didn't add "$plugin->component = 'mod_booking';"
