### ISSUE TITLE
Error in calendar

### ISSUE THREAD

**Issue by Sandrokkan** [Wunderbyte-GmbH/moodle-mod_booking#222]
When a registered user is given the opportunity to register other users (teacher modification function) the error "Sorry, but you do not have permission to update the calendar event." appears. The booking is successful but the booking does not appear in the user calendar.
Moodel 3.11.11, Fordson theme

**Comment by dasistwas** [comment]
Seems to be the same as this, which reached us via email:

in the booking plugin I encountered a problem. If I assign the teacher role to a student to make him book for others, when the user books a message appears saying that he cannot update the calendar even if the booking option is not selected the calendar

**Comment by Sandrokkan** [comment]
Yes, sorry if I repeated myself

**Comment by gemguardian** [comment]
@dasistwas We have this issue as well in Moodle 3.9 / Essential Theme.

**Comment by gemguardian** [comment]
@dasistwas it seems to related to: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/208

**Comment by bernhard-wunderbyte** [comment]
I just fixed this for the MOODLE_39_STABLE branch.

@Sandrokkan Could you please tell me which version of Booking you are using with Moodle 3.11?

**Comment by Sandrokkan** [comment]
Thanks for the great job. I am using version v7.0.22.02 (2021112902)

**Comment by Sandrokkan** [comment]
Can I ask when the next version will be available?

**Comment by bernhard-wunderbyte** [comment]
@dasistwas will publish it in January, I guess. If you cannot wait, you can just get it from Github: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/MOODLE_39_STABLE.zip

**Comment by Sandrokkan** [comment]
Thank you very much and congratulations for the excellent work
