### ISSUE TITLE
Hidden edit button

### ISSUE THREAD

**Issue by Sandrokkan** [Wunderbyte-GmbH/moodle-mod_booking#223]
As you can see from the screenshot the edit option button is hidden.
![Immagine 2023-01-01 100733](https://user-images.githubusercontent.com/109354224/210165942-8373a7fe-af52-43bc-90a4-9fcc0b9d4b6c.png)
Moodle 3.11.11+ theme Boost

**Comment by dasistwas** [comment]
This is a CSS problem. Maybe increasing z-index of the menu would solve the problem.

**Comment by Sandrokkan** [comment]
Please would it be possible to download the plugin when the bug is fixed?
Thank you

**Comment by bernhard-wunderbyte** [comment]
Fixed in Booking 7.0.22.15 - download at: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/MOODLE_39_STABLE.zip

@dasistwas Please publish the new version on Moodle.org

**Comment by Sandrokkan** [comment]
Thanks so much!
