### ISSUE TITLE
Course copy issue

### ISSUE THREAD

**Issue by mbaddar** [Wunderbyte-GmbH/moodle-mod_booking#224]
I have create a booking in a course, then copied it, and tried to copy a booking option inside a booking. 
On my first use of booking and booking options, no error was encountered, and then only when I duplicated a booking option I got this error: 
Exception - Class 'moodleform' not found
Stack trace:

    line 25 of /mod/booking/classes/form/option_form.php: Error thrown
    line 139 of /lib/classes/component.php: call to include_once()
    line ? of unknownfile: call to core_component::classloader()
    line 50 of /mod/booking/editoptions.php: call to spl_autoload_call()

I'm using Moodle 4.2dev so probably out of scope of current release. What I don't understand is why booking works with one course and throws this error on duplicate (and even new) courses

**Comment by mbaddar** [comment]
I have created another Moodle instance (4.1 stable) and the problem now persists throughout. Adding a booking option will throw that error and fail

**Comment by mbaddar** [comment]
Since I am desperately behind schedule I had the liberty to add 2 lines to: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/blob/fb757ffcccda2dabf3d6c333489c0364de70928f/classes/form/option_form.php#L17
```
global $CFG;
require_once($CFG->libdir . '/formslib.php');
```
And the issue disappeared. I am not an expert in PHP, so I will leave it up to the contributors to decide whether that code (or something more conformant) should be added to the next release

**Comment by dasistwas** [comment]
@mbaddar which booking version do you use? with 4.2 you have to use one of the 7.2 versions and not 7.0. I would recommend to use the USI branch.

**Comment by mbaddar** [comment]
I'm using the release related to issue #225 (https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v7.0.22.14). Have you incorporated this issue on the USI branch? Happy to use it if you did

**Comment by dasistwas** [comment]
Hi @mbaddar, the USI branch is not yet to be used in production. But you can test it or use it in your dev environment. Also it does only work on Moodle 4 and newer.

**Comment by bernhard-wunderbyte** [comment]
I could not reproduce this with v7.0.22.15 in Moodle 3.9.
If you want to **test** the development version of Booking for **Moodle 4.0 or newer**, then please use the newest one on the USI-Branch at https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/USI.zip
