### ISSUE TITLE
Autoenrol button behaviour

### ISSUE THREAD

**Issue by mbaddar** [Wunderbyte-GmbH/moodle-mod_booking#225]
The auto enrol option `(Miscellaneous settings > Automatically enrol users)` make it possible to "Enrol users only if either:
- Course has already started,
- Or booking option is set to immediately enrol users."
 The responses page will not have an enrol button if the auto enrol option is active. So this makes enrolling users who I would want to enrol for booking options having future dates a manual process. Am I missing something? I suggest to enable to button regardless of the auto enrol option 

Edit:
There seems to be a cron task that takes care of future enrolling. Yet it keeps on failing on my instance:

```
Execute scheduled task: Booking (mod_booking\task\enrol_bookedusers_tocourse)
... started 23:10:02. Current memory use 41.9 MB.
WARNING: Failed to get booking instance from option id: 1
... used 2 dbqueries
... used 0.0059142112731934 seconds
Scheduled task failed: Booking (mod_booking\task\enrol_bookedusers_tocourse),Can't find data record in database.
Debug info:
SELECT cm.*, m.name, md.name AS modname 
              FROM {course_modules} cm
                   JOIN {modules} md ON md.id = cm.module
                   JOIN {booking} m ON m.id = cm.instance
                   
             WHERE cm.id = :cmid AND md.name = :modulename
                   
[array (
  'cmid' => NULL,
  'modulename' => 'booking',
)]
Backtrace:
* line 1266 of /lib/datalib.php: call to moodle_database->get_record_sql()
* line 87 of /mod/booking/classes/booking.php: call to get_coursemodule_from_id()
* line 125 of /mod/booking/classes/booking_option.php: call to mod_booking\booking->__construct()
* line 51 of /mod/booking/classes/task/enrol_bookedusers_tocourse.php: call to mod_booking\booking_option->__construct()
* line 259 of /lib/cronlib.php: call to mod_booking\task\enrol_bookedusers_tocourse->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()
```

**Comment by mbaddar** [comment]
This is oddly related to a closed issue #185. I'm using v7.0.22.13 which should not have this

**Comment by dasistwas** [comment]
Hi @mbaddar , thank you for reporting this. In fact this has not been backported to MOODLE_39_STABLE branch. But it is there for Moodle 4 onwards (which is not yet officially released. I did now backport it and released the new version:
Fixed in: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v7.0.22.14

**Comment by mbaddar** [comment]
Thanks a lot, I just tested it in one booking instance and one response and it works. I'll do more tests. You saved me a lot of hassle so thanks again
