### ISSUE TITLE
Booking option template does not retain some flags

### ISSUE THREAD

**Issue by mbaddar** [Wunderbyte-GmbH/moodle-mod_booking#226]
I found out that saving a booking option template and reusing it to create new ones does not retain the  `Limit the number of participants` flag. Is this by design?

**Comment by dasistwas** [comment]
thank you for reporting the problem. could you specify the booking version?

**Comment by bernhard-wunderbyte** [comment]
I fixed this now in Booking 7.8.7 (Moodle 4.0+) in the Moodle 4.0 Development branch. If you want to test it, you can download it here: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/MOODLE_400_DEV.zip (You'll need Moodle 4.0 or 4.1)
