### ISSUE TITLE
Problem categories

### ISSUE THREAD

**Issue by Sandrokkan** [Wunderbyte-GmbH/moodle-mod_booking#227]
Once a category is selected, it cannot be deselected
The only way to delete the category is to create a subcategory and then move the first category as a subcategory of the second
Moodle 3.11.11+ Theme Fordson

**Comment by dasistwas** [comment]
OK, that's another thing someone else implemented. Does it make any sense or should we get rid of it?

**Comment by dasistwas** [comment]
@bernhard-wunderbyte could we check if that's something we can remove?

**Comment by Sandrokkan** [comment]
I think it is useful because users, by clicking on the category, can see all the courses belonging to that category. For example, the "Health" category could show all related courses (cardiology, urology, etc.)

**Comment by dasistwas** [comment]
Actually you can unselect the category by using "CTRL+Left Mouse click". But this is a horrible user interfase. There are better form elements for displaying multislect options. I think we are going to remove that soon and replace it with a more modern tagging system. Also you can already use Moodle tags as well. So I recommend to not use category but Moodle tags instead.

**Comment by Sandrokkan** [comment]
Great, thank you very much

**Comment by bernhard-wunderbyte** [comment]
I will close this issue for now. We will implement a more modern tagging system in one of the next booking versions.
