### ISSUE TITLE
Problem Edit institutions

### ISSUE THREAD

**Issue by Sandrokkan** [Wunderbyte-GmbH/moodle-mod_booking#230]
In the settings of the option if I go to edit institution and create an institution this is saved but does not appear in the Add new institution menu

**Comment by dasistwas** [comment]
not sure what is exactly the problem: first you add an institution to the institution list, then you add it to the booking option?

**Comment by Sandrokkan** [comment]
After adding an institution using the edit institution command, I don't see it in the list of available institutions

**Comment by bernhard-wunderbyte** [comment]
The form to edit institutions is not needed anymore in newer versions of booking as institutions can be added directly with the autocomplete field in the form for booking options. (You can just directly enter a name for an institution with no need to go to the "edit institution" form anymore.)

In the new versions 7.0.22.16 (Branch: MOODLE_39_STABLE for Moodle 3.9 / 3.11) and 7.8.3 (Branch: MOODLE_400_DEV for Moodle 4.0), we removed the link and the old way of editing institutions completely.

**Comment by Sandrokkan** [comment]
A thousand thanks.
Please could I have the download link?

Il giorno lun 16 gen 2023 alle ore 16:38 bernhard-wunderbyte <
***@***.***> ha scritto:

**Comment by bernhard-wunderbyte** [comment]
Just go to https://github.com/Wunderbyte-GmbH/moodle-mod_booking and select your preferred branch - either MOODLE_39_STABLE (stable for 3.9/3.11) or MOODLE_400_DEV (4.0, for testing purposes only). Then click on the Dropdown-Button "Code" > "Download ZIP"

**Comment by Sandrokkan** [comment]
Thanks so much

Il giorno lun 16 gen 2023 alle ore 16:49 bernhard-wunderbyte <
***@***.***> ha scritto:
