### ISSUE TITLE
Completion status teacher

### ISSUE THREAD

**Issue by Sandrokkan** [Wunderbyte-GmbH/moodle-mod_booking#232]
I don't understand this function. It should allow you to mark the activity as done for teachers. Not only does this not work (flagged users are not completed) but I don't understand the utility as it is possible to do the same thing in the response management screen
![Immagine 2023-01-14 213842](https://user-images.githubusercontent.com/109354224/212495901-b89a2846-84ea-40f6-95bd-69733e32e8a2.png)

**Comment by dasistwas** [comment]
Hi,
this is a feature that was implemented by another programmer. Apparently it was a request by a client. Marking teacher as completed might enable tracking of teacher participation. We might abandon this feature in the future....

**Comment by Sandrokkan** [comment]
Thanks a lot for the answer
