### ISSUE TITLE
Address in Mailing

### ISSUE THREAD

**Issue by sabing** [Wunderbyte-GmbH/moodle-mod_booking#238]
bis zur Version v7.0.22.02 (2021112902) haben wir in den Bestätigungsmails das Feld {address} verwendet, um die Adresse der Buchungsoption an die Teilnehmer weiterzugeben.
Seit dem Update auf v7.0.22.15 (2021112915) erscheint leider nicht mehr die Buchungs-Adresse in diesem Feld, sondern die Adresse des _Teilnehmers_.
Wir verwenden Moodle 3.11.12 (Build: 20230116)

**Comment by bernhard-wunderbyte** [comment]
Vielen Dank für den Hinweis. Wir haben den Fehler in Booking v7.0.22.17 behoben. Sie können die neue Version hier herunterladen: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/MOODLE_39_STABLE.zip
