### ISSUE TITLE
text under booking option depending on booking status

### ISSUE THREAD

**Issue by jharej** [Wunderbyte-GmbH/moodle-mod_booking#239]
Hello,

I've installed booking module version 2022120900 on Moodle 4.1+ (Build: 20221209, fresh install), then I created moodle option and set the text that should display depending of user's booking status. 

The sistem does not display the correct text when the completion status of the user is "confirmed".

![booking2](https://user-images.githubusercontent.com/10975112/214677146-74349f4f-6c8f-4dba-a612-c9a5152d147b.png)

**Comment by dasistwas** [comment]
do you mean activity completion or booking option completion?

**Comment by bernhard-wunderbyte** [comment]
In Booking 8, all of these 3 texts work correctly, so I'll close this issue for now.
