### ISSUE TITLE
wrong information in the menu

### ISSUE THREAD

**Issue by jharej** [Wunderbyte-GmbH/moodle-mod_booking#240]
Hello,

I create a new booking option and as administrator choose Manage responses. If I click on menu More, I can see that the option selected is Delete this booking option. This is not right. Maybe nothing should be selected in menu?  If I try to click on this option I get an error "A required parameter (sesskey) was missing". So from this point it is not possible to delete the booking option that I currently manage responses for. 
 
![booking3](https://user-images.githubusercontent.com/10975112/214684326-03091a0b-8da8-4340-9c8b-9e1db5f9c8ad.png)

**Comment by bernhard-wunderbyte** [comment]
I fixed this now in Booking 7.8.7 (Moodle 4.0+) in the Moodle 4.0 Development branch. If you want to test it, you can download it here: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/MOODLE_400_DEV.zip 

Please note that Booking for Moodle 4.0/4.1 is still a developer preview and not officially released yet.
