### ISSUE TITLE
duplicate does not work

### ISSUE THREAD

**Issue by jharej** [Wunderbyte-GmbH/moodle-mod_booking#241]
Hello, 

If I try to duplicate booking module in the course, I get an error: error/baseelementincorrectfinalorattribute

moodle 4.1, booking version 2022120900

![booking-duplicate](https://user-images.githubusercontent.com/10975112/214686572-debff65e-5124-4e25-b4e4-52dda3749f3a.png)

**Comment by bernhard-wunderbyte** [comment]
This has already been fixed. Please update to the newest version of booking (currently 7.8.6) on branch MOODLE_400_DEV. You can download it here: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/MOODLE_400_DEV.zip

(Please note that booking for Moodle 4.0/4.1 is still a developer preview.)
