### ISSUE TITLE
missing link to manage custom report templates

### ISSUE THREAD

**Issue by jharej** [Wunderbyte-GmbH/moodle-mod_booking#242]
Hello,

on Moodle 4.1 and booking version ... I miss the link to the form for adding/uploading custom report templates - i/mod/booking/customreporttemplates.php?id=... If I enter the url manual, I can upload templates and then download the report. 

Have I forgot some setting or ... 

bye

**Comment by dasistwas** [comment]
Which version do you use? Do you use a 7.0.xxx version or something like [v7.8.5]. Do not use 7.0.xx with M4 and above.

**Comment by jharej** [comment]
Ok, now testing on v.7.8.7. Link ok.
