### ISSUE TITLE
generating numbers 

### ISSUE THREAD

**Issue by jharej** [Wunderbyte-GmbH/moodle-mod_booking#243]
I create a booking and choose the setting "Enable rec. number generation?". Then I go to booking option and choose Manage responses. If I click the button "Generate numbers" I see, that the generated numbers don't start with 1 and sometimes the numbers are not consecutive.

![booking-generate-numbers](https://user-images.githubusercontent.com/10975112/214690722-9ff422f4-799b-419a-b4d1-805898da4042.png)

**Comment by jharej** [comment]
I'have tested it on booking version 7.8.7. It works just first time. All the next times booked users get higher and higher numbers. The right thing would be, that the numbers always start with 1.

**Comment by atlet** [comment]
This is working fine. If you generate numbers for all users, then will begin from 1. If you select only a few participants they will get number from last biggest number.

Also I fixed a bug as this wasn't working with PostgreSQL.

**Comment by bernhard-wunderbyte** [comment]
I added an additional check, so that - if you select all answers - it will always start from 1. Also, I had to add "AND waitinglist < 2" to all SQL-selects of the booking_answers table (we have more than 2 waitinglist-params in newer booking versions).
