### ISSUE TITLE
Probleme mit Benachrichtigungen an Teilnehmer und Buchungsverwalter

### ISSUE THREAD

**Issue by moddleupdaterHS** [Wunderbyte-GmbH/moodle-mod_booking#244]
Sehr geehrte Damen und Herren,

wir verwenden das mod_booking in der Version 7.5.5 (2022041900). In dem betroffenen Moodlekurs wird die Buchungsaktivität mehrfach verwendet. In jeder Buchungsaktivität gibt es mehrere Buchungsmöglichkeiten für Termine. 

Normalerweise erhält die buchende Person eine Bestätigung und der Buchungsverwalter eine Kopie der E-Mails, die an die buchende Person verschickt wurden. Dies ist auch in den Einstellungen hinterlegt.

Bei uns kommt allerdings keine Kopie der E-Mail mehr beim Buchungsverwalter an, wenn ein eingeschriebener Teilnehmer mit der Rolle Student einen Termin bucht. Welche Möglichkeiten haben wir dieses Problem zu beheben?

Viele Grüße

**Comment by dasistwas** [comment]
This is a duplicate of  #238 and has been fixed. Please refer to the other ticket.

**Comment by moddleupdaterHS** [comment]
Wir verwenden Moodle 4.0.4+ (Build: 20220922)- funktioniert die vorgeschlagene Lösung auch damit?

**Comment by dasistwas** [comment]
4.0.4 unterstützen wir offiziell noch nicht. @bernhard-wunderbyte  was meinst du dazu?

**Comment by bernhard-wunderbyte** [comment]
@dasistwas Kein Duplikat von #238 - habe das Ticket erneut geöffnet und werde mir das ansehen.

**Comment by bernhard-wunderbyte** [comment]
Bug fixed in Booking version 7.8.6 (Branch: MOODLE_400_DEV)

You can download the latest version for Moodle 4.0 (developer preview) here: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/MOODLE_400_DEV.zip
