### ISSUE TITLE
Exception - Class 'moodleform' not found

### ISSUE THREAD

**Issue by goose2000** [Wunderbyte-GmbH/moodle-mod_booking#245]
**Describe the bug**
I was successfully using the 3.11 version with Moodle 4.0. I then updated to 4.0.6 and after that I would get this error when trying to make a new booking option: Exception - Class 'moodleform' not found
That would happen on the editoptions.php script like:
mod/booking/editoptions.php?id=7564&optionid

**Versions uses**
Moodle version: 4.0.6
Booking version: v7.0.22.02 ( 2021112902 )

**To Reproduce**
Upgrade your moodle to 4.0.6 and try to create a new booking option

**Expected behavior**
Create and save a new booking option

**Additional context**
Thank you for all the work on this module.

**Comment by dasistwas** [comment]
The booking version used is not compatible with M4.0. I will release the correct version for M4 today.
