### ISSUE TITLE
Sort by booking name for existing booking option not working on overview 

### ISSUE THREAD

**Issue by moddleupdaterHS** [Wunderbyte-GmbH/moodle-mod_booking#246]
**Describe the bug**
In existing bookings, the booking overview does not show the correct order of booking options, although sort by booking name is selected in the settings of the booking options.

**Versions uses**
Moodle version: 4.0.4+ (Build: 20220922)
Boooking version:  7.8.6 (Branch: MOODLE_400_DEV)

**To Reproduce**
Problems occur only for existing booking options. Works fine for new ones.

**Expected behavior**
The booking should show the correct order of each booking option on the overview. Which is the case with every newly created booking option.

**Screenshots**
![image](https://user-images.githubusercontent.com/123622895/218717133-32dd7076-826f-4a99-8140-2d88591def53.png)

Best Regards.

**Comment by dasistwas** [comment]
Thank you for reporting that bug. We are going to have a look a that.

**Comment by bernhard-wunderbyte** [comment]
The feature to show a list of booking options right on the course page will be removed in the next release of booking.

**Comment by bernhard-wunderbyte** [comment]
The next release of Booking will however support multiple ways of sorting, full text search and filtering possibilities.
