### ISSUE TITLE
Update form 7.8.7 to 7.9.0: Unavailable missing dependencies Not in the Plugins directory: local_wunderbyte_table

### ISSUE THREAD

**Issue by baltaner** [Wunderbyte-GmbH/moodle-mod_booking#249]
**Describe the bug**
Update form 7.8.7 to 7.9.0: Unavailable missing dependencies Not in the Plugins directory: local_wunderbyte_table

**Versions uses**
Moodle version: 4.1.1+ (Build: 20230217)
Boooking version:  7.8.7

**To Reproduce**
Try to update mod_booking from 7.8.7 to 7.9.0
During update following message appears:

Unavailable missing dependencies
Not in the Plugins directory: local_wunderbyte_table.

**Comment by dasistwas** [comment]
Please do only install the releases from moodle.org. Installing from github ist not recommended. But the message is clear. You need to install that plugin too:
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table

**Comment by baltaner** [comment]
Hello David,
sorry - I thought it is helpful when I report those issues.
And yes, the message is clear for me that I have to install that additional plugin.
Thank you for your great work on this plugin!
Bertold

**Comment by dasistwas** [comment]
Thank you. Your feedback is always appreciated. Thank you for contributing and trying to make the booking module better.
