### ISSUE TITLE
Display the dates beside all booking options by default

### ISSUE THREAD

**Issue by jharej** [Wunderbyte-GmbH/moodle-mod_booking#251]
Is it possible to display the dates beside booking options by default? It's very time consuming for users to click on each icon to display dates in order to get the dates. We use booking to organize workshops for teachers. Teachers choose a workshop based on when and where it is held. So they have to click on the icon in order to make the decision ... 

Moodle 4.1, booking version 7.8.7

![booking-dates](https://user-images.githubusercontent.com/10975112/221852861-eaab22b3-d714-49e9-ac19-f7daeb1ba7e5.png)

thanks for the answer

**Comment by miotto** [comment]
You can change some code `aria-expanded="false" > aria-expanded="true"` and `class="collapse" > class="collapse show"`  in the `templates/col_coursestarttime.mustache` file, then the dates will be displayed by default. 
This is how the commitdiff looks like.
```
diff --git a/templates/col_coursestarttime.mustache b/templates/col_coursestarttime.mustache
index 3775ac37..db4b86b7 100755
--- a/templates/col_coursestarttime.mustache
+++ b/templates/col_coursestarttime.mustache
@@ -25,10 +25,10 @@
 }}
 
 {{#showcollapsebtn}}
-    <a data-toggle="collapse" href="#optiondates{{{optionid}}}" role="button" aria-expanded="false" aria-controls="optiondates{{{optionid}}}">
+    <a data-toggle="collapse" href="#optiondates{{{optionid}}}" role="button" aria-expanded="true" aria-controls="optiondates{{{optionid}}}">
         <i class="fa fa-calendar"></i> {{#str}}showdates, mod_booking{{/str}}
     </a>
-    <div class="collapse" id="optiondates{{{optionid}}}">
+    <div class="collapse show" id="optiondates{{{optionid}}}">
         <small>
         {{#datestrings}}
             <div>{{{datestring}}}</div>
```

**Comment by jharej** [comment]
I guess it would be proper to trigger this from the settings as there are obviously different expectations from users using this plugin.

**Comment by dasistwas** [comment]
The goal is to have a tidy overview of all booking options. If a booking instance has 20 option dates, we would have a problem. But there could be the possibility to collapse/show all at once.

**Comment by jharej** [comment]
I think that at the end we will still argue, what is the default behaviour. I still suggest that this becomes part of settings.

**Comment by jharej** [comment]
I have also discovered that in that space just dates entered in section Dates get displayed. The start and end date in the General section of setting is ignored. This is certainly not right. Version 7.8.7

Section General - this dates are ignored, only the duration is displayed - suggestion: this date gets always displayed
![dates-start](https://user-images.githubusercontent.com/10975112/223805494-08ba320e-e9b0-44ac-972b-192be8e60548.PNG)

Section Dates - this dates are displayed - this can stay as it is now (shown when clicked)
![dates-only](https://user-images.githubusercontent.com/10975112/223805490-9e8d313f-8fdf-4f6b-9a41-4cddf1dfa5f8.PNG)

**Comment by dasistwas** [comment]
Start and end time of the course are different from the section dates. That are 2 different pairs of shoes with completely different use cases.

**Comment by jharej** [comment]
I am aware of that. As I understand I would use the Start and End date to mark the start and end of a course and session dates for example the dates of lectures within this course. This only means that the dates of the end/start of a course should be displayed differently. 

I suggest that the end/start date is displayed above the session dates (as it was on previous versions) if the end/start date is set in the booking option settings. Duration should be displayed beside the course start/end.

**Comment by dasistwas** [comment]
Usually we do only do bugfixes for free. If you have change requests we can send you a quote. @bernhard-wunderbyte what do you thank of those suggestions?

**Comment by bernhard-wunderbyte** [comment]
@jharej In **Booking 8**, we have changed the behavior of dates on the view.php as follows. Once there are more than 2 dates, the dates will be collapsed, if there are only 1 or 2 dates, they are shown without collapse. However, in the future, we might add a setting to always show all dates without any collapsing, if that is preferred. It's in our backlog, but not our top priority right now.

As for the other issue: Yes, we are aware of that. However, the way the date of a booking option (set in the option form) and the dates of individual sessions (optiondates) work in combination is quite complex and to re-write all the code affected by those combinations would probably take weeks. We will for sure change this in the future, but right now it works like this:

* **Case 1:** You do **not** have individual sessions (optiondates) => then you set the start and end time directly in the option form.
* **Case 2:** You do have individual sessions. Once you save them, the start time of the booking option is set to the beginning of the first individual session and the end time of the booking option is set to the end of the last session.
