### ISSUE TITLE
Hide the "Booking text" when displaying booking option information

### ISSUE THREAD

**Issue by jharej** [Wunderbyte-GmbH/moodle-mod_booking#252]
Is it possible to hide the Booking text when displaying information of the selected booking option - Manage responses page? The "manage responses" page is meant to be used by teachers or organizers, so this text just uses space ...

Testing on Moodle 4.1, booking version 7.8.7.

![booking-text](https://user-images.githubusercontent.com/10975112/221854474-c6718eae-2688-4f7c-a742-74dce8053f8e.png)

**Comment by miotto** [comment]
You can add a code line 
`$PAGE->activityheader->disable();`
in the `report.php` file, then the description will not be displayed. 

This is how the commitdiff looks like.
```
diff --git a/report.php b/report.php
index 96dd35da..f06e657b 100755
--- a/report.php
+++ b/report.php
@@ -231,6 +231,7 @@ if (!empty($bookingoption->option->titleprefix)) {
 $PAGE->navbar->add(format_string($titlestring));
 $PAGE->set_title(format_string($bookingoption->booking->settings->name) . ": " . format_string($titlestring));
 $PAGE->set_heading(format_string($course->fullname));
+$PAGE->activityheader->disable();
 
 if (isset($action) && $action == 'sendpollurlteachers' &&
          has_capability('mod/booking:communicate', $context)) {
```
So you could also prevent the double display of the description above the `view.php` file.

**Comment by dasistwas** [comment]
@bernhard-wunderbyte what do you think?

**Comment by bernhard-wunderbyte** [comment]
I already added CSS to hide the header on all pages except view.php. But I like the solution with
$PAGE->activityheader->disable(); even better.

We will definitely add this to the next developer release of booking which we hope to complete by the beginning of next week.

**Comment by bernhard-wunderbyte** [comment]
If you need a quickfix for this, you can add the following code to the styles.css in the mod/booking folder:

/* The description text should only be shown on the view.php and nowhere else. */
#page-mod-booking-edit_optiontemplate #intro,
#page-mod-booking-optiontemplatessettings #intro,
#page-mod-booking-teachers_instance_report #intro,
#page-mod-booking-recalculateprices #intro,
#page-mod-booking-importexcel #intro,
#page-mod-booking-tagtemplates #intro,
#page-mod-booking-importoptions #intro,
#page-mod-booking-customreporttemplatesadd #intro,
#page-mod-booking-customreporttemplates #intro,
#page-mod-booking-instancetemplateadd #intro,
#page-mod-booking-editoptions #intro {
    display: none;
}
