### ISSUE TITLE
Description space

### ISSUE THREAD

**Issue by Sandrokkan** [Wunderbyte-GmbH/moodle-mod_booking#254]
Good morning,
when you fill in the space for the description it appears twice on the booking page.
Moodle 4.1.1
Theme: moove
Plugin version: 7.8.7
2023012700
![Immagine 2023-03-07 163619](https://user-images.githubusercontent.com/109354224/223475951-4aabf3e1-c933-48dd-82c2-51296533c7f7.png)

**Comment by bernhard-wunderbyte** [comment]
We have fixed this issue in **Booking 8**. 

If you want to try Booking 8, you need to install **local_wunderbyte_table** first:
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/archive/refs/heads/main.zip

You can download Booking 8 from here: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/MOODLE_401_DEV.zip

**Comment by Sandrokkan** [comment]
Thank you
