### ISSUE TITLE
Wrong item in the menu selected

### ISSUE THREAD

**Issue by jharej** [Wunderbyte-GmbH/moodle-mod_booking#255]
If I open the booking and chose any booking option by clicking on Manage x responses, on the page that opens wrong item in the menu is selected.  At least in case of using version 7.8.7 the selected item is "Save booking option as template" which is wrong.

As this report can not be choosen from menu, I guess the proper behaviour would be none item selected

![manage-options](https://user-images.githubusercontent.com/10975112/223785914-11311f43-2f31-4902-a74b-1d218a3e01a4.PNG)

**Comment by dasistwas** [comment]
@jharej could you add the Moodle version and use the template for reporting bugs?

**Comment by jharej** [comment]
Bug description: When opening page Manage xy responses in the top menu there is wrong item underlined / marked as selected. 

Versions:
- moodle: $release  = '4.0.1 (Build: 20220509)';
- booking: $plugin->version = 2023012700;

Steps:
- chose any booking whit at least one booking option created
- go to registration part and click on Manage xy responses
- new page opens (/mod/booking/report.php?id=___&optionid=___)
- look at the top menu and see which option is underlined / marked as selected

Expected behaviour:
- when opening the Manage xy responses there should be no item marked as selected on top menu

Screenshot - provided at first post above.

**Comment by bernhard-wunderbyte** [comment]
We have fixed this in **Booking 8**. If you want to try Booking 8, install **Wunderbyte Table** first:
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/archive/refs/heads/main.zip

After installing Wunderbyte Table, you can now install Booking from here:
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/MOODLE_401_DEV.zip
