### ISSUE TITLE
Confirm users who completed activity or received badge - received badge does not work

### ISSUE THREAD

**Issue by jharej** [Wunderbyte-GmbH/moodle-mod_booking#256]
Hello, I'm testing version 7.8.7. I chose booking option and in menu option "Confirm users who completed activity or received badge". I chose the badge option, select the badge that I know at least one user from booked users got and click Confirm users activity (/mod/booking/confirmactivity.php). Nothing happenes - users that got the badge don't get activity/booking marked as completed.

![badge-confirm](https://user-images.githubusercontent.com/10975112/223824276-a7a76e27-cada-4d4f-8a60-5c10098904ee.PNG)

**Comment by dasistwas** [comment]
@bernhard-wunderbyte I have never seen this. Could you have a look?

**Comment by bernhard-wunderbyte** [comment]
I fixed this now. This fix will be part of releases **8.0.2** as well as the hotfix release **7.8.7.01** of mod_booking.
