### ISSUE TITLE
Remainder

### ISSUE THREAD

**Issue by Sandrokkan** [Wunderbyte-GmbH/moodle-mod_booking#259]
In the settings I have activated the sending of reminder emails but it doesn't work
Moodel 4.1.1
Moove theme
![Immagine 2023-03-12 110850](https://user-images.githubusercontent.com/109354224/224537966-ceb866a6-c988-49d2-8294-cd7e0e91532c.png)
![Immagine 2023-03-12 111041](https://user-images.githubusercontent.com/109354224/224538024-ae86d613-1c33-4ff2-a632-daabc094dcd9.png)

**Comment by dasistwas** [comment]
Is the cron job running?

**Comment by Sandrokkan** [comment]
Yes

**Comment by bernhard-wunderbyte** [comment]
There was an error caused by the new way we retrieve booked users internally. I fixed it. The fix will be part of Booking 7.8.7.01 which @dasistwas will release soon.

**Comment by Sandrokkan** [comment]
Thanks so much for the great job

**Comment by Sandrokkan** [comment]
Is it possible to download the correct zip?

**Comment by bernhard-wunderbyte** [comment]
There you go: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/tags/v7.8.7.01.zip

**Comment by Sandrokkan** [comment]
Thank you very much
