### ISSUE TITLE
The headmaster's view

### ISSUE THREAD

**Issue by jharej** [Wunderbyte-GmbH/moodle-mod_booking#260]
**Is your feature request related to a problem? Please describe.**
In our country the headmaster of each school is entitled to see which trainings have their teachers booked. So we would like to have a report for headmaster. 

**Describe the solution you'd like**
We suggest that a report is build and accessible from user's profile page for users with a special capability e.g. booking:headmastersview. The user with this capability gets the lists of users and connected bookings and information if booking is confirmed (marked as done) from the same institution. This filed is in our situation maped from shibboleth authentication and locked.  

**Describe alternatives you've considered**
/

**Additional context**
We have the resources to program this and provide the code.

**Comment by dasistwas** [comment]
Feel free to make a pull request once you have finished programming. Usually we only accept features that have behat tests included, comply with coding standards and are backward compatible.
