### ISSUE TITLE
Reminder emails not sent

### ISSUE THREAD

**Issue by goose2000** [Wunderbyte-GmbH/moodle-mod_booking#263]
**Describe the bug**
I have a Bookings activity with booking options, where the start and end dates are known and set. I have set the 1st and 2nd notification reminder to go 3 and 1 days before the session. 

**Versions uses**
Moodle version: Moodle 4.0.6+ (Build: 20230126) 
Boooking version: 7.8.7 - 2023012700

**To Reproduce**
1. Create a Booking activity and add at least one booking option with a set start and end date.
2. On the Bookings activity settings, be sure to setup the the 'Participant notification before start' email 
3. Set a number for 'Number of days in advance of the event-start to notify participants' set to 2
4. Set a number for 'Second notification before start of event to notify participants.' set to 1
5. Make a test booking and wait for reminder emails. 

**Expected behavior**
Emails I think would be sent on the time the booking option was set, but I'm not sure if this is a cron job or a scheduled task?

**Additional context**
I did have this working initially, and not sure if moodle updates affected this. Does each option need a 'manager' to send emails?
How can I trouble shoot / test this better? Are there any sent logs? Or maybe managers could get a notice that reminders were sent?

**Comment by bernhard-wunderbyte** [comment]
Can you please try again with Booking 7.8.7.01 - there this bug should be already fixed. You can download it here: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/tags/v7.8.7.01.zip

To test it: Make the according settings and then go to SITEADMIN > Server > Scheduled tasks => There you'll find the task "Booking: Send reminder mails (\mod_booking\task\send_reminder_mails)". Click on the little "Run now" link in the "Last run" column to execute the task.

I'll close this ticket for now. If the problem should - unexpectedly - persist with 7.8.7.01 please let us know - in this case I will reopen it.
