### ISSUE TITLE
Problem log

### ISSUE THREAD

**Issue by Sandrokkan** [Wunderbyte-GmbH/moodle-mod_booking#265]
Hello, when I look at the daily user logs I get this error message.
Could I get some help on how to fix it?
Thank you
Exception - Return value of mod_booking\event\message_sent::transform_msgparam() must be of the type string, none returned

Moodle 4.1.1
Theme Moove
Booking version 7.8.7.01
2023012701

**Comment by bernhard-wunderbyte** [comment]
I think we'll need some additional information here. Do you know which type of message it was trying to send? (e.g. Teacher reminder, session reminder, status change, change notification...)

**Comment by Sandrokkan** [comment]
All booked users have been selected and the message sending the link to the survey has been sent
![Immagine 2023-03-23 114036](https://user-images.githubusercontent.com/109354224/227178880-9ba9ceae-b92f-49ee-a094-b6ce55fcd391.png)

**Comment by bernhard-wunderbyte** [comment]
I fixed this in Booking 7.8.7.02: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/tags/v7.8.7.02.zip

**Comment by Sandrokkan** [comment]
Good job!
Thank you
How can I purchase a PRO version?

**Comment by bernhard-wunderbyte** [comment]
To purchase a license, please send an e-mail to elianne.schewe [_at_] wunderbyte [_dot_] at - she'll send you an offer.
