### ISSUE TITLE
Status "users with shortterm reservations" when booking

### ISSUE THREAD

**Issue by monsieurmonsieur** [Wunderbyte-GmbH/moodle-mod_booking#267]
Hello, 

I'm sorry I'm not sure this is a bug but there is a feature I don't understand : Some users have the ability to be added to a booking option from a third party page in our moodle. With booking 7, people booked from this page now appear in the session not as registered users in the session, but as "users with shortterm reservations".

How can we manage that status ? What is the purpose of the short term reservation ? When placed in the option with that status, users do not receive the confirmation email and we can't set their presence status which is problematic.

Moodle version: 4.0.7
Boooking version: 7.8.7 (2023012700)

Thanks a lot for your answer,
Best Regard.

**Comment by dasistwas** [comment]
I think we changed the status field in the table and added more different status there.

**Comment by monsieurmonsieur** [comment]
Thank you @dasistwas for your answer, is it possible to know in which table and column to look for so I can identify these statuses ?

Thanks again

**Comment by georgmaisser** [comment]
Hi, shortterm reservations were introduced to support local_shopping_cart.

You said that you you allow booking from "a third party page", what does this means?

We used the existing waiting list field for the status as follows:

Look in lib.php:
// Define booking status parameters.
define('STATUSPARAM_BOOKED', 0);
define('STATUSPARAM_WAITINGLIST', 1);
define('STATUSPARAM_RESERVED', 2);
define('STATUSPARAM_NOTIFYMELIST', 3); // Get message when place is open.
define('STATUSPARAM_NOTBOOKED', 4);
define('STATUSPARAM_DELETED', 5);
