### ISSUE TITLE
Images added in the 'Booking text' section are not displayed.

### ISSUE THREAD

**Issue by guillermorojas** [Wunderbyte-GmbH/moodle-mod_booking#269]
In a Booking reservation module, in the 'Booking text' field, we add images. The images are displayed during the editing time, but when the editing is finished the image is not loaded. 

Moodle version: 3.9.19+ (20230126)
Boooking version: v7.0.22.18 (2021112918)

1. Go to an existing formation
2. Turn on the edit mode.
3. Add an activity or resource : Booking
4. Fill in the field "Booking name".
5. In the "Boogkin Text" field use the ATTO editor and click on the insert an image button.
6. Upload an image 
7. Click on the "Save and display" button.
The image does not display.

Expected behavior:
The  image shlould be loaded on the page.

Screenshots
Error:
https://drive.google.com/file/d/1yHIT8FXqTgB8wMb2_3r-LduKNmrxJb9k/view?usp=share_link

When we inspect the image we see this src value. 
img` src="**@@PLUGINFILE@@**/desk1-guillermorojas.jpg" alt="" width="130" height="173" class="img-responsive atto_image_button_text-bottom" id="yui_3_17_2_1_1683310431289_329"

**Comment by georgmaisser** [comment]
Hi, sorry, we we won't support Moodle 3.9 anymore. If you absolutely need a fix, you can contact us for a quotation.
