### ISSUE TITLE
Testing: GitHub Mustache lint issues (signin_downloadform)

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#271]
**Describe the bug**
Hardcoded attribute `style="display: none;"`  lead to permanent GitHub Mustache lint issues
`HTML Validation error, line 20: The value of the “for” attribute of the “label” element must be the ID of a non-hidden form control.`

**Versions uses**
Moodle version: all
Boooking version: since 2019091100

**To Reproduce**
1. GitHub Action must be executed OR browser's development console should be used

**Screenshots**
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/0a0a3497-e444-4e2d-a0ad-66471edd4643)

**Additional context**
I can suggest to setup attribute `style="display: none;"`  at runtime - not as static

**Comment by dasistwas** [comment]
Maybe we can modify the class:

class="card hidden" (Moodle style)
or
class="card invisible" (Boostrap)

**Comment by semteacher** [comment]
class="card hidden" (Moodle style) looks OK  as for me

**Comment by semteacher** [comment]
Solved [there](https://github.com/semteacher/moodle-mod_booking/commit/1779cb518d71353bac0da60d56403f7c6e196d67)
