### ISSUE TITLE
Testing: GitHub Mustache lint issues (bookingoption_dates_custom_list_items) 

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#274]
**Describe the bug**
The `<li>` tag in the child template leads to the following GitHub Mustache lint issue: 
`HTML Validation error, line 2: Element “li” not allowed as child of element “body” in this context.`
Tag `<li>` cannot be simply moved to parent template because has ben involved in the interactive  adding of custom dates in the option edit form via `initmodaloptiondateform()` method in the `dynamicoptiondateform.js`

**Versions uses**
Moodle version: all
Boooking version:  since 2019091100

**To Reproduce**
1. GitHub Action must be executed OR browser's development console should be used

**Screenshots**
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/b3f8529d-631d-434b-8c34-88be24312c57)
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/12dc7cfb-fb36-411e-8847-06c711e425ae)

**Additional context**
To solve - hardcode `<li>` in JS? Should work but not the best way...

**Comment by dasistwas** [comment]
is this fixed?
