### ISSUE TITLE
Rating bug (references $baid wrongfully)

### ISSUE THREAD

**Issue by rogiervandongen** [Wunderbyte-GmbH/moodle-mod_booking#279]
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/blob/687076c4556ce4893c71aa9edf6b37744c3d82fe/report.php#L412

When using the rating option from the report, this line causes a fatal error.
The problem seems to be in the $allusers = $bookingoption->get_all_users(); call; which does _not_ return the structure as implied in foreach ($allusers as $baid => $user).

In fact; the output immediately shows the issue:
Array
(
    [3] => stdClass Object
        (
            [baid] => 4
            [id] => 3
            [userid] => 3
            [waitinglist] => 0
            [timecreated] => 1688632393
            [optionid] => 6
        )

)

The fix is rather simple: refer to $user->baid in the foreach loop; remove or change the "index/key" reference in the foreach declaration, i.e.:

`
foreach ($allusers as $user) {
    if (in_array($user->userid, $allselectedusers) && $user->userid != $USER->id) {
        $rating = new stdClass();
        $bookedusers[$user->userid] = $user->baid;
        $bookinganswerid = "rating" . $bookedusers[$user->userid];

        $rating->rateduserid = $user->userid;
        $rating->itemid = $user->baid;
        $rating->rating = $_POST[$bookinganswerid];
        $ratings[$user->baid] = $rating;
        // Params valid for all ratings.
        $params = new stdClass();
        $params->contextid = $context->id;
        $params->scaleid = $scaleid;
        $params->returnurl = $returnurl;
    }
}
`

While this issue is being solved; you may just as well call clean_param on $_POST[$bookinganswerid]; it's a potential security issue and prone to injection.

**Comment by dasistwas** [comment]
report.php is quite old code. Should be redone entirely.

**Comment by dasistwas** [comment]
This mentioned function is not anymore done in the booking_option class but in the booking answers. So we have to get the users from there....

**Comment by bernhard-wunderbyte** [comment]
The rating bug in report.php was already fixed in Booking 8 with the following commit: 3560b4dd8054dd5d4655682b5e08a9289a72d7b3

If you want to try Booking 8, you'll additionally need Wunderbyte Table. You can find the plugins here:

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.0.29
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/releases/tag/v1.6.9

**Comment by bernhard-wunderbyte** [comment]
Already fixed.
