### ISSUE TITLE
Optiondate teacher form: fatal exception.

### ISSUE THREAD

**Issue by rogiervandongen** [Wunderbyte-GmbH/moodle-mod_booking#281]
Version: 2023012702 / Release: 7.8.7.02

When opening the teacher report and I try to edit the teachers, the dynamic form crashes with a fatal exception.

The problem is in the hidden field for the teachers that is defined with PARAM_RAW.
However, the list of teachers is already "explode()"d, so when setting the default value, an array of values is tried.

See:
/classes/form/editteachersforoptiondate_form.php line 153

If I'm correct, the line should read: $mform->addElement('hidden', 'teachers', $this->_ajaxformdata['teachers']);

or something to that extent

**Comment by dasistwas** [comment]
Which Moodle version do you use?

**Comment by rogiervandongen** [comment]
Ah sorry for leaving that out.
Moodle version is 4.1 Moodle 4.1+ (Build: 20221216), driven by PHP 8.0 FPM

If my memory serves me correct, the issue is mostly caused by PHP getting ever more strict.

**Comment by dasistwas** [comment]
You should use version 8 then together with wunderbyte table. Install it from github. booking depends on https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table but Moole HQ did still not do the plugin verification and we are waiting that the plugin is going to be released on moodle.org. Without that we can not publish booking version 8 on moodle.org because people will wonder how to get and install the depency.

**Comment by dasistwas** [comment]
There you find the releases: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tags

**Comment by dasistwas** [comment]
Wunderbyte Table releases: https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/tags

**Comment by rogiervandongen** [comment]
@dasistwas I've updated the code to use the latest version of mod_booking  and the table.
Let me keep silent about the UX changes; I'm not convinced some of those are benificiary or aiding to simplicity of use or correct UX. On the other hand, I've got the exact same issue with Moodle itself.

Anyway,
The issue is still there:
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/10880921/186b9336-9761-49af-a1db-cf1d4ce0f949)

The problem (and solution) is here:
`    public function definition() {
        global $DB;

        $mform = $this->_form;

        $cmid = $this->_ajaxformdata['cmid'];
        $optionid = $this->_ajaxformdata['optionid'];
        $optiondateid = $this->_ajaxformdata['optiondateid'];
        $teachers = explode(',', $this->_ajaxformdata['teachers']);

        $mform->addElement('hidden', 'cmid', $cmid);
        $mform->setType('cmid', PARAM_INT);

        $mform->addElement('hidden', 'optionid', $optionid);
        $mform->setType('optionid', PARAM_INT);

        $mform->addElement('hidden', 'optiondateid', $optiondateid);
        $mform->setType('optiondateid', PARAM_INT);

        //$mform->addElement('hidden', 'teachers', $teachers); // This line causes the fatal. It's caused by the fact you're trying to set an array of values onto the hidden field.
        $mform->addElement('hidden', 'teachers', $this->_ajaxformdata['teachers']); // This line seems to do the job, but I'm not sure it's meant to have a comma separated value.
        $mform->setType('teachers', PARAM_RAW);

`
Cheers

**Comment by dasistwas** [comment]
Help on UX is always appreciated. Moodle does not make it easy to have a good UX. But if you have ideas for nice templates, that would be great.

**Comment by dasistwas** [comment]
... and report.php and optiondates is really old legacy code. Going to improve that in the next couple of months.

**Comment by rogiervandongen** [comment]
Thanks for the updates and feedback.
report and optiondates is somewhat critical to the clients needs (please mind I'm also still rather new to this module) so I had to fix the code so it'd work.

Regarding UX: I'll keep track of the ideas opted by our client, as I'm a developer myself and the standard is that developers are by far not the best UX-ers in the world (although a few big projects where "extreme simplicity" was the mandate I'm now thinking about UX a little more than before).
I agree Moodle doesn't make it easy to have a good UX and their change management isn't always ..... let's say community friendly, especially when the whole interface and placement of any components changes heavily. Then again their coding standards are truly questionable as well (PSR standards, anyone?)

What would come to mind regarding UX in the sense of "ease of use", and I'm just thinking out loud, I could imagine there could be a wish for much simpler forms.
Thinking of a very old project, I've implemented some sort of dropdown that allowed for various modes of "expert settings" (and ultimately this lead to just a definition with a name, the configuration was made up of a huge set of disabledIf/hideIf settings).
So basically, a dropdown with some indicative name where the selected value/option would hide a number of fields.
The first remark when presenting the booking module to the client was "Oh dear! that's a lot of settings".

I can imagine this not really being feasible, but I'm happy to think along if this would or could be added to the "nice to have's".

One other feature that would make the life of our client happier would be to have an action: "add new booking option from template", where only the utmost necessities would need configuration. (Yes: I realize a booking option can be pre-filled from a template from within the form, but this is one of the questions I have already been asked. Even to this day a lot of our clients have endless knowledge on the organisation and processes, but are really not that well with computers. Of course this automatically means that they're instantly "scared off" when a page shows a lot of information, let alone when it's a form page).

Alas,
As said, I'll keep track of any relevant requirements, change requests or ideas for better/easier use of features, possible quick wins etc etc and will likely add them here in time.
As soon as I've had the time to dive much deeper into the booking module code I might even issue some PR's here but right now it's a little too early for that.

Cheers

**Comment by dasistwas** [comment]
That are some great ideas and I think we already did at least one of them: We have a mode that simplifies the creation of booking options by hiding a predefined set of settings. You will find that there:
mod/booking/optionformconfig.php

Concerning the option from template thing: That's really a subtle difference in usage. But providing a button with that functionality is not that easy. So in matter of effort implementing the templating feature and still having some kind of simple UI, that was the way to go. But indeed it could be implemented in a different way.

**Comment by bernhard-wunderbyte** [comment]
Fixed in Booking 8 with commit 34775c816401d7fd4527859c0dbec06ebff2a1dd.
