### ISSUE TITLE
Fatal exceptions when updating a booking

### ISSUE THREAD

**Issue by rogiervandongen** [Wunderbyte-GmbH/moodle-mod_booking#283]
It seems like this may be a bit of a trivial case, but when certain fields are left empty, updating or creating a booking crashes.
Much like a bug already issued, this is related to arrays.

It affects _all_ form fields that handle array based values, such as the report fields (just an example).

From lib.php, function booking_update_instance():

`
if (isset($booking->reportfields) && is_array($booking->reportfields) && count($booking->reportfields) > 0) {
    $booking->reportfields = implode(',', $booking->reportfields);
}
`

The code updates the $booking instance provided, so it basically assumes the provided $booking paramater is clean. However, it's form data. This isn't the biggest problem foor Moodle when you pass the object directly to an insert_record/update_record call because Moodle will clear all invalid fields, _but_... you now have an issue with the above code because _one_ case if falling through: when the array is empty, it does _not_ get modified to be either an empty string or NULL.
Instead, the (unmodified) array is provided along to the insert_record/update_record call and crashes the process with the ever familiar message a string is expected but an array is provided.

Solution: 
All cases where we can expecvt an array of values should handle empty arrays, as shown below:
`
    if (isset($booking->reportfields) && is_array($booking->reportfields)) {
        if (count($booking->reportfields) > 0) {
            $booking->reportfields = implode(',', $booking->reportfields);
        } else {
            $booking->reportfields = null; // Could also be empty string, but the field is defined nullable in the DB.
        }
    }
`

By the way:
the check seems a little surplus: when you can be 100% sure the field, when present, can _only_ be an array, the code can be changed to:
`
$booking->reportfields = (empty($booking->reportfields) ? null : implode(',', $booking->reportfields));
`
This is due to the fact that PHP's "empty()" call also checks if the field is set at all and not null.

@dasistwas if wanted, I can synchronize my work/fixes somewhere next week or the week after (too hectic at the moment, I'll start off soon with forking the repository).

**Comment by georgmaisser** [comment]
Sorry that we didn't answer on this, but I guess it's long fixed.
