### ISSUE TITLE
Missing String in /en/booking.php 

### ISSUE THREAD

**Issue by katcee** [Wunderbyte-GmbH/moodle-mod_booking#284]
When viewing the notification settings at //moodlesite/admin/message.php I see the following error message: 

Invalid get_string() identifier: 'messageprovider:sendmessages' or component 'mod_booking'. Perhaps you are missing $string['messageprovider:sendmessages'] = ''; in mod/booking/lang/en/booking.php?
line 356 of /lib/classes/string_manager_standard.php: call to debugging()
line 7409 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 136 of /message/renderer.php: call to get_string()
line 57 of /message/renderer.php: call to core_message_renderer->manage_defaultmessageoutputs()
line 132 of /admin/message.php: call to core_message_renderer->manage_messageoutput_settings()

and the affected notification setting shows: [[messageprovider:sendmessages]]

I would fix this myself in the local plugin but I can't find references to this anywhere in the Booking code so I do not know where to either a) stop it calling the string or b) Add the string to en/booking.php with the correct wording (as I have no idea what is meant to be here).

**Versions uses**
Moodle version: 4.1
Boooking version: 7.8.7.02

**To Reproduce**
1. Go to //moodlesite/admin/message.php (with developer debugging turned on)
2. See error

**Expected behavior**
Advice about what the notification setting relates to would replace [[messageprovider:sendmessages]] i.e Sends message when cancelled.

**Comment by georgmaisser** [comment]
Thank you @katcee  for reporting, it's already fixed and will be part of the next release.

**Comment by bernhard-wunderbyte** [comment]
@katcee This was fixed in Booking 8 only - which we will hopefully release soon.

In the meantime you can get it here (please note that you need Wunderbyte Table for it to work):

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.0.29
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/releases/tag/v1.6.9
