### ISSUE TITLE
Anleitung für booking-plugin / Instructions for booking plugin 

### ISSUE THREAD

**Issue by fmj1981** [Wunderbyte-GmbH/moodle-mod_booking#285]
It would be nice if there would be a description of the individual attributes of the booking plugin (moodle). For example, it is not clear what the difference between "ms1starttime" and "starttime" is. 
Thank you
Markus Dutzi

**Comment by dasistwas** [comment]
The first one is an option date: A session within the booking option. The second the overall starttime of the booking option.

**Comment by fmj1981** [comment]
Das heißt, wenn ich eine Buchungsoption zu zwei verschiedenen Terminen anbieten möchte, sollte ich ms1starttime bzw. ms2starttime nutzen.
Korrekt?
Kann der Nutzer bei der Buchung zwischen den unterschiedlichen Terminen wählen?

Zwei weitere Fragen habe ich noch:
Was ist der Unterschied zwischen "limitanswers" und 
"maxanswers"?
Gibt es eine Möglichkeit die Anzahl der Buchungen eines Users zu begrenzen? Macht dies etwa "limitanswers"?
Sorry wegen der vielen Fragen, bin Moodle-Booking-Newby.

----------------------------------------------------------------------------------------
This means that if I want to offer a booking option for two different dates, I should use ms1starttime or ms2 starttime. Correct?
Can the user choose between the different dates when booking?

I have two further questions:
What is the difference between "limitanswers" and 
"maxanswers"?
Is there a way to limit the number of bookings of a user? Does this about "limitanswers"? 
Sorry because of the many questions, i'm a Moodle Booking-Newby.

**Comment by bernhard-wunderbyte** [comment]
Das heißt, wenn ich eine Buchungsoption zu zwei verschiedenen Terminen anbieten möchte, sollte ich ms1starttime bzw. ms2starttime nutzen.
Korrekt? => **Nein, nicht ganz. Optiondates (in Booking auch "Sessions" genannt) verwendet man dann, wenn z.B. ein Kurs mehrere Termine hat. Diese können aber nur gemeinsam und nicht einzeln gebucht werden.**

Kann der Nutzer bei der Buchung zwischen den unterschiedlichen Terminen wählen? => **Nein, in diesem Fall müssen Buchungsoptionen einzeln erstellt werden, die jeweils eigene Start- und Endzeiten haben. In Booking 8 gibt es aber ein neues Feature, mit dem aus Optiondates (Sessions) neue Buchungsoptionen erstellt werden können.**

Was ist der Unterschied zwischen "limitanswers" und "maxanswers"? => **"maxanswers" ist die maximale TN-Anzahl, "limitanswers" der Wert der Checkbox "Teilnehmeranzahl beschränken" (0 => unlimitierte Buchungen, 1 => Wert aus maxanswers).**

Gibt es eine Möglichkeit die Anzahl der Buchungen eines Users zu begrenzen? => **Ich glaube, derzeit nicht.**

**Comment by dasistwas** [comment]
@bernhard-wunderbyte sorry, but this is not for support. If you want to have support please contact info@wunderbyte.at
