### ISSUE TITLE
Delete booking when user is deleted from Moodle

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#29]
When a user is deleted in moodle, the user should be deleted from the booking. Right now deleted users are still appearing in the booked users list. But are not counted as booked users in the booking overview.

**Comment by atlet** [comment]
Fixed - in my git repository - branch develop.

**Comment by dasistwas** [comment]
Hi Andraz,

usually you add an observer there: https://github.com/dasistwas/moodle-mod_booking/blob/master/classes/observer.php and check if a user was deleted in Moodle. I do not see that in the code.

Compare for correct implementation:

https://github.com/dasistwas/moodle-mod_newsletter/blob/master/classes/observer.php

```

    /**
     * Observer for the user_deleted event
     * deletes all newsletter subscriptions of the user
     *
     * @param \core\event\user_deleted $event           
     */
    public static function user_deleted(\core\event\user_deleted $event) {
        global $DB;

        $params = array (
                'userid' => $event->relateduserid 
        );
        $DB->delete_records_select ( 'newsletter_subscriptions', 'userid = :userid', $params );
    }
```

Kind regards,
David

**Comment by atlet** [comment]
Fixed - in my git.

**Comment by dasistwas** [comment]
Perfect. Thank you!
