### ISSUE TITLE
option overview displays table from different context after "one" action.

### ISSUE THREAD

**Issue by rogiervandongen** [Wunderbyte-GmbH/moodle-mod_booking#294]
**Describe the bug**
Major problem when using sorting or downloading of booking options.
It seems that the first table in a booking module you've visited is kept "somewhere" for some reason.

It shows itself as soon as you visit a second course with a booking module, go to the booking option overview and decide to either sort or download the table. Both the download as well as the replacement after the sort is applied holds the table from the OTHER course.

**Versions uses**
Moodle version: 4.1+
Boooking version: 8.0.20

**To Reproduce**
1. Create a course with a booking module with 20 options. We'll call this course A.
2. Create a course with a booking module and 20 options. We'll call this course B.
3. Go to course A's option overview and navigate between the paged output, or hit the sort button.
4. Go to course B's option overview. Verify that the INITIAL list is alright.
5. Try to download or hit "A->Z" zort button. Verify the actual output is now that of course A. 

**Expected behavior**
Obviously, we should see the table that actually belongs to the scope.

**Screenshots**
I've only debugged so far as to see what download.php generates.
I'm printing the $_REQUEST, the encodedtable param and a _part_ of the resulting $table object.
It's very obvious both tables are actually the same object, whereas the request parameters are clearly different.

---
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/10880921/e67be722-9243-4016-bd19-4e1a9ccb2dbd)
---
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/10880921/ee17c98b-29c0-486b-b029-df41583e657d)

Extra info:
Nothing changes at all when clearing the full Moodle cache. I've tried in many different stages, the reproduction is structurally the same: the instance of the wunderbute table does NOT change, no matter the encodedtable param.

Needless to say, this is a _critical_ issue that needs resolving ASAP (system is in production)

**Comment by rogiervandongen** [comment]
After a bit of digging I've come to the conclusion that the cached table is far from unique.
The wunderbuyte_wbtable has $uniqueid as it's first argument which is used to cache the table.

The uniqueid is ONLY unique in a generic scope, as can be determined from the ones used in /mod/booking/classes/output/view.php

Random pick from the original code in the view: "new bookingoptions_wbtable('visibleoptionstable', $booking);"
if 'visibleoptionstable' is to be made unique, please make sure it's unique in the contextual scope. This keyword identifier is only unique in global scope.

I've seem to have resolved the issue by suffixing ALL wbtable's initialized with the CMID (seemed the logical choice since the context is CONTEXT_MODULE and the view is dependent on cmid; hence the module context).

It seems to have worked for ALL wbtable instances in the view by suffixing the cmid as shown below:

new bookingoptions_wbtable('visibleoptionstable' . $cmid, $booking);

I'm _not_ sure if this is the right way to fix this, hence the lack of a PR for this. I'm still not familiar enough with the ins and outs of the booking module yet due to it's many loosely coupled dependencies and thus not familiar with possibly breaking anything somewhere else.

**Comment by bernhard-wunderbyte** [comment]
Fixed in Booking 8.0.33 with the following commits:
df23cf9b5f8d2e17e73452ff9b6c4bf5fe4424d7, 6391d184b4fbd08191eb010bb3b819f070081ab3 and f6e1e68267bd5d425b80402e8e0e4e91997432bf
