### ISSUE TITLE
Default exception handler: Error reading from database

### ISSUE THREAD

**Issue by stevenlovidge** [Wunderbyte-GmbH/moodle-mod_booking#296]
**Describe the bug**

[Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Column 'mdl_booking_options.bookingid' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.

Possible affecting all 'group by' statements. I have seen this before when using MS SQL which requires a full group by statement. For example:

MYSQL
'GROUP BY  bo.id '

MS SQL
'GROUP BY bo.id, bo.bookingid, bo.text, bo.maxanswers, bo.maxoverbooking, bo.bookingclosingtime, bo.courseid, bo.coursestarttime, bo.courseendtime, bo.enrolmentstatus, bo.description, bo.descriptionformat, bo.limitanswers, bo.timemodified, bo.addtocalendar, bo.calendarid, bo.pollurl, bo.groupid, bo.sent, bo.location, bo.institution, bo.address, bo.pollurlteachers, bo.howmanyusers, bo.pollsend, bo.removeafterminutes, bo.notificationtext, bo.notificationtextformat, bo.disablebookingusers, bo.sent2, bo.beforebookedtext, bo.beforecompletedtext, bo.aftercompletedtext, bo.shorturl, bo.duration, bo.sentteachers, bo.parentid, bo.semesterid, bo.dayofweektime, bo.invisible, bo.annotation, bo.identifier, bo.titleprefix, bo.priceformulaadd, bo.priceformulamultiply, bo.dayofweek, bo.priceformulaoff, bo.bookingopeningtime, bo.availability, bo.minanswers, bo.status'

I have tested the query using MS SSRS and returns expected results. The query used is
'SELECT id, bookingid, text, maxanswers, maxoverbooking, bookingclosingtime, courseid, coursestarttime, courseendtime, enrolmentstatus, description, descriptionformat, limitanswers, timemodified, addtocalendar, calendarid, pollurl, groupid, sent, location, institution, address, 
             pollurlteachers, howmanyusers, pollsend, removeafterminutes, notificationtext, notificationtextformat, disablebookingusers, sent2, beforebookedtext, beforecompletedtext, aftercompletedtext, shorturl, duration, sentteachers, parentid, semesterid, dayofweektime, invisible, 
             annotation, identifier, titleprefix, priceformulaadd, priceformulamultiply, dayofweek, priceformulaoff, bookingopeningtime, availability, minanswers, status, teacherobjects, filename
FROM   (SELECT DISTINCT 
                           bo.id, bo.bookingid, bo.text, bo.maxanswers, bo.maxoverbooking, bo.bookingclosingtime, bo.courseid, bo.coursestarttime, bo.courseendtime, bo.enrolmentstatus, bo.description, bo.descriptionformat, bo.limitanswers, bo.timemodified, bo.addtocalendar, bo.calendarid, 
                           bo.pollurl, bo.groupid, bo.sent, bo.location, bo.institution, bo.address, bo.pollurlteachers, bo.howmanyusers, bo.pollsend, bo.removeafterminutes, bo.notificationtext, bo.notificationtextformat, bo.disablebookingusers, bo.sent2, bo.beforebookedtext, bo.beforecompletedtext, 
                           bo.aftercompletedtext, bo.shorturl, bo.duration, bo.sentteachers, bo.parentid, bo.semesterid, bo.dayofweektime, bo.invisible, bo.annotation, bo.identifier, bo.titleprefix, bo.priceformulaadd, bo.priceformulamultiply, bo.dayofweek, bo.priceformulaoff, bo.bookingopeningtime, 
                           bo.availability, bo.minanswers, bo.status, STRING_AGG(bt1.teacherobject, ', ') AS teacherobjects, f.filename
             FROM    dbo.mdl_booking_options AS bo LEFT OUTER JOIN
                               (SELECT bt.optionid, CAST('{"id":' AS NVARCHAR(255)) + CAST('' AS NVARCHAR(255)) + CAST(u.id AS NVARCHAR(255)) + CAST('' AS NVARCHAR(255)) + CAST(', "firstname":"' AS NVARCHAR(255)) + CAST('' AS NVARCHAR(255)) + CAST(u.firstname AS NVARCHAR(255)) 
                                            + CAST('' AS NVARCHAR(255)) + CAST('", "lastname":"' AS NVARCHAR(255)) + CAST('' AS NVARCHAR(255)) + CAST(u.lastname AS NVARCHAR(255)) + CAST('' AS NVARCHAR(255)) + CAST('", "name":"' AS NVARCHAR(255)) + CAST('' AS NVARCHAR(255)) 
                                            + CAST(u.firstname AS NVARCHAR(255)) + CAST('' AS NVARCHAR(255)) + CAST(' ' AS NVARCHAR(255)) + CAST('' AS NVARCHAR(255)) + CAST(u.lastname AS NVARCHAR(255)) + CAST('' AS NVARCHAR(255)) + CAST('"}' AS NVARCHAR(255)) AS teacherobject
                               FROM    dbo.mdl_booking_teachers AS bt INNER JOIN
                                            dbo.mdl_user AS u ON bt.userid = u.id) AS bt1 ON bt1.optionid = bo.id LEFT OUTER JOIN
                           dbo.mdl_files AS f ON f.itemid = bo.id AND f.component = N'mod_booking' AND f.filearea = N'bookingoptionimage' AND f.mimetype LIKE 'image%'
             GROUP BY bo.id, bo.bookingid, f.filename, bo.text, bo.maxanswers, bo.maxoverbooking, bo.bookingclosingtime, bo.courseid, bo.coursestarttime, bo.courseendtime, bo.enrolmentstatus, bo.description, bo.descriptionformat, bo.limitanswers, bo.timemodified, bo.addtocalendar, 
                           bo.calendarid, bo.pollurl, bo.groupid, bo.sent, bo.location, bo.institution, bo.address, bo.pollurlteachers, bo.howmanyusers, bo.pollsend, bo.removeafterminutes, bo.notificationtext, bo.notificationtextformat, bo.disablebookingusers, bo.sent2, bo.beforebookedtext, 
                           bo.beforecompletedtext, bo.aftercompletedtext, bo.shorturl, bo.duration, bo.sentteachers, bo.parentid, bo.semesterid, bo.dayofweektime, bo.invisible, bo.annotation, bo.identifier, bo.titleprefix, bo.priceformulaadd, bo.priceformulamultiply, bo.dayofweek, bo.priceformulaoff, 
                           bo.bookingopeningtime, bo.availability, bo.minanswers, bo.status) AS s1
WHERE (1 = 1) AND (id = 11)'

**Versions uses**
Moodle version: 4.1.4
Booking version: 7.8.7.02

**To Reproduce**
1. Go to '/mod/booking/view.php?id=xxxxx'
2. Click on 'On page load'
4. See error below 

Default exception handler: Error reading from database Debug: SQLState: 42000<br>
Error Code: 8120<br>
Message: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Column 'mdl_booking_options.bookingid' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.<br>

SELECT *
                    FROM (
                        SELECT DISTINCT bo.* , STRING_AGG(bt1.teacherobject, ', ')  as teacherobjects ,  f.filename  FROM mdl_booking_options bo   LEFT JOIN
        (
            SELECT bt.optionid,   CAST('{"id":' AS NVARCHAR(255))  +  CAST('' AS NVARCHAR(255))  +  CAST(u.id AS NVARCHAR(255))  +  CAST('' AS NVARCHAR(255))  +  CAST(', "firstname":"' AS NVARCHAR(255))  +  CAST('' AS NVARCHAR(255))  +  CAST(u.firstname AS NVARCHAR(255))  +  CAST('' AS NVARCHAR(255))  +  CAST('", "lastname":"' AS NVARCHAR(255))  +  CAST('' AS NVARCHAR(255))  +  CAST(u.lastname AS NVARCHAR(255))  +  CAST('' AS NVARCHAR(255))  +  CAST('", "name":"' AS NVARCHAR(255))  +  CAST('' AS NVARCHAR(255))  +  CAST(u.firstname AS NVARCHAR(255))  +  CAST('' AS NVARCHAR(255))  +  CAST(' ' AS NVARCHAR(255))  +  CAST('' AS NVARCHAR(255))  +  CAST(u.lastname AS NVARCHAR(255))  +  CAST('' AS NVARCHAR(255))  +  CAST('"}' AS NVARCHAR(255))   as teacherobject
            FROM mdl_booking_teachers bt
            JOIN mdl_user u
            ON bt.userid = u.id
        ) bt1
        ON bt1.optionid = bo.id   LEFT JOIN mdl_files f
            ON f.itemid=bo.id and f.component=N'mod_booking'
            AND f.filearea=N'bookingoptionimage'
            AND f.mimetype LIKE 'image%' GROUP BY  bo.id   ,   f.filename 
                    ) s1
                    WHERE 1=1  AND   id = 11
[array (
  0 => 'mod_booking',
  1 => 'bookingoptionimage',
)]
Error code: dmlreadexception
* line 494 of \lib\dml\moodle_database.php: dml_read_exception thrown
* line 331 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
* line 438 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
* line 907 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
* line 983 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
* line 1679 of \lib\dml\moodle_database.php: call to sqlsrv_native_moodle_database->get_records_sql()
* line 285 of \mod\booking\classes\booking_option_settings.php: call to moodle_database->get_record_sql()
* line 254 of \mod\booking\classes\booking_option_settings.php: call to mod_booking\booking_option_settings->set_values()
* line 234 of \mod\booking\classes\singleton_service.php: call to mod_booking\booking_option_settings->__construct()
* line 155 of \mod\booking\classes\booking_option.php: call to mod_booking\singleton_service::get_instance_of_booking_option_settings()
* line 207 of \mod\booking\editoptions.php: call to mod_booking\booking_option->__construct()

**Expected behavior**

Page loads and shows bookings.

**Screenshots**
None

**Additional context**

**Comment by stevenlovidge** [comment]
Hi,
I'm wondering if you have an update for this issue?
Kind regards,
Steve

**Comment by dasistwas** [comment]
Could you upgrade to the latest version and check if the problem still exists @stevenlovidge ? 
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.0.55

**Comment by bernhard-wunderbyte** [comment]
@stevenlovidge Before you install Booking 8.0.55, you need to install Wunderbyte Table. You can get it here:
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/releases/tags

**Comment by stevenlovidge** [comment]
> Could you upgrade to the latest version and check if the problem still exists @stevenlovidge ? https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.0.55

Yes, of course. Thank you!

**Comment by stevenlovidge** [comment]
> @stevenlovidge Before you install Booking 8.0.55, you need to install Wunderbyte Table. You can get it here: https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/releases/tags

Yes, of course :)
Thanks!

**Comment by stevenlovidge** [comment]
Hi Guys 🙂
I'm please to inform you that the issue I raised is fixed in the latest release!
Thank you both for your help!

**Comment by stevenlovidge** [comment]
This issue is now complete.
