### ISSUE TITLE
Not using the standard email_to_user function

### ISSUE THREAD

**Issue by sebastianberm** [Wunderbyte-GmbH/moodle-mod_booking#297]
**Describe the bug**
Why is this module not using the default email_to_user function?
It should be possible to just use that function, without having to resort to manually doing everything, as this method is changing in Moodle 4.2 (please check master branch), this will have consequences.

So if it's possible to go back to the normal email_to_user function from /lib/moodlelib.php it would certainly make the transition easier.

**Versions uses**
Moodle version: 4.1
Boooking version: 8.0.20

**Comment by dasistwas** [comment]
Default does not support multiple attachments. Why is that a problem?

**Comment by dasistwas** [comment]
I tried to identify some changes but there isn't anything in the release notes. So we have to debug that.
https://moodledev.io/general/releases/4.2

**Comment by dasistwas** [comment]
@bernhard-wunderbyte email does not seem to work anymore in M4.2. Also mod_newsletter is affected and has the same problem.

**Comment by sebastianberm** [comment]
Basically, the send_email_to_user functionality was completely rewritten for Moodle 4.2, and apparently pulled out of integration again (https://tracker.moodle.org/browse/MDL-69724). So, it might be wise to add to that and/or work with that ticket as well.

At the moment it's affecting one of our systems that is using the default email_to_user function to log outbound mails. But it didn't seem to catch mod_booking based emails, so that's why it triggered me to add this ticket.

**Comment by sebastianberm** [comment]
Further note; the fork of the function **does not** honor the **nomailever** statement. (https://github.com/Wunderbyte-GmbH/moodle-mod_booking/blame/687076c4556ce4893c71aa9edf6b37744c3d82fe/classes/message_controller.php#L776)
Why in the name of .... would you not honor that?

It was good we found this in time, as this could have caused major issues in our implementation.

**Comment by dasistwas** [comment]
@bernhard-wunderbyte Could we fix the noemailever thing ASAP? That could cause serious problems.

**Comment by bernhard-wunderbyte** [comment]
Fixed in 35236566155dc24210c5f3b4bcd2cebc0e6ff3cd
