### ISSUE TITLE
Problem migrate from older version of moodle

### ISSUE THREAD

**Issue by MoodleFun77** [Wunderbyte-GmbH/moodle-mod_booking#301]
Good morning everyone, today I migrated from a moodle 3.7 to 4.1.5 .
The migration procedure is the classic one, backup old database, import and migrate to the new server with different url.
I also did a replace of the old url with the new one, the only thing left with the old link are the Booking plugin appointments.
THE strange thing is that if I open an old appointment I edit it and save it the link is saved to the new url, if I create a new one the same.(Everything works)
Where does the plugin read the old url ? if there is not the slightest sign of the old url in the database ?
Thanks a lot

**Comment by MoodleFun77** [comment]
Versione plugin 7.8.7.02 (2023012702)

**Comment by dasistwas** [comment]
Sorry, we can't you offer free support for migrating from one URL to another. You can contact us via mail if you want to contract us. You find the contact details at https://wunderbyte.at

**Comment by MoodleFun77** [comment]
Hi David is not a problem of migration i have migrate all plugin of moodle and all was ok with a new url.
The problem is that your plugin use URL ENCODE base64 for link in calendar.
When i migrate , the string e replace cant fount the old domain
Exist a procedure to encode all old url in new url?

Why you use the base64 in db insted of url in clear? 
https://externalnewsite.exmaple/mod/booking/bookingredirect.php?encodedurl=U2l0b0VzdGVybm92ZWNjaGlvLmNvbQ==

Thanks a lot

**Comment by MoodleFun77** [comment]
David the problem on button "go to the booking option" the url is oncoded of CALENDAR

/mod/booking/bookingredirect.php?encodedurl=

**Comment by dasistwas** [comment]
This is the reason:
 * This is a very simple script which allows us to pass a base64 encoded URL
 * as param and redirect to the decoded URL.
 * This was needed because it wasn't possible to stop the Moodle calendar exporter
 * from escaping "&" to "&amp;" HTML entitities which made it impossible
 * to open links within outlook events.

**Comment by MoodleFun77** [comment]
Thanks David, so your plugin is not possible to move to another server with different url? 
Have you a solution about this problem? 

David , after edit  old option of event and after save the url is encoded right.

**Comment by dasistwas** [comment]
You already have the solution



> David , after edit old option of event and after save the url is encoded right.

That would be the solution. Do you have many options to edit?

**Comment by dasistwas** [comment]
I created a bug report. But right now for us this is not high priority. https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/305

**Comment by MoodleFun77** [comment]
Yes David but i should edit and save ALL events of calendar , there are a lot, and all manualy.
Thanks a lot for your Time

**Comment by dasistwas** [comment]
What you could do is: Download the booking  options via CSV and then modify them so you can reimport them using the bulk import tool. That might you save some work, but it might require some testing.
Also I recommend to install the latest booking version:

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.0.30

But this depends on:
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/releases/tag/v1.6.9

So you have to install wunderbyte table first.

**Comment by MoodleFun77** [comment]
Thanks David this version is Stable for Moodle 4.1.5 or is unstable or developper?
Thanks

**Comment by dasistwas** [comment]
All releases are stable.
