### ISSUE TITLE
Multiple errors when export options table to any formats

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#302]
**Describe the bug**
1. Deprecation message on export of options list to CSV or json or HTML table:
<b>Deprecated</b>:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in <b>/var/www/html/mod/booking/classes/booking.php</b> on line <b>499</b>

2. "Division by zero" error when trying to download as PDF wit the follwing stack trace
```
line 90 of /dataformat/pdf/classes/writer.php: DivisionByZeroError thrown
line 2353 of /lib/tablelib.php: call to dataformat_pdf\writer->start_sheet()
line 1086 of /lib/tablelib.php: call to table_dataformat_export_format->output_headers()
line 778 of /lib/tablelib.php: call to flexible_table->start_output()
line 728 of /lib/tablelib.php: call to flexible_table->add_data()
line 629 of /local/wunderbyte_table/classes/wunderbyte_table.php: call to flexible_table->add_data_keyed()
line 430 of /local/wunderbyte_table/classes/wunderbyte_table.php: call to local_wunderbyte_table\wunderbyte_table->build_table()
line 71 of /mod/booking/download.php: call to local_wunderbyte_table\wunderbyte_table->printtable()
```
3. MS Exclel export produce errror "incorrect or corrupted file"
4. Unreadable OpenOffice ods file

**Versions uses**
Moodle version: 4.1
Boooking version: 8.0.30 but previous also affected

**To Reproduce**
1. Go to '/mod/booking/view.php?id=<id>'
2. Try to download options's table in any format

**Screenshots**
MS Exclel errror
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/202cdf04-81b0-45ea-8833-e1187d5b2800)

**Additional context**
Pribably caused by empty value in the 
`$this->settings->optionsdownloadfields`
in the following method:
```
    public function get_bookingoptions_fields(bool $download = false) {

        if ($download) {
            $fields = explode(',', $this->settings->optionsdownloadfields);
        } else {
            $fields = explode(',', $this->settings->optionsfields);
        }
```

**Comment by bernhard-wunderbyte** [comment]
Under booking instance settings you may need to re-configure the columns (header: "Configure fields and columns"):
"Booking options overview - Page" and "Booking options overview - Download".

When migrating from Booking 7 to Booking 8 these columns probably got lost.

I added the following bugfix: If there are no columns set at all, all columns will be used as fallback.
