### ISSUE TITLE
CSV Import: existing options cannot be updated

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#303]
**Describe the bug**
The following code 
```
if ($optionid === false) {
                    $optionid = booking_update_options($bookingoption, $this->booking->get_context(), UPDATE_OPTIONS_PARAM_IMPORT);
                }
```
in `process_data()` method of the `csv_import `class prevents any update of existing options because `$optionid === false` only for new options

**Versions uses**
Moodle version: 4.1.4
Boooking version: 8.0.30 but previous affected too

**Comment by bernhard-wunderbyte** [comment]
I did some tests now. Unfortunately, updating of booking options via CSV import does not really work the way it should right now. So, for now, I think, we'll keep it that way - knowing that updating does not do anything right now.

We'll need to re-write the CSV import class completely using functions that make it easy to change individual fields while not breaking anything else of existing booking options. Also there is a lot of stuff like (teachers, entities, custom fields etc.) that needs individual handling and is not stored directly in the booking option - so the new importer should take care of this as well.

For now, we'll only use it as an "importer" class (which creates NEW booking options) but we will not update existing booking options with it.

I already created the new issue #310 for the new importer.
