### ISSUE TITLE
CSV import of booking options: issue with location which is not in DB

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#304]
**Describe the bug**
If provided location (by ID or name) not found - `moodle_error `has been thrown. 
It caused by overlaping of of code, related to processing of location:
a) in the `booking_update_options() `(being executed 1st in the `process_data() ` method of the `csv_import ` class) 
```
// Save relation for each newly created optiondate if checkbox is active.
$isimport = $updateparam == UPDATE_OPTIONS_PARAM_IMPORT ? true : false; // For import we need to force this!
save_entity_relations_for_optiondates_of_option($optionvalues, $optionid, $isimport);
```
and the above function  ( `save_entity_relations_for_optiondates_of_option()` ) thrown  `moodle_error `if provided location (by ID or name) not found (special case for import!)
```
// If we have exactly one entiity, we create the entities entry.
            if (count($entities) === 1) {
                $entity = reset($entities);
                $optionvalues->local_entities_entityid = $entity->id;
            } else {
                throw new moodle_exception("More than one entity found for {$optionvalues->location}.");
            }
```
b) with almost the same code in the in the `process_data() ` method of the `csv_import ` class - just below calling of the `booking_update_options() ` menthod

**Versions uses**
Moodle version: 4.1.
Boooking version: 8.0.30 but previous have been affected too

**Additional context**
a) probably have to be solved in conjunction with [previous issue](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/303)
b) I proposed simple approach with elimination of `moodle_error ` - because it is possible to save booking option via UI without location being provided OR with location not available in given list of entities (this [commit](https://github.com/semteacher/moodle-mod_booking/commit/6dc0166666a3c2c2b41328347587ae9730938762) under [this branch](https://github.com/semteacher/moodle-mod_booking/tree/MOODLE_401_TESTING)). 
c) it migth be necessary to create test items (generator and classes) under local/entites plugin to provide necessary testing tools for other plugins

Testing file
[options_coma_new00.csv](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/files/12419858/options_coma_new00.csv)

**Comment by bernhard-wunderbyte** [comment]
See issue #310 - we'll need to re-write the CSV importer class in order to properly support updating. When importing NEW booking options the import works properly.
