### ISSUE TITLE
Default ordering of booking options is the wrong way around

### ISSUE THREAD

**Issue by sebastianberm** [Wunderbyte-GmbH/moodle-mod_booking#307]
**Is your feature request related to a problem? Please describe.**
Usecase:
As a learner, I want to book a booking option, my institution has multiple options. By default, this will mean I have to scroll down as the default ordering is from z to a based upon the starttime.

Admin side:

**Describe the solution you'd like**
The column for which the sort works is configurable already, but the default ordering is from z to a instead of a to z.
This should be configurable or work in a logical manor.

**Additional context**
* Currently version 8.0.20.
* There are instances with over 10 options available. At the start of each year, they're added for almost the entire year, so people can have freedom of choice.

**Comment by georgmaisser** [comment]
The setting for this is present in the latest version.

<img width="768" alt="Bildschirmfoto 2024-01-01 um 14 14 31" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/7524621/0f2bfaf8-b830-4e4f-a755-e3de3cf9c636">
