### ISSUE TITLE
Booking options show in wrong booking

### ISSUE THREAD

**Issue by jharej** [Wunderbyte-GmbH/moodle-mod_booking#308]
**Describe the bug**
We've discovered that when searching for a booking option within one booking, the search results display booking options from another unrelated booking. Our platform is used for booking seminars, where each booking represents an individual seminar and each booking option signifies a specific session of that seminar (e.g., at a particular location and time). While testing the new version, browsing through booking options functions correctly, but the search feature does not behave as expected.

**Versions uses**
Moodle version: $release  = '4.1.2+ (Build: 20230406)';
Boooking version: $plugin->release = '8.0.20';
wunderbyte table version: $plugin->release = '1.6.9'; $plugin->version = 2023081100;

**To Reproduce**
Click on booking number one.
Utilize the search function and observe that only the booking options from this specific booking are displayed – this is the correct behavior.
Return to the main course page and select a different booking, for instance, booking number two within the same course.
Employ the search function and input the name of a booking option from booking number one.
Observe that the search results include the list of booking options from booking number one, which is unexpected behavior.

**Expected behavior**
When using the search option within booking number two, the expected outcome is not to receive any results related to booking options from booking number one.

**Comment by dasistwas** [comment]
We are now at [v8.0.31](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.0.31)  Could you check if that is still a problem?

**Comment by atlet** [comment]
Ok, I upgraded to v8.0.31, but no I'm getting this error:

![2023-08-30_10-20](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1223162/347f0519-00fd-4e31-a84a-d7c6e3f1c5c9)

How to fix this issue?

**Comment by dasistwas** [comment]
Could you provide the steps to reproduce this error? Could you also purge the caches?

**Comment by atlet** [comment]
I cleared the cache and it's the same. I updated to v8.0.31 and this error pops out when I go to /mod/booking/view.php?id=XXXX address. I suspect naming of cache as we have č char in it.

**Comment by atlet** [comment]
So, the problem is with wunderbyte_table. If I add in file classes/wunderbyte_table.php in line 900 this 
`$key = str_replace(['č', 'ž', 'š', 'Č', 'Ž', 'Š'], ['c', 'z', 's', 'C', 'Z', 'S'], $key);`
it's working fine.

**Comment by atlet** [comment]
can you fix this please.

**Comment by dasistwas** [comment]
Where did you include the special characters in booking? In the booking option name? We would be happy if you give us some hints how we can reproduce the error on our systems.

**Comment by atlet** [comment]
In my institution.
![2023-08-30_14-34](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1223162/4c5eed39-43a9-4205-aef2-eaaf41c01761)

**Comment by dasistwas** [comment]
I tried to reproduce: On my machine it works. See the video

[Screencast from 2023-08-30 14-49-15.webm](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1620975/1f683cbc-678c-4273-a982-cce091fb7c62)

**Comment by dasistwas** [comment]
What is your PHP version and database used?

**Comment by atlet** [comment]
I'm using PostgreSQL and php is version 7.4.3

**Comment by bernhard-wunderbyte** [comment]
I fixed this with commit f6e1e68267bd5d425b80402e8e0e4e91997432bf. It's already part of Booking 8.0.33 - you can get it here: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tags
