### ISSUE TITLE
CSV import - Re-write importer class and support updating again.

### ISSUE THREAD

**Issue by bernhard-wunderbyte** [Wunderbyte-GmbH/moodle-mod_booking#310]
The way the CSV importer is currently written is very old legacy - also it currently does not support updating of any existing booking options (!).

We should re-write it in a more readable way - using functions that make it easy to update certain parts of booking options (like option dates, entity relations, teachers, custom fields...) while not destroying any existing data.

**Comment by Christoph5** [comment]
Today I noticed that my CSV Import worked without any error message but the bookingclosingtime was not updated. 
Here is an example:
"text","bookingclosingtime","coursestarttime","courseendtime","description","institution","maxanswers","maxoverbooking","limitanswers","location","addtocalendar"
"EN/DE - Selling Skills I, Q1 2024","01.04.2024 00:01:00","02.04.2024 00:01:00","03.04.2024 00:01:00","Las inscripciones se cerrarán 3 días antes para la organización.","Technical Training","20","0","8","MS Teams","1"
I changed to different startimes and endtimes for the booking options, but couldn´t find a way that accepted the booking closing time. Any idea why this behaviour changed? I am pretty sure this worked before we did out last update. Honestly not sure from what version we changed. Actual version is: v7.0.22.18

**Comment by bernhard-wunderbyte** [comment]
Booking 7.0.x is very old and we do not provide updates for this version anymore. Could you please upgrade to Booking 8? (You'll need at least Moodle 4.0). Also Booking 8 requires Wunderbyte Table. You can get both here:

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.0.46a
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/releases/tag/v1.8.0

If this is still a problem with Booking 8, we'll try to fix it, of course.

**Comment by georgmaisser** [comment]
New csv importer is now incorporated in a dev branch, soon to be part of main.
