### ISSUE TITLE
Show a warning when optiondate series are created for a semester in the past

### ISSUE THREAD

**Issue by bernhard-wunderbyte** [Wunderbyte-GmbH/moodle-mod_booking#311]
When using the CSV importer it might be possible that a semester is used for optiondate series creation that lies in the past. As this might be most possibly a user's error a **warning** should be shown so the user is aware that the import was done for a semester in the past.

This also applies to optiondate series within the editoption form - there a warning should also be shown if a semester lies in the past.

**Comment by georgmaisser** [comment]
I close this because it just seems too much. Users should check the date when they import sth.
