### ISSUE TITLE
Notification list

### ISSUE THREAD

**Issue by Sandrokkan** [Wunderbyte-GmbH/moodle-mod_booking#312]
If Use notification list is selected in the plugin settings and there are zero seats on the waiting list, the button to be notified when the seats become free does not appear
Moodel 4.1.1

Booking 7.8.7.02
2023012702
![Immagine 2023-08-30 121220](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/109354224/50bbea66-afd1-4463-9371-c64565c57788)

**Comment by dasistwas** [comment]
Please upgrade to version 8. You have to download it from github. Moodle did not yet release a plugin the new booking version needs. So we can't publish it on moodle.org.
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tags
You also need that plugin:
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/tags

**Comment by dasistwas** [comment]
I will close the issue for now, if the bug still exists in version 8, you can comment here.

**Comment by Sandrokkan** [comment]
Thank you. Is it possible to predict when the new version will be published?

**Comment by dasistwas** [comment]
We are waiting since May for approval. If you know somebody at Moodle HQ who can speed up the process, that would be great. Here is the issue that was created: https://tracker.moodle.org/browse/CONTRIB-9279

**Comment by Sandrokkan** [comment]
Thank you. Can this version of the plugin already be used in a production platform?

**Comment by dasistwas** [comment]
Yes. These are stable releases. Can be used under conditions of GPLv3
