### ISSUE TITLE
Custom labels do not show

### ISSUE THREAD

**Issue by jharej** [Wunderbyte-GmbH/moodle-mod_booking#315]
**Describe the bug**
If I enter a custom label for "Book now" button, it does not show.

**Versions uses**
Moodle version: 4.1
Boooking version: 8.0.33

**To Reproduce**
1. Go to booking settings and to section Custom labels [deprecated]
2. Enter custom label in "Name of button: Book now" e.g. Sign in for competition
3. Save and go back to main booking page. 
4. Text on the "Book now" should be "Sign in for competition"

**Context**
We use booking in two different ways: 1. to support the organization of teacher training, 2. to support the organization of exams. This is the reason for this section - to enable to use different labels on different buttons for different usage scenarios.

![deprecated-custom-labels](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/10975112/80210f44-430a-4bd1-9a2f-446bd182fa0f)

**Comment by georgmaisser** [comment]
Sorry to have lost that feature. We might include sth like that again in the future, but not around the corner... If you need features which are not currently part of booking, you can commission https://wunderbyte.at to implement them.

Thank you for your understanding.
