### ISSUE TITLE
Adding user to option

### ISSUE THREAD

**Issue by atlet** [Wunderbyte-GmbH/moodle-mod_booking#316]
**Describe the bug**
If I add user to option, then delete this user from option and add it again I get this error.
`Did you remember to make the first column something unique in your call to get_records? Duplicate value '59' found in column 'userid'.`

**Versions uses**
Moodle version: 4.1
Boooking version: 8.0.33

**To Reproduce**
1. Add user to booking option.
2. Delete user from this booking option.
3. Add user to this booking option.

**Solution**
To remove user record from this table when you delete the user.

**Comment by georgmaisser** [comment]
Tried to reproduce on the 
mod/booking/subscribeusers.php?id=968&optionid=8557&agree=0

Couldn't get an error. On which page you get this error?

We don't delete from booking answers anymore, but we set "waitinglist" column (which will be renamed to "bookingstatus", see the constants in lib.php) to 5. So the way to avoid is to just return waitinglist < 3 (including booked, waitinglist & reserved users, but not deleted.

**Comment by dasistwas** [comment]
@atlet should be fixed in most recent version. Please checkout this version and  confirm the fix.

**Comment by georgmaisser** [comment]
No feedback anymore, so closed

**Comment by atlet** [comment]
Yes it's working. tnx
