### ISSUE TITLE
404 Error. Probably code issue in module

### ISSUE THREAD

**Issue by ThaRooney** [Wunderbyte-GmbH/moodle-mod_booking#321]
A customer did report an issue.
As they will fill in an number at
https://leeromgeving.iokai.nl/mod/booking/report.php?id=5705&optionid=6871
And then click on "rate", they do get a 404 error page.

If we look further, we do see this;

2023/09/19 13:31:19 [error] 131492#131492: *1032428 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "rating178" in /home/iokai/web/leeromgeving.iokai.nl/public_html/mod/booking/report.php on line 402PHP message: Default exception handler: Kan gegevensrecord niet vinden in databanktabel booking_answers. Debug: SELECT * FROM {booking_answers} WHERE id = ? AND userid = ?
[array (
  0 => 178,
  1 => '178',
)]
Error code: invalidrecord
* line 1654 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
* line 1630 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 1972 of /mod/booking/lib.php: call to moodle_database->get_record()
* line 8064 of /lib/moodlelib.php: call to booking_rating_validate()
* line 8036 of /lib/moodlelib.php: call to component_callback()
* line 1007 of /rating/lib.php: call to plugin_callback()
* line 2061 of /mod/booking/lib.php: call to rating_manager->check_rating_is_valid()
* line 412 of /mod/booking/report.php: call to booking_rate()" while reading response header from upstream, client: 116.203.115.189, server: leeromgeving.iokai.nl, request: "POST /mod/booking/report.php?id=5705&optionid=6871 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.0-fpm-leeromgeving.iokai.nl.sock:", host: "leeromgeving.iokai.nl", referrer: "https://leeromgeving.iokai.nl/mod/booking/report.php?id=5705&optionid=6871"

It looks like there is a double 178 in it, maybe a typo.

To make sure i would like to let you check and see whats not correct or what does the issue caused.
![404](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/145471283/878ae697-7750-4797-8528-5a2bd6bc2d17)

**Comment by gemguardian** [comment]
@bernhard-wunderbyte to give some extra context to this issue and hopefully help you  (or other dev that are working on this) the issues to fix it. 

Currently it prevents us from grading students. 

We are using : M4.1, Laatste Booking activite release moodle.org 7.8.7.02 | 2023012702

The notification "402PHP message: Default exception handler: Kan gegevensrecord niet vinden in databanktabel booking_answers"  states that the record cannot be found in the database, though we do find the record in the database when we look it up 

![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16559999/5ad1a08b-1185-4869-bcc6-f5b4efdeb3c9)

**Comment by bernhard-wunderbyte** [comment]
This issue should already be fixed in Booking 8. Unfortunately, we could not yet publish it on Moodle.org as we need permission for the required plugin local_wunderbyte_table. If you know someone at Moodle HQ who could speedup this process, we would be more than happy.

In the meantime, you can get Wunderbyte Table and Booking 8 from here (please click on the newest Tag and download the ZIP from there):

https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/tags
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tags

Please note that you need to install wunderbyte table BEFORE booking.

I'll close this for now. If there are still issues with Booking 8 please let us know.

**Comment by gemguardian** [comment]
@bernhard-wunderbyte thank you for informing and the links. I will see what I can do :)

**Comment by gemguardian** [comment]
@bernhard-wunderbyte could you please update https://moodle.org/plugins/local_wunderbyte_table/versions to the latest release: https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/releases/tag/v1.8.2

I concuding my functional test, and then I can push for the code test by David and/or Dan, but it would be good to have the latest version.

**Comment by bernhard-wunderbyte** [comment]
David (@dasistwas ), can you do the update?

**Comment by dasistwas** [comment]
New version is on moodle.org @gemguardian @bernhard-wunderbyte

**Comment by gemguardian** [comment]
@dasistwas thank you. there is a huge backlog and they are doing what they can. My functional test helps a little bit, but I cannot check / verify codes. But if you know someone that could help with code reviewing plugins please contact David Mudrák or Dan Marsden.

**Comment by dasistwas** [comment]
Thank you @gemguardian . We are already in contact with a German Moodle partner. Their developers try now to become plugin guardians. I hope that will accelerate the process.

**Comment by gemguardian** [comment]
@dasistwas well I think we managed to get something going. Though I see some issues needs to be fixed. :)
