### ISSUE TITLE
group booking

### ISSUE THREAD

**Issue by Sandrokkan** [Wunderbyte-GmbH/moodle-mod_booking#322]
Good morning,
I created a group in the course, I assigned users to the group but when I register for other users and select the group the users are not registered
[Moodle][4.1.1 (Build: 20230116)]
Tjeme Movve
Booking: 7.8.7.02
2023012702

**Comment by Sandrokkan** [comment]
I found the problem. When you fill in the booking policy in the general settings, group booking does not work

**Comment by georgmaisser** [comment]
Hi, thanks for telling us. It's fixed in a develop branch but will be incorporated to main very soon.

The logic was clearly a bug, not a feature ;-)
