### ISSUE TITLE
Linting: add comma to last line of multiline arrays

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-mod_booking#323]

**Comment by georgmaisser** [comment]
We get listing errors because of that. Thank you!
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/actions/runs/6333366141/job/17201370930

**Comment by semteacher** [comment]
As per this GitHub's log fragment

```
FILE: /home/runner/work/moodle-mod_booking/moodle-mod_booking/moodle/mod/booking/optiondates_teachers_report.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------------------------------
 40 | ERROR   | [x] There should be a comma after the last array item in a multi-line array.
    |         |     (NormalizedArrays.Arrays.CommaAfterLast.MissingMultiLine)
 79 | WARNING | [x] Short array syntax must be used to define arrays (Generic.Arrays.DisallowLongArraySyntax.Found)
------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------------------------------------------------------------
```

As reported, PHPCBF should be able to fix both issues automatically. Hovewer, when I have tried it with default settings but it does not works.
Some search gives me possible resolution for "short array syntax":
https://stackoverflow.com/a/56646503/6734441
but I have not tested it yet. 
I assume that something similar should be available for "should be a coma..." but more search required.

UPD: further search gives infor that sniffs are not all documented but their names could be retreived fron standard files 
[https://github.com/squizlabs/PHP_CodeSniffer/issues/1774](https://github.com/squizlabs/PHP_CodeSniffer/issues/1774)
