### ISSUE TITLE
Several issues with PHP 8.1

### ISSUE THREAD

**Issue by abkoch** [Wunderbyte-GmbH/moodle-mod_booking#327]
**Describe the bug**
mod_booking does not run with PHP 8.1

**Versions uses**
Moodle version: 4.1.6
Boooking version: 7.8.7.02

**To Reproduce**
1. Creating a new option throws the following error because the old hash_key() is used.
```
* line 638 of /cache/classes/helper.php: coding_exception thrown
* line 1207 of /cache/classes/loaders.php: call to cache_helper::hash_key()
* line 504 of /cache/classes/loaders.php: call to cache->parse_key()
* line 1870 of /cache/classes/loaders.php: call to cache->get_implementation()
* line 405 of /cache/classes/loaders.php: call to cache_application->get_implementation()
* line 237 of /mod/booking/classes/booking_option_settings.php: call to cache->get()
* line 234 of /mod/booking/classes/singleton_service.php: call to mod_booking\booking_option_settings->__construct()
* line 76 of /mod/booking/classes/dates_handler.php: call to mod_booking\singleton_service::get_instance_of_booking_option_settings()
* line 76 of /mod/booking/classes/form/dynamicoptiondateform.php: call to mod_booking\dates_handler->add_optiondates_for_semesters_to_mform()
* line 214 of /lib/formslib.php: call to mod_booking\form\dynamicoptiondateform->definition()
* line 73 of /lib/form/classes/dynamic_form.php: call to moodleform->__construct()
* line 73 of /lib/form/classes/external/dynamic_form.php: call to core_form\dynamic_form->__construct()
* line 262 of /lib/externallib.php: call to core_form\external\dynamic_form::execute()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()
```

2. Using other plugins like "mod_checklist" throws warnings because deprecated functions are used:
`Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/VirtHosts/c94fe718-183c-4bec-9a8c-5e78a40dcf0e/data/htdoc/moodle/mod/booking/classes/booking_tags.php on line 79`

**Expected behavior**
mod_booking should run with PHP 8.1

**Additional context**
Please see Please see https://www.php.net/manual/de/migration81.php and especially https://www.php.net/manual/de/migration81.deprecated.php for all changes.

Thanks.

**Comment by dasistwas** [comment]
Please use the latest version from github. Moodle HQ is very slow in approving new plugins and the most recent version depends on a new plugin. The 7.xx versions do not work with latest PHP and latest Moodle. Download there:
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tags
Depends on:
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/tags

**Comment by abkoch** [comment]
Many thanks.
