### ISSUE TITLE
Endless loop for saving settings after upgrade

### ISSUE THREAD

**Issue by agru** [Wunderbyte-GmbH/moodle-mod_booking#330]
**Describe the bug**
Endless loop for saving new settings without any option open.

**Versions uses**
Moodle version: 4.1.6 (Build: 20231009)
Booking version: Tag 8.0.48
Wunderbyte Table: Tag 1.8.1

**To Reproduce**
1. Install mod_booking and local_wunderbyte_table
2. Confirm new settings
3. Get stuck in following loop
4. System page for website administration (https://moodle.somedomain.de/admin/index.php is automatically forwarded to https://devmoodle.somedomain.de/admin/upgradesettings.php. There is endless loop when clicking on save below the following text: "Die folgenden Optionen wurden bei der letzten Aktualisierung hinzugefügt. Ändern Sie (falls nötig) die voreingestellten Werte und speichern Sie die Einstellungen. Neue Einstellungen - Buchung". Therefor the system page of website administration is not reachable anymore.

**Expected behavior**
Confirm once and end the upgrade process

**Comment by bernhard-wunderbyte** [comment]
Fixed in Booking 8.0.50: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.0.50

**Comment by bernhard-wunderbyte** [comment]
For installation please go directly to: &lt;yourdomain&gt;/admin/tool/installaddon/index.php

**Comment by bernhard-wunderbyte** [comment]
Please let us know, if everything worked as expected.

**Comment by agru** [comment]
Installation now worked and the settings loop is gone. Thank you very much for this very quick fix!
