### ISSUE TITLE
How to trigger cancellation message when event is cancelled by organizer?

### ISSUE THREAD

**Issue by VOOM108** [Wunderbyte-GmbH/moodle-mod_booking#331]
**Versions uses**
Moodle version: 3.10
Booking version: v7.0.22.18

In the docs there is mentioned that Booking includes cancellation system. From the settings I would presume, that the message "Cancelled booking message" is a message that goes out to the user, if the event is cancelled by the organizer.

But we cannot find a way to cancel an event and trigger that message. We tried deleting the event, but that did not trigger the message. 

What are we missing?

**Comment by dasistwas** [comment]
The cancellation message is the message when a user cancels an already booked option. It is not when the organiser cancels the option. But you have more features in booking 8, which you can download here on github.

**Comment by VOOM108** [comment]
I cannot find - as in I searched Github and Google - what you are referring to as "booking 8" - could you provide a link?

**Comment by dasistwas** [comment]
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tags

**Comment by dasistwas** [comment]
It requires also this plugin to be installed: https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/tags and you need to upgrade to M4.1

**Comment by VOOM108** [comment]
I was looking at the branch names. Thanks for the hint. Upgrading Moodle might not be possible, but I will bring it up. 

Where can I find a list of features that are new in that version?

**Comment by VOOM108** [comment]
> The cancellation message is the message when a user cancels an already booked option. It is not when the organiser cancels the option. But you have more features in booking 8, which you can download here on github.

You wrote, that there are more options in Booking 8, but my questions what the new features are related to my query were never answered. I still need to know, if it is possible to send a cancellation message for events cancelled by the organizer, and if yes, in which version of the plugin. 

I have version 8.2.x on a 4.1.x platform, but will be able to utilize anything that works with 4.4.x soon. 

I found this mail template to inform about changes, but it is not clear to me, what kinds of changes the placeholder can stand for.
 
![image](https://github.com/user-attachments/assets/3e228c41-0cfc-4320-9d0a-9134139e6659)

**Comment by dasistwas** [comment]
Sorry, this is not a support forum, but a Bug-Tracker. If you want to have professional support please contact us at info at wunderbyte at.

**Comment by VOOM108** [comment]
I had hoped you could simply point to a documentation. But I also used the contact button on the demo site, where I did not find the documentation or courses mentioned in the text, either. So hopefully, I will get an answer from there, or should I rather write again by email?
