### ISSUE TITLE
Make sure description HTML does not break overall HTML

### ISSUE THREAD

**Issue by bernhard-wunderbyte** [Wunderbyte-GmbH/moodle-mod_booking#332]
Example: A description has a broken HTML tag like `<br<` instead of `<br>`

Currently this can break the HTML of the whole site. We need to find a way to "encapsulate" the HTML of booking option descriptions so their HTML cannot break the overall site.

**Comment by georgmaisser** [comment]
Issue can only occur when uploading description via csv: we choose to ignore this.
