### ISSUE TITLE
Registration in the calendar

### ISSUE THREAD

**Issue by Sandrokkan** [Wunderbyte-GmbH/moodle-mod_booking#334]
If I change the setting of a booking (after it has been saved) so that it is recorded in the Moodle calendar this does not happen

7.8.7.02
2023012702

**Comment by bernhard-wunderbyte** [comment]
This is a bug in Booking 7 which is quite old - we do not support it anymore actually. We only do fixes for Booking 8, which we hope to release soon (as soon as Wunderbyte Table can be released on moodle.org).
