### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Sandrokkan** [Wunderbyte-GmbH/moodle-mod_booking#335]
If I change the setting of a booking (after it has been saved) so that it is recorded in the Moodle calendar this does not happen

8.0.52
2023112800

Moodle 4.1.1
Theme Moove

**Comment by bernhard-wunderbyte** [comment]
I added some fixes for this in Booking 8.0.53 - https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.0.53

However, please note the following: Setting calendar entries **only works well with optiondates** (sessions). We are currently redesigning the way dates work in Booking. Currently you can set dates for booking options like this:

![Bildschirmfoto 2023-12-04 um 16 35 36](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/78346453/6a3e4843-243d-404f-9bc8-b708ab2eac47)

and you can **additionally** set **date series and custom option dates** (sessions) like this:

![Bildschirmfoto 2023-12-04 um 16 36 16](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/78346453/81322e1b-eb04-4d2e-b037-085aaefdd159)

![Bildschirmfoto 2023-12-04 um 16 36 32](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/78346453/16bc9b71-f47c-4c82-a61f-230be61e630d)

Once you have **any** optiondate (a date set via "Dates"), the date of the booking option will be set to the **beginning of the first** and **end of the last** optiondate.

In the upcoming booking versions, we will improve the usability of this massively. So there will be **only optiondates** and no separate date for the booking option anymore. This means, we won't fix the calendar functionality for booking options but **only** for option dates.

**Comment by bernhard-wunderbyte** [comment]
@georgmaisser FYI

**Comment by Sandrokkan** [comment]
Thank you very much
