### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Sandrokkan** [Wunderbyte-GmbH/moodle-mod_booking#340]
Good morning, I am translating the Italian language plugin with AMOS but many strings are missing. For example, I can't find the text related to the tabs
![Screenshot 2023-12-21 090521](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/109354224/9f7bde48-0370-4baa-a7b3-c29bb25474d2)

**Comment by georgmaisser** [comment]
Hi,
in the booking.php, the missing strings are present. I am not sure why you don't find them...

activebookingoptions
showallbookingoptions
visibleoptions
invisibleoptions

**Comment by dasistwas** [comment]
As I published the new version only recently, maybe Amos takes some time before the new strings are there.
