### ISSUE TITLE
No link in 'teached by me' to booking/report.php for teachers

### ISSUE THREAD

**Issue by baltaner** [Wunderbyte-GmbH/moodle-mod_booking#341]
**Describe the bug**
A teacher doesn't see a link to the report page booking/report.php?id=XX&optionid=YY

**Versions uses**
Moodle version: 4.3.2
Boooking version: 8.0.55

**To Reproduce**
1. Go to 'Teached by me'
2. No link is shown

**Expected behavior**
In "teached by me" there should be a link to the booking report page
When I copy the link when I'm logged in as "moodle-admin" and open it as teacher I see the report page

**Comment by baltaner** [comment]
and thank you for your great work to the booking plugin - it's really nice!

**Comment by georgmaisser** [comment]
Where exactly do you expect the link?
You can access the reports page always via the link in the booked users section.

![link](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/7524621/87b52ab7-454f-4bf2-ad5d-b01fa812e81e)

**Comment by baltaner** [comment]
Hi,
exactly where you see on your screenshot I expect the link!
I have forgotten to point out, that the "teacher" of this booking-entry has a normal student-role in the Moodle-course.
With the role "teacher" in the Moodle-course I see the link to the report page.
But in our scenario no "booking-teacher" has the course-role "teacher".

**Comment by bernhard-wunderbyte** [comment]
A user with the normal student-role will never be able to access the participants page. Your teachers need to have at least **one** of these capabilities:
- **mod/booking:viewreports**
- **mod/booking:addeditownoption**

**Comment by baltaner** [comment]
Hi,
thank you for your answer.
But when I add the capability mod/booking:viewreports to the student-role (globally and/or in the specific booking-activity) nothing changed - the link to the report is still missing...

Here are a few more observations:
- why can a "booking-teacher" with course-role "student" see the report page if he knows the exact link to the report - a "normal" student (not a "booking-teacher") gets an error message when calling up the report page. No additional capabilities were set.
- the "booking teacher" with the course role "student" can see the "taught by me" tab - but the link to the report page is missing there

- in the prior version of mod_booking 7.8.x a booking-teacher with course-role "student" can see the report-page

**Comment by bernhard-wunderbyte** [comment]
Ok, I fixed this now in Booking **v8.0.56a** - you can get it here: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.0.56a

Please also update Wunderbyte Table: https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/releases/tag/v1.9.3

**Comment by baltaner** [comment]
Thank you!
It works now as expected.
