### ISSUE TITLE
Price not showing up

### ISSUE THREAD

**Issue by rashadkung** [Wunderbyte-GmbH/moodle-mod_booking#342]
<img width="1728" alt="Screenshot 2023-12-24 at 18 31 35" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/154904809/9091244d-fdf7-4e78-94cb-6521692f76a3">
<img width="1728" alt="Screenshot 2023-12-24 at 18 32 15" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/154904809/dac1ec8b-5945-4c97-aa36-5fc41f360d3d">
<img width="1689" alt="Screenshot 2023-12-22 at 21 34 52" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/154904809/37426b29-351a-4169-b451-09a3537d63e1">
<img width="1728" alt="Screenshot 2023-12-26 at 15 09 59" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/154904809/3203aa81-0a48-47d4-a51b-4eb812b1ede7">
**Describe the bug**

**Versions uses**
Moodle version: 4.3.2
Boooking version: 8.0.55

**To Reproduce**

**Expected behavior**
I am using the latest version of Moodle as well as booking. Unfortunately it would not display the price of the course, although it is added in the settings. The price of the courses visible in guest mode. However, as soon as the users login into their account it says price has not been set. I've been using this plug-in for sometime and I've checked all the settings thoroughly including the database but could not find the reason why this is happening. There is no change in the settings that I've made. I've checked the permissions of the users as well as a guest as well, but not find out why this is happening. I would really appreciate any sort of help with because I'm really struggling with my booking system and my users need this working as soon as possible.
[**Screenshots**](<img width="1728" alt="Screenshot 2023-12-24 at 18 31 35" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/154904809/938edba7-98b7-466a-97fe-b97a05db56db">)

**Additional context**

**Comment by dasistwas** [comment]
It looks like you do not have correct settings. For every use case you have to define the appropriate price. When there is no price set for the user who is looking at the booking option, then that's how it looks like. So check your price category prices in the admin settings.

**Comment by georgmaisser** [comment]
To weigh in here:

The working of the price is like this:

- In booking settings ( /admin/category.php?category=modbookingfolder ) you can choose which user profile filed you want to use attribute price categories.
- If a user has not set this field, the price will fall back on the default price category
- But, and I guess this is important for your case, if the user has set sth in this field, it will try to match it with the existing price categories. If that doesn't work, you get the "no price is set" message.

As I can see only one price category in your screenshot, you only have the "default" category. So, for the user profile field which you use as pricecategory field, you will need to enter the string "default". Or, alternatively, leave it blank.

Please tell us if this explanation was sufficient to solve your problem.

**Comment by georgmaisser** [comment]
Please reopen, if our explanation was not sufficient.
