### ISSUE TITLE
Error on page optionformconfig.php (feature_new_option_form_gem)

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#344]
The following error being thrown
/mod/booking/optionformconfig.php

Exception - mod_booking\price::__construct(): Argument #2 ($itemid) must be of type int, null given, called in [dirroot]/mod/booking/classes/option/fields/price.php on line 89
Stack trace:
line 57 of /mod/booking/classes/price.php: TypeError thrown
line 89 of /mod/booking/classes/option/fields/price.php: call to mod_booking\price->__construct()
line 135 of /mod/booking/classes/option/fields_info.php: call to mod_booking\option\fields\price::instance_form_definition()
line 100 of /mod/booking/classes/form/option_form.php: call to mod_booking\option\fields_info::instance_form_definition()
line 217 of /lib/formslib.php: call to mod_booking\form\option_form->definition()
line 73 of /lib/form/classes/dynamic_form.php: call to moodleform->__construct()
line 70 of /mod/booking/classes/form/optionformconfig_form.php: call to core_form\dynamic_form->__construct()
line 217 of /lib/formslib.php: call to mod_booking\form\optionformconfig_form->definition()
line 48 of /mod/booking/optionformconfig.php: call to moodleform->__construct() 

No parameters expected for optionformconfig.php page but it calls option_form which in turn calls /fields/ which has different required parameters

**Comment by georgmaisser** [comment]
We just switched from optionid to id in the option_form.
