### ISSUE TITLE
Missing definition for "mod/booking:view" capability

### ISSUE THREAD

**Issue by danraij** [Wunderbyte-GmbH/moodle-mod_booking#345]
While working on a specific use-case scenario in which I didn't want specific instances of the activity be visible to certain roles, I noticed that the "mod/booking:view" capability isn't defined in _/db/access.php_.

As per my understanding, the definition of this capability is required for activity modules.

**Comment by dasistwas** [comment]
As far as I know the capability here is mod/booking:choose instead of view. @bernhard-wunderbyte could you check?

**Comment by bernhard-wunderbyte** [comment]
Yes, there is the mod/booking:choose capability, but no mod/booking:view capability. mod/booking:choose is used to determine the users who are allowed to book but I'm not really sure if it still works the way as it worked in older booking versions (previous to Booking 8). @georgmaisser We probably should introduce a new mod/booking:view capability. What do you think?

**Comment by bernhard-wunderbyte** [comment]
We added the "mod/booking:view" capability now. It will be added to the next Booking release.
