### ISSUE TITLE
MS SQL support missing

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#35]
Debug info: SQLState: 42000<br>
Error Code: 8127<br>
Message: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Column
"mdl_booking_options.coursestarttime" is invalid in the ORDER BY clause because
it is not contained in either an aggregate function or the GROUP BY clause.<br>

SELECT COUNT(DISTINCT bo.id) AS count FROM mdl_booking_options AS bo LEFT JOIN
mdl_booking_teachers AS bt ON bt.optionid = bo.id LEFT JOIN mdl_user AS ut ON
bt.userid = ut.id LEFT JOIN mdl_booking_answers AS ba ON bo.id = ba.optionid
LEFT JOIN mdl_user AS u ON ba.userid = u.id WHERE bo.bookingid = '1' AND
(bo.courseendtime > 1461592750 OR bo.courseendtime = 0) ORDER BY
bo.coursestarttime DESC
[array (
0 => '1',
)]
# Error code: dmlreadexception

**Comment by Asampson** [comment]
@dasistwas Just wondering if you got anywhere with this issue, we're getting the same error message.

**Comment by dasistwas** [comment]
@Asampson: I do not have funding or a MS SQL testing system for solving this issue. If you provide a fix or funding, then this will be fixed. Otherwise MS SQL won't be supported. Best thing would be to fund or contribute automated testing too. But usually clients only want to pay for features and not for stability or sustainability ;-).

**Comment by johnsto34** [comment]
We had this and moved to MySQL instead which worked fine.

**Comment by dasistwas** [comment]
MS SQL won't be supported...
