### ISSUE TITLE
Subbooking show the wrong string

### ISSUE THREAD

**Issue by bernhard-wunderbyte** [Wunderbyte-GmbH/moodle-mod_booking#356]
When creating a subbooking, the user can provide a description string:
![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/78346453/af1e16e4-66f9-43f9-8232-656a41f5f048)

But in the actual Booking process another string is shown:
![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/78346453/ecf18d66-1e96-4328-bf55-593fa3d4bfce)

**Comment by georgmaisser** [comment]
is this fixed @bernhard-wunderbyte ?

**Comment by bernhard-wunderbyte** [comment]
I fixed this now.
