### ISSUE TITLE
Not sends email when user made a booking

### ISSUE THREAD

**Issue by lorenzogreco** [Wunderbyte-GmbH/moodle-mod_booking#36]
Module Release Diane Selwyn 1.0
When a student does a booking, not sends email to "booking manager" and to students.
but
when a student cancel the booking, the email works.

**Comment by atlet** [comment]
I tested and it's working fine. Did you enable email notifications in booking settings?

**Comment by lorenzogreco** [comment]
Yes, it is enabled,(Send confirmation email to booking manager) and (Username of the booking manager) is admin
Infact when I cancel a booking, i receive the email, but i not receving it when a student does a booking.

I have Enable rec. number generation? NO (disabled)
I'm working with moodle 3.03, on PHP 5.5

**Comment by demontech** [comment]
Yes, I'm having the same problem

**Comment by atlet** [comment]
Yes, its't working on Moodle up to 2.9. I'm planing to migrate to Moodle 2.9+ this summer, so I'll fix this isssue.

**Comment by demontech** [comment]
It's not working for 2.9 either - same issue confirmation email is not received, but cancellation email is working fine.

**Comment by atlet** [comment]
I fixed. It's in branch develop - my github. Please check if it's working also for you.

**Comment by demontech** [comment]
Nice, it looks like it's working fine for now, but the new csv booking import with options is not.

Thanks Andraz!

**Comment by atlet** [comment]
Fixed - in my git...
