### ISSUE TITLE
Options to edit or delete booking don't show - 2016051900

### ISSUE THREAD

**Issue by demontech** [Wunderbyte-GmbH/moodle-mod_booking#37]
Option to edit or delete booking are not displayed

![booking mod issue](https://cloud.githubusercontent.com/assets/8148238/15602133/319b2780-23a8-11e6-992f-44bab4ed4195.png)

**Comment by atlet** [comment]
Yes, as I did some modifications to UX, the optios are moved to Administration menu.

**Comment by demontech** [comment]
I see it now Thanks!!

Any plans for 3.1 version? I installed on 3.1 and I have the following message:

The following plugins in your system are using Events 1 API deprecated handlers: 'mod_booking'. Please, update them to use Events 2 API. See https://docs.moodle.org/dev/Event_2#Event_dispatching_and_observers.

congratulations on this plugin, you're doing an excellent job!

**Comment by dasistwas** [comment]
This usability issue will be resolved with following issue: #44
