### ISSUE TITLE
Using old Event 1 API

### ISSUE THREAD

**Issue by nitro2010-zz** [Wunderbyte-GmbH/moodle-mod_booking#38]
The following plugins in your system are using Events 1 API deprecated handlers: '**mod_booking**, enrol_elediacohortgreeting, local_obf, tool_mergeusers, local_welcome'. Please, update them to use Events 2 API. See https://docs.moodle.org/dev/Event_2#Event_dispatching_and_observers.

**Comment by atlet** [comment]
I'm planning to upgrade this summer.

**Comment by dasistwas** [comment]
Fixed in c9bf64cf80443658a6aa0c94a985397e118426a7
