### ISSUE TITLE
Many options are created within the booking instance as there are users present in the CSV file

### ISSUE THREAD

**Issue by beppemandara** [Wunderbyte-GmbH/moodle-mod_booking#381]
**Describe the bug**
Trying to import a CSV file into a course with a booking instance to create options and add users returns the following result: as many options are created within the booking instance as there are users present in the CSV file.

**Versions uses**
Moodle version:  4.1.7+ (build 20231221)
Boooking version: 8.0.55

**To Reproduce**
Steps to reproduce the behavior A (CSV import without option already present):
1. Go to the chosen course
2. Click on 'CSV Import' on other menu
3. Import CSV file
4. See on 'Active options' as many optionsas there are users

**Expected behavior**
The expected behavior would be the creation of an edition containing the users present in the CSV file.

**Screenshots**
![Img_Err_Booking_Multiple_Options_with_CSV](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/25076545/03eaa9a7-2ee2-4275-b9fa-9ef3cdae0426)

**Additional context**
The same thing happens when you try, with a CSV file, to insert users into an existing edition but without users. The CSV file used has this scheme: 
![Img_Err_Booking_Multiple_Options_with_CSV_option_exist](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/25076545/2c3f30b8-aed7-41ed-ba2f-c132b7b7b393)

**Comment by dasistwas** [comment]
I suppose the CSV file has not the right format. Could you attach an example CSV?

**Comment by beppemandara** [comment]
Hi, I'm attaching the CSV file used for one of the tests from which I took the screenshot attached above.
[booking_test_BIS.csv](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/files/13974159/booking_test_BIS.csv)
For the CSV file I started from the example at the url https://docs.moodle.org/403/en/Booking_module

**Comment by dasistwas** [comment]
Thank you. That might be outdated. @bernhard-wunderbyte do we have a new template?

**Comment by georgmaisser** [comment]
You need to use the identifier now! Matching was previously done via the name, but we discontinued that. When you edit a booking option, you find the unique identifier. Add it to your csv and users should be booked.

**Comment by beppemandara** [comment]
Thanks, using 'identifier' by importing a CSV file I can create the options and register the related users, I can also create the groups linked to the options but it doesn't include the users present in the option, please where can I find some documentation updated or an example of a CSV file? TIA

**Comment by beppemandara** [comment]
I found that by using 'enrolmentstatus' with a value of 2 in the import CSV file I can insert users into the relevant course group. Thanks good evening.

**Comment by bernhard-wunderbyte** [comment]
Ok, great. I'll close this for now.
