### ISSUE TITLE
MUSI-322 Umbuchen

### ISSUE THREAD

**Issue by bernhard-wunderbyte** [Wunderbyte-GmbH/moodle-mod_booking#389]

**Comment by georgmaisser** [comment]
- [x] Button in history, mark for rebooking -> Adds the item and it's price to the shopping cart as negative value.
- [x] Area of the item should be called "rebookitem".
- [x] Itemid should be the id of the record in shopping cart history.
- [ ] Only show button if it's within the allowed period (This has to be defined, there needs to be a setting etc.)
- [ ] Description with "Rebooking" marker plus name of option to be canceled
- [ ] Booking fee was already paid, so there must be **no booking fee** when rebooking.
- [ ] There is no limit of courses that can be marked for rebooking.
- [x] A user can only book as many new courses as have been marked for rebooking (example: a user has marked 2 courses for rebooking: a user can book 1 or 2 new courses => the overall price must not be negative)
  - If the user would mark one course for rebooking and book 2 new courses, this would be a possibility for users to circumvent the booking fee, so we cannot allow this!
- [x] No matter how many negative items are there in the cart, the total price at the end will never be lower than 0
- [x] If you add a course, the calculation will be done right in the cart
- [ ] Sorting of the items should be adapted:
  - [ ] the items to be bought are on top
  - [ ] the items to be rebooked are at the bottom of the list
- [x] Make sure ledger and history are correctly written at checkout.
- [ ] Make sure a loss of cache during payment process will not lead to an error
- [ ] Make sure we don't use cancelation fee, rebookingcredit or other stuff during rebooking process
