### ISSUE TITLE
Permissions bug? (Event and free seats visible for all, but only bookable for specific role or cohort)

### ISSUE THREAD

**Issue by VOOM108** [Wunderbyte-GmbH/moodle-mod_booking#407]
**Is your feature request related to a problem? Please describe.**
We want interested people be able to see, if there are free seats for an event, but only be able to book a seat after buying the whole course. There are courses with several events, that repeat after some weeks. People should be able to see in advance, if there are free seats at dates that are suitable for them. We do not want them to buy the course and only then see, that there are no free seats for several weeks or none, that are suitable for them. On the other hand, people who have not bought the course, of course should not be able to book seats and block them for people who are actually allowed to visit them because they bought the course. 

**Describe the solution you'd like**
I tried to disallow (retract) booking:choice for authenticated users, in order to then allow them explicitly for people who bought the course. (still need to figure out the last part). But when logging in as a user without further enrollments, I can still book that option. 

**Describe alternatives you've considered**
Any way that would enable the scenario would suffice. Maybe I am only overlooking sth. with the permission settings?

**Comment by dasistwas** [comment]
What you can do is to have an enrolment into the course where you have the booking instance set up. You are charging for accessing the course, and then enrolled users can book seats in the booking module within the course.

**Comment by VOOM108** [comment]
But then users who did not buy the course could not see in advance, if there are free seats, right?

**Comment by VOOM108** [comment]
I think there actually is a bug concerning permissions. I removed the permission for students to book, and even added students to forbidden to book - however, students can still book without any restrictions. It does not matter if I do this globally for a role or locally just for the booking activity. 

<img width="1204" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/0cd4e2eb-451d-4162-8a97-62e70987a2ee">

Checking the permissions for a student in that course, it says no, but as said, the student can still book: 

<img width="553" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/b64ffa26-ec4e-478b-9c27-72040798a665">

 Of course there is still the question, whether that would help with my goal. Since there is no extra permission "view booking" to "choose booking" it may not be viewable if the permission worked anyway. This could on the other hand then be a route to implement sth. of that kind, to discern permissions for view and book.

**Comment by georgmaisser** [comment]
You were right, it was an oversight not to have a proper condition to block booking for users who have no right on the instance. We added this now. If you want that anybody (even not enrolled in the given course) can book, you will need to give the right to "mod/booking:choose" to authenticated user.

**Comment by VOOM108** [comment]
Thanks for the fix :)

>If you want that anybody (even not enrolled in the given course) can book, you will need to give the right to "mod/booking:choose" to authenticated User.

I basically want kind of the opposite: People who are not enrolled should see if there are free slots, but not be able to book them without enrolling in the course aka buying it. So I suppose I can't do that without a permission "view" separate from the permission "book". Then I could set "see" to authenticated user and "book" to enrolled user.  

But I will check what I can achieve with the book-permission.
