### ISSUE TITLE
Missing events and wrong event logs when users a subscribed with "book other users"

### ISSUE THREAD

**Issue by bernhard-wunderbyte** [Wunderbyte-GmbH/moodle-mod_booking#409]
When users a booked with Booking using the "book other users" (subscribeuser) functionality, we do not have any good logs to see who booked the users.

We need to see the user who booked the users as well as who was booked in event logs.

Also the log message when a user is booked by "book other users" is misleading: "The user with id 12275 booked the booking option with id 418." => It looks as if the user has booked herself.

Instead the message should be something like "The user with id X booked the booking option with id Y **for user with id Z.**"

**Comment by georgmaisser** [comment]
fixed with 5ae9088bde3fb3c4a6cd2badcababe5d9602d8e8
