### ISSUE TITLE
Description Box missing Filter

### ISSUE THREAD

**Issue by dustinbrisebois** [Wunderbyte-GmbH/moodle-mod_booking#411]
Inside of booking editing we are seeing that the appropriate Moodle filters are not added to the description box

![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16727280/c5ec970f-6e14-4737-b4d2-ca391849978e)

**Comment by dasistwas** [comment]
Could you describe in detail what you mean? The screenshot just shows an empty description field using Moodle auto-format. Maybe you want to change to HTML editor?

**Comment by bernhard-wunderbyte** [comment]
@dustinbrisebois You can easily fix this by running the following SQL update statement in your DB (please use the correct prefix, it might be something else than "mdl_"):

```
UPDATE mdl_booking_options
SET descriptionformat = 1
WHERE descriptionformat = 0
```
