### ISSUE TITLE
Wie kann ein Nutzer seine Buchung stornieren? 

### ISSUE THREAD

**Issue by VOOM108** [Wunderbyte-GmbH/moodle-mod_booking#426]
**Describe the bug**
Es ist an keiner Stelle, weder bei den Einstellungen des Bookings, noch in den einzelnen Optionen, das Stornieren unterbunden. Doch wenn ich als Nutzer buche, finde ich danach nirgendwo eine Möglichkeit zum Stornieren. Das Zahnrad bei den Optionen ist als TN nicht vorhanden, an der Stelle ist nur ein Drucken-Button. 

**Versions uses**
Moodle version: 4.1
Booking version: 2023121100

**Screenshots**
<img width="650" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/66b0e011-f316-4cbb-890b-b447f09d360b">

**Comment by VOOM108** [comment]
Oder meint das hier, dass inzwischen Stornieren ohne Pro gar nicht mehr möglich ist? Ich dachte, dass da zusätzliche Funktionen einstellbar sind, aber nicht, dass eine so grundlegende Funktion wie Stornieren gar nicht mehr geht. 

<img width="779" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/c8899466-da7e-4963-939a-8b27c1a1a909">

**Comment by dasistwas** [comment]
Eigentlich sollte es ein Setting dafür geben. Pro ist dafür nicht notwendig.

**Comment by VOOM108** [comment]
Hier sind meine Einstellungen, Buchung allgemein:
<img width="1066" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/2e9c7dc0-8447-4eee-b002-1455d872a747">

Und in der Buchungsoption:
<img width="935" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/34177d4f-0b43-46dd-bfb7-8c82aef1f950">

Was auch beides eigentlich bedeuten würde, dass Stornieren können default ist, und man es explizit deaktivieren müsste.

**Comment by dasistwas** [comment]
Ich würde mal auf die neueste Booking Version wechseln. Die verwendete ist ziemlich alt

**Comment by VOOM108** [comment]
Hab ich gemacht. Nun ist das Drucksymbol direkt über dem Button, aber sonst hat sich nichts geändert.

**Comment by VOOM108** [comment]
Erst mit dieser Einstellung wird der Stornieren-Button sichtbar. Aber eigentlich soll nach Beginn der Veranstaltung nicht mehr storniert werden können. 
<img width="901" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/c578db20-2d7e-49f9-a38e-ce91089303d4">

Ach ja, in dem Menü gibt es nur negative Werte und "kein Limit" zur Auswahl, obwohl da steht "n Tage vor Beginn" - und das Menü wird auch erst editierbar, wenn das darüber angekreuzt ist.

**Comment by VOOM108** [comment]
Vielleicht ist da ein sprachliches und ein Logikproblem:
<img width="939" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/09f897b3-8541-4717-8a92-0701070bb372">
Positive Werte sind weit unter den negativen Werten vorhanden, aber dass es ausgegraut ist, wenn das darüber nicht angekreuzt ist, macht dann keinen Sinn. Wenn es aber eigentlich das Stornieren generell erlauben soll, ist der Punkt darüber obsolet, da der Erlauben-Punkt das bereits in beide Richtungen abdeckt.

**Comment by bernhard-wunderbyte** [comment]
Hallo @VOOM108 - ich habe mir das jetzt angesehen und ich glaube, hier hat sich tatsächlich ein Bug eingeschlichen. Ich werde mir das ansehen und das fixen. Danke für den Hinweis!

**Comment by dasistwas** [comment]
Bitte für das und für den Download Bug gleich einen Behat Test beauftragen. @bernhard-wunderbyte

**Comment by bernhard-wunderbyte** [comment]
Wenn es folgendermaßen konfiguriert ist, sollte es richtig funktionieren:

<img width="693" alt="Bildschirmfoto 2024-03-01 um 12 54 43" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/78346453/ccbb30fd-9e4c-419b-8188-c3ed676a1c5d">

Wichtig ist, dass man den Wert "Nutzer:innen können nur bis n Tage vor Kursstart stornieren. Negative Werte meinen n Tage NACH Kursstart." auf "0" setzt, damit man **ab** Kursstart **nicht mehr** stornieren kann. Wir werden uns noch überlegen, wie wir das Interface hier intuitiver/logischer machen können.

**Comment by VOOM108** [comment]
Ja, so hatte ich es jetzt auch gemacht, allerdings mit 1 statt 0, da es nur bis einen Tag davor möglich sein soll. Ist so natürlich nur ein Workaround.
