### ISSUE TITLE
Beim Hochladen von Terminen via CSV werden die Datum/Zeit-Angaben nicht mehr erkannt

### ISSUE THREAD

**Issue by VOOM108** [Wunderbyte-GmbH/moodle-mod_booking#427]
**Describe the bug**
Ich konnte bis gestern wie gewohnt CSV-Dateien mit Terminen hochladen, und Datum und Zeit wurden korrekt angelegt. Wegen des issues mit den Stornierungen habe ich dann ein Update des Plugins gemacht. Mit den exakt gleichen Dateien wird nun kein Datum mehr angelegt. Format ist d.m.Y H:i:s und die CSV-Dateien haben dieses Format exakt wie immer. Ob der Zusammenhang mit dem Update kausal ist, weiß ich nicht, das war die einzige Änderung am Kontext. 

**Versions uses**
Moodle version: 4.1
Booking version: 2024022701

**Screenshots**
<img width="411" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/cde923a6-be46-4d15-8777-68489510c630">
<img width="207" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/a0bc8a3e-1338-44a4-81ef-57bdcbb993a9">

**Comment by dasistwas** [comment]
Können Sie uns eine Beispiel CSV per E-Mail schicken an info@wunderbyte.at

**Comment by georgmaisser** [comment]
Hi, also:

wir haben gerade "startdate" & "enddate" wieder als Keys hinzugefügt. Bisher hat starttime & coursestarttime etc. funktioniert. e28a712092236ab9da8b78e90c428020c41466df

Außerdem gab es einen Error bei addtocalendar, den haben wir auch gefixt 6f909fe1040b7e930357c6a9da79b113b6442745

Der Branch MOODLE_401_DEV ist ein wenig experimentell, aber kann auf eigene Gefahr ausgecheckt werden (aufpassen, dass auch WB Table in entsprechender Version ausgecheckt werden muss.

Bei uns wird das übermittelte CSV jetzt korrekt importiert. Nur in der headerspalte von "teacheremail" ist ein Leerzeichen, das muss man unbedingt entfernen.

**Comment by VOOM108** [comment]
Termine gehen nun mit der DEV, dafür werden nun die Locations nicht hochgeladen bzw. zumindest nicht angezeigt.
