### ISSUE TITLE
Kein Formularfeld für Orts-Angaben (location) mehr, div.location in der Ausgabe leer

### ISSUE THREAD

**Issue by VOOM108** [Wunderbyte-GmbH/moodle-mod_booking#428]
**Describe the bug**

Ich habe wie immer eine Spalte location in der CSV. Beim CSV-Upload werden die Locations nicht hochgeladen bzw. zumindest nicht angezeigt. Ich sehe beim Bearbeiten eines Events nicht mal mehr ein Eingabefeld mehr für den Ort. Der Ort ist bei Buchungen von Praxisterminen eine absolut notwendige Angabe. Bis vor Kurzem war das Feld auch noch vorhanden, und es existiert im Ausgabe-HTML als leeres DIV mit der Klasse .location direkt vor dem Termin. 

**Versions uses**
Moodle version: 4.1
Booking version: 401-DEV as of 6.3.2024

**Comment by VOOM108** [comment]
Aktuell: 
<img width="976" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/5fab25e8-be39-4a1a-b71e-82ced86aafd3">

Noch in Version: 8.0.55  2023121100
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/4e17d702-d479-426e-9f73-4f6cf87f182a)

**Comment by georgmaisser** [comment]
Guten Tag,
Location wird nicht mehr angezeigt, wenn das local_entities Plugin installiert ist, weil es dabei zu Überschneidungen kommt. Kann es sein, dass Sie das installiert haben?

**Comment by VOOM108** [comment]
Es war da, ich kann mich aber nicht daran erinnern, es installiert zu haben, da es keine Funktion hat, die ich auf dieser Plattform je benötigen werden. Aber ja, das war die Ursache des Problems. :)
