### ISSUE TITLE
Alle Termine doppelt im Kalender (Kurstermine, gleiche Buchungsoption)

### ISSUE THREAD

**Issue by VOOM108** [Wunderbyte-GmbH/moodle-mod_booking#429]
**Describe the bug**
Wegen der kürzlichen Issues habe ich immer wieder eine Bookinginstanz gelöscht, um nicht die Termine einzeln löschen zu müssen. Vielleicht wurden die Termine dabei nicht aus dem Kalender gelöscht. Ich habe nun jedenfalls alle Termine doppelt im Kalender stehen. 

Ansonsten weiß ich nicht, wann und wie das entstanden ist, vielleicht wurden beim letzten Upload auch direkt doppelte Termine angelegt (dann mit der 401-DEV) - da war ja irgendwas mit dem addtocalendar. 

**Versions uses**
Moodle version: 4.1
Booking version: zwischen 23121100 und aktuelle 401-DEV

**To Reproduce**
Wenn es am Upload liegt: Termine hochladen, die Buchungsinstanz löschen, neu anlegen, wieder Termine hochladen nun ist jeder Termin doppelt im Kalender

**Expected behavior**
Termine im Kalender werden mit ihren Buchungsoptionen gelöscht, Termine werden nur einmal pro Option angelegt

**Comment by VOOM108** [comment]
Dazu kommt, dass ich die doppelten Einträge offenbar nicht ohne damit verbundene Buchungsoption löschen kann. Sie sind immer beide mit der gleichen Buchungsoption verlinkt, gehören also wohl dazu. Ich kann es gerade nicht mal manuell aufräumen, bzw. ich wüsste nicht wie. Da sind jetzt 5 Kurse mit ca. 200 Terminen betroffen. 

<img width="642" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/e287c88a-8498-4a69-b058-d50d4a4d8141">

**Comment by VOOM108** [comment]
Noch etwas ausprobiert: wenn ich bei einem Termin unter dem Abschnittstitel "Termine" auswähle: "nicht in den Kurs-Kalender eintragen", sind beide Termine weg. Wenn ich dort wieder "in den Kurs-Kalender eintragen" wähle, sind es wieder zwei.

**Comment by bernhard-wunderbyte** [comment]
Wir haben diese Bugs bereits gefixt, bitte gehen Sie folgendermaßen vor:

1. Booking auf v8.1.33 und Wunderbyte Table auf v1.9.16 updaten:
- https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/tags
- https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tags

2. Sicherstellen, dass der CRON-Job regelmäßig ausgeführt wird - am besten jede Minute (https://docs.moodle.org/403/de/Cron-Job)

3. Mit folgendem SQL die Kalender-Artefakte aus der Datenbank löschen:
```
DELETE FROM mdl_event
WHERE eventtype = 'course'
AND component = 'mod_booking' AND modulename = 'booking'
AND visible = 1
AND (uuid = '' OR uuid IS NULL)
```
**mdl_** bitte durch das korrekte Prefix ersetzen (falls Sie ein anderes verwenden). Wichtig ist die letzte Zeile => Einträge bei denen die uuid fehlt, sind Kalender-Artefakte. Wir identifizieren Kalender-Events bei neueren Booking-Versionen über die uuid.

Bitte lassen Sie uns wissen, ob das Ihr Problem gelöst hat. Falls nicht, werde ich dieses Ticket noch einmal öffnen.

**Comment by bernhard-wunderbyte** [comment]
@VOOM108 Zusätzlich können Sie auch noch dieses SQL ausführen, um wirklich alle Artefakte zu entfernen:

```
DELETE FROM mdl_event
WHERE eventtype = 'course' AND component = 'mod_booking' AND modulename = 'booking'
AND instance NOT IN (SELECT id FROM mdl_booking)
```

Auch hier bitte wieder auf Prefix (mdl_) achten und ggf. ersetzen.

**Comment by VOOM108** [comment]
Die Tabellen-Version war die angegebene, die Bookingversion habe ich von 8.1.30 auf 8.1.33 gebracht. Ich habe beide SQL-Abfragen ausgeführt und bei beiden 0 Ergebnisse erhalten, also es wurde nichts geändert. Präfix ist mdl_ Cron läuft alle 5 Minuten, mehr geht da nicht, wo das Moodle liegt. Einträge sind immer noch doppelt.

**Comment by VOOM108** [comment]
Ich glaube, das liegt daran, dass modulename bei denen mit leerer uid auch leer ist

<img width="1493" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/ccf1d664-3c85-48a9-bb53-e91d85830071">

**Comment by VOOM108** [comment]
Das sieht danach aus, dass die uuid nicht leer ist, sondern für den gleichen Termin zwei existieren

<img width="1659" alt="image" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/16562946/d93d3125-094e-4046-8de8-40f0efe67e93">

**Comment by bernhard-wunderbyte** [comment]
Die Einträge bei denen die uuid auf "-0" endet, sind ebenfalls Relikte, die müssen auch noch gelöscht werden:

```
DELETE FROM mdl_event
WHERE eventtype = 'course'
AND component = 'mod_booking' AND modulename = 'booking'
AND uuid LIKE '%-0'
```

**Comment by VOOM108** [comment]
Danke, jetzt sind sie weg :)
