### ISSUE TITLE
Buchung spiegeln oder verschieben

### ISSUE THREAD

**Issue by hnazmy** [Wunderbyte-GmbH/moodle-mod_booking#443]
Hallo Ihr Lieben, 

wir planen Euer Tool in einer Moodle Instanz für ein ganzes Bundesland einzusetzen. Leider müssen wir aus Datenschutzgründen Bookings für einzelne Ressorts erstellen. Gerne würden wir die Kurse in den einzelnen Bookings jedoch ab einem bestimmten Zeitpunkt, und wenn noch freie Plätze sind, auch in einem Systemweiten Booking freigeben. Ich suche quasi nach einer Möglichkeit einen Kurs zu spiegeln oder zu verschieben. Vielleicht habt ihr ja eine Idee. 

Viele Grüße, 

Hisham

**Comment by dasistwas** [comment]
Bitte für Supportanfragen dieser Art info@wunderbye.at kontaktieren. Die Github Issues sind primär für Bug-Reports gedacht.
