### ISSUE TITLE
Incorrect integer value: '' for column `database`.`mdl_booking_options`.`responsiblecontact` at row 1

### ISSUE THREAD

**Issue by adit-terus** [Wunderbyte-GmbH/moodle-mod_booking#444]
**Describe the bug**
Whenever I try to save an existing booking option, I always encounter that error. However, creating a booking activity or a new booking option doesn't trigger any error.

Interestingly, this issue doesn't occur in other Moodle instances; it's specific only to this particular Moodle. Copying the activity or course to other Moodles doesn't trigger this error. I suspect that there might be a misconfiguration or incorrect value in the responsible contact settings of this specific Moodle, but I'm not sure where to find it.

Here is the error message:
Incorrect integer value: '' for column `database`.`mdl_booking_options`.`responsiblecontact` at row 1
UPDATE mdl_booking_options SET bookingid = ?,json = ?,text = ?,identifier = ?,titleprefix = ?,description = ?,descriptionformat = ?,invisible = ?,annotation = ?,location = ?,institution = ?,address = ?,maxanswers = ?,maxoverbooking = ?,minanswers = ?,pollurl = ?,pollurlteachers = ?,courseid = ?,coursestarttime = ?,courseendtime = ?,dayofweektime = ?,dayofweek = ?,semesterid = ?,addtocalendar = ?,responsiblecontact = ?,priceformulaadd = ?,priceformulamultiply = ?,priceformulaoff = ?,credits = ?,sortorder = ?,availability = ?,bookingopeningtime = ?,bookingclosingtime = ?,disablebookingusers = ?,notificationtext = ?,notificationtextformat = ?,removeafterminutes = ?,shorturl = ?,howmanyusers = ?,beforebookedtext = ?,beforecompletedtext = ?,aftercompletedtext = ? WHERE id=?
[array (
  0 => 1,
  1 => '{"useprice":0}',
  2 => 'Test Booking',
  3 => 'dcbd16e2',
  4 => '',
  5 => '',
  6 => '1',
  7 => 0,
  8 => '',
  9 => '',
  10 => 
  array (
    0 => '',
  ),
  11 => '',
  12 => 0,
  13 => 0,
  14 => 0,
  15 => '',
  16 => '',
  17 => 0,
  18 => NULL,
  19 => NULL,
  20 => '',
  21 => '',
  22 => 0,
  23 => 0,
  24 => 
  array (
    0 => '0',
  ),
  25 => 0,
  26 => 1,
  27 => 0,
  28 => 0,
  29 => 0,
  30 => '[]',
  31 => 0,
  32 => 0,
  33 => 0,
  34 => '',
  35 => '1',
  36 => 0,
  37 => '',
  38 => 0,
  39 => '',
  40 => '',
  41 => '',
  42 => 122,
)]
Error code: dmlwriteexception
* line 497 of /lib/dml/moodle_database.php: dml_write_exception thrown
* line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
* line 1604 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
* line 1636 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->update_record_raw()
* line 3352 of /mod/booking/classes/booking_option.php: call to mysqli_native_moodle_database->update_record()
* line 248 of /mod/booking/classes/form/option_form.php: call to mod_booking\booking_option::update()
* line 77 of /lib/form/classes/external/dynamic_form.php: call to mod_booking\form\option_form->process_dynamic_submission()
* line 262 of /lib/externallib.php: call to core_form\external\dynamic_form::execute()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

**Versions uses**
Moodle version: 4.1.9
Booking version: 8.1.26
PHP: 7.4 or 8.1 have the same error.

**To Reproduce**
Steps to reproduce the behavior in this spesific Moodle only:
1. Go to any activity booking
2. Click on 'Edit booking option'
3. Scroll down and just click save
4. Got error message and cannot continue

**Screenshots**
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/115072781/509865ec-b041-46b9-bd18-120abcbf2116)

**Comment by dasistwas** [comment]
Could you try to use the latest version of wb table and booking. You find them there:

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tags
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/tags

**Comment by dasistwas** [comment]
Another option is to set a correct user under "Responsible contact".

**Comment by adit-terus** [comment]
Updating the plugin to the latest version from the GitHub link fixed the issue. Additionally, I now see the "Responsible Contact Option" when editing the booking option.

Thank you for the fast response.
