### ISSUE TITLE
Creation of options and import of users with csv file

### ISSUE THREAD

**Issue by beppemandara** [Wunderbyte-GmbH/moodle-mod_booking#447]
**Describe the bug**
when I try to import a CSV file into a course with a booking instance to create various editions and add a user to each, I get the following result: the desired editions are created within the instance with the indicated settings but the users present in the CSV file, neither in the edition nor as enrolled in the course and not even the groups relating to the editions are created. I did various tests and even by first inserting the users as course participants, the csv file does not insert them into the editions.

**Versions uses**
Moodle version:  4.1.3+ (build 20230609)
Boooking version: 8.1.26

**To Reproduce**
0. Create three new users (optional)
1. Create a new course (with visible groups)
2. Add booking to the created course
3. Create a new instance within booking (flag on Automatic enrollment of users to the course and on Automatically enroll users in this edition's group)
4. Import csv files
5. Check the outcome

[bookingTestElde_v12.csv](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/files/14702402/bookingTestElde_v12.csv)
[bookingTestElde_v11.csv](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/files/14702417/bookingTestElde_v11.csv)
[bookingTestElde_v10.csv](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/files/14702425/bookingTestElde_v10.csv)

**Expected behavior**
Importing the csv file should create the option, the group and enroll users in the option.

**Screenshots**
![immagine](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/25076545/17ed047f-da04-44e3-9792-5c269cb3db1d)
![immagine](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/25076545/ad0fac7b-3b8f-46ab-aa55-7d832bf09bd3)

**Comment by georgmaisser** [comment]
Thank you very much for pointing out this Bug. 

We had a look and it is fixed. Right now, it's fixed in our MOODLE_401_DEV branch, but we will update main within the next days.

We have an automated test for importing via CSV, but not yet for booking users via CSV. We will fix that as well so this kind of errors won't happen in the future.
