### ISSUE TITLE
Question: where do I find lists of users who booked, online or export?

### ISSUE THREAD

**Issue by VOOM108** [Wunderbyte-GmbH/moodle-mod_booking#448]
8.1.33 in Moodle 4.1 - I can't seem to find information about who booked events anywhere. Neither online like for one option or the whole instance, or as a table to export. Maybe I am blind, but I believe to have looked everywhere. 

In the settings there are options what to show under "Manage Bookings" but I cannot find any menu items that would lead to that view.  

It is the same on two Moodles, where Booking is used. I remember, that the responses used to be visible in the list of options in an earlier version of the plugin.

**Comment by georgmaisser** [comment]
You can click directly on the number of the booked users. in the screenshot the 0/30
<img width="372" alt="Bildschirmfoto 2024-03-23 um 17 14 53" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/7524621/c9485dd1-8e18-4bca-bdc8-d1927e2f68b7">

**Comment by VOOM108** [comment]
Yeah, that was me being blind. I was so being used to find it on the right somewhere... Thanks...
