### ISSUE TITLE
Write a behat test to cover duplication of course along with option

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#458]
Write a behat test to cover duplication of course along with option
There is another new feature, where - when a booking option gets duplicated, the Moodle course will get duplicated too.
This works asynchronously with an adhoc task and there is a setting that has to be turned on first.

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/df211059-c8b3-43c8-8e97-9fc8238cec30)

**Comment by semteacher** [comment]
Course duplication works but option has been duplicated in original course first than course become duplicated with both options. So result is: 2 courses, 4 options: 


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/ba7053e3-95a3-4c83-bb96-378b38541bab)



![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/b5793e8b-cb2d-49f4-adf2-3aeac9c29c27)

**Comment by georgmaisser** [comment]
@bernhard-wunderbyte , you should have a look at this!

**Comment by bernhard-wunderbyte** [comment]
Hi @semteacher - this is correct behavior. When a course with two options gets duplicated, there should be 2 new options in the new course.
