### ISSUE TITLE
Tabellenexport in der Übersicht einer Buchungsaktivität schlägt fehl

### ISSUE THREAD

**Issue by moddleupdaterHS** [Wunderbyte-GmbH/moodle-mod_booking#459]
Sehr geehrte Damen und Herren,

wir verwenden das mod_booking in der Version 8.1.26 (2024022701). In dem betroffenen Moodlekurs wird die Buchungsaktivität mehrfach verwendet. In jeder Buchungsaktivität gibt es mehrere Buchungsmöglichkeiten für Termine.

In der Übersicht der Buchungsaktivität mit mehreren Buchungsmöglichkeiten für Termine  gibt es eine Downloadoption via Excel (Button "Tabelle herunterladen":
![Unbenannt](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/123622895/a1f14f1a-80f3-4193-a3bb-a9b3917803ba)

Wenn man diese ausführt, wird folgende Fehlermeldung angezeigt:
Fehler: mod_booking\singleton_service::get_instance_of_booking_settings_by_cmid(): Argument #1 ($cmid) must be of type int, null given, called in [dirroot]/mod/booking/download.php on line 44

Welche Möglichkeiten haben wir dieses Problem zu beheben?

Viele Grüße

**Comment by dasistwas** [comment]
Wir haben soeben eine neue Version auf moodle.org veröffentlicht. Bitte testen, ob der Fehler noch besteht.

**Comment by moddleupdaterHS** [comment]
Hallo. Der Fehler existiert aktuell nicht mehr. Vielen Dank für die schnelle Reaktion.
