### ISSUE TITLE
When user is deleted in moodle, users on waitinglist remain on waitinglist

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#46]
I tested following scenario:

3 users booked / 3 available places
3 users on waitinglist
I deleted a user who had a regular place, but all three users on the waitinglist remained on the waitinglist. What should have happened is that one waitinglist user moves to "booked users".

It would be better to use the method for deleting a booking instead of en sql query. Deleting a booking with sql query does not seem to be right here.

**Comment by atlet** [comment]
It's a valid point. Function exist, but need to be modified - add parameter force remove user.
