### ISSUE TITLE
Error creating a reservation while trying to assign a date

### ISSUE THREAD

**Issue by beppemandara** [Wunderbyte-GmbH/moodle-mod_booking#470]
**Describe the bug**
A new course is created and the booking module is added, a booking instance is created and when you want to create an edition if, in the dates section, you click on the 'Add date' button the buttons become grey, are no longer clickable and you need to reload the page. An error message appears with the debugger active. See attached images.

**Versions uses**
Moodle version: 4.1.3+ (build 20230609)
Boooking version: 8.2.4

**To Reproduce**
1. Create course
2. Set the start and end date of the course
3. Add the booking module
4. A booking instance is created
5. Choose to create a new edition
6. Click on the 'Add Date' button in the 'Dates' section

**Expected behavior**
You should be able to set the edition date.

**Screenshots**
![IMG_Errore_data_Edizione_No_Debug_2024-04-15](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/25076545/3fdb2b7a-0169-4e78-a420-a2bef2e0d1dc)
![IMG_Errore_data_Edizione_With_Debug_2024-04-15](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/25076545/2b13024c-939d-46cf-bc3e-d7314211a51e)
![IMG_Creazione_Edizione_Senza_Data_2024-04-15](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/25076545/89371a4c-5220-4094-aad2-384c6c0186c7)
![IMG_Errore_Add_Holiday_2024-04-15](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/25076545/f8e2c81a-d33a-406e-8ceb-ab5a535263d8)
![IMG_Errore_Add_Semester_2024-04-15](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/25076545/50af6630-7df2-47bb-b41e-fdbee605b0b1)

**Additional context**
Stack Trace:
------------
ln: 5183
https://tst-www.e-lde.it/lib/requirejs.php/1712847
updateForm

ln: 30038
https://tst-www.e-lde.it/lib/javascript.php/171284
e

ln: 30340
https://tst-www.e-lde.it/lib/javascript.php/171284
Deferred/then/l/</t<

ln: 30549
https://tst-www.e-lde.it/lib/javascript.php/171284
setTimeout handler*Deferred/then/l/<

ln: 28327
https://tst-www.e-lde.it/lib/javascript.php/171284
c

ln: 29072
https://tst-www.e-lde.it/lib/javascript.php/171284
fireWith

ln: 29108
https://tst-www.e-lde.it/lib/javascript.php/171284
fire

ln: 28327
https://tst-www.e-lde.it/lib/javascript.php/171284
c

ln: 29072
https://tst-www.e-lde.it/lib/javascript.php/171284
fireWith

ln: 30310
https://tst-www.e-lde.it/lib/javascript.php/171284
e

ln: 30340
https://tst-www.e-lde.it/lib/javascript.php/171284
Deferred/then/l/</t<

ln: 30549
https://tst-www.e-lde.it/lib/javascript.php/171284
setTimeout handler*Deferred/then/l/<

ln: 28327
https://tst-www.e-lde.it/lib/javascript.php/171284
c

ln: 29072
https://tst-www.e-lde.it/lib/javascript.php/171284
fireWith

ln: 29108
https://tst-www.e-lde.it/lib/javascript.php/171284
fire

ln: 28327
https://tst-www.e-lde.it/lib/javascript.php/171284
c

ln: 29072
https://tst-www.e-lde.it/lib/javascript.php/171284
fireWith

ln: 30973
https://tst-www.e-lde.it/lib/javascript.php/171284
Deferred/</s[t[0]]

ln: 537
https://tst-www.e-lde.it/lib/requirejs.php/1712847
requestSuccess

ln: 28327
https://tst-www.e-lde.it/lib/javascript.php/171284
c

ln: 29072
https://tst-www.e-lde.it/lib/javascript.php/171284
fireWith

ln: 80045
https://tst-www.e-lde.it/lib/javascript.php/171284
l

ln: 82499
https://tst-www.e-lde.it/lib/javascript.php/171284
send/o/<

ln: 82685
https://tst-www.e-lde.it/lib/javascript.php/171284
EventHandlerNonNull*send

ln: 78435
https://tst-www.e-lde.it/lib/javascript.php/171284
ajax

ln: 2626
https://tst-www.e-lde.it/lib/requirejs.php/1712847
call

ln: 3853
https://tst-www.e-lde.it/lib/requirejs.php/1712847
getBody

ln: 4662
https://tst-www.e-lde.it/lib/requirejs.php/1712847
processNoSubmitButton

ln: 3005
https://tst-www.e-lde.it/lib/requirejs.php/1712847
_exports.default</<

ln: 2619
https://tst-www.e-lde.it/lib/requirejs.php/1712847
EventListener.handleEvent*

ln: 396
https://tst-www.e-lde.it/lib/requirejs.php/1712847
_exports.init

@https://tst-www.e-lde.it/mod/booking/editoptions.php?id=1042&optionid&returnto=url&returnurl=https%3A%2F%2Ftst-www.e-lde.it%2Fmod%2Fbooking%2Fview.php%3Fid%3D1042:6182:123
ln: 12861
https://tst-www.e-lde.it/lib/javascript.php/171284
execCb

ln: 6615
https://tst-www.e-lde.it/lib/javascript.php/171284
check

ln: 9363
https://tst-www.e-lde.it/lib/javascript.php/171284
enable

ln: 5721
https://tst-www.e-lde.it/lib/javascript.php/171284
init

ln: 11235
https://tst-www.e-lde.it/lib/javascript.php/171284
newContext/makeRequire/o/<

ln: 14846
https://tst-www.e-lde.it/lib/javascript.php/171284
setTimeout handler*req.nextTick<

ln: 11174
https://tst-www.e-lde.it/lib/javascript.php/171284
o

ln: 14737
https://tst-www.e-lde.it/lib/javascript.php/171284
requirejs

@https://tst-www.e-lde.it/mod/booking/editoptions.php?id=1042&optionid&returnto=url&returnurl=https%3A%2F%2Ftst-www.e-lde.it%2Fmod%2Fbooking%2Fview.php%3Fid%3D1042:6182:64
ln: 12861
https://tst-www.e-lde.it/lib/javascript.php/171284
execCb

ln: 6615
https://tst-www.e-lde.it/lib/javascript.php/171284
check

ln: 9036
https://tst-www.e-lde.it/lib/javascript.php/171284
newContext/enable/</<

ln: 814
https://tst-www.e-lde.it/lib/javascript.php/171284
bind/<

ln: 9498
https://tst-www.e-lde.it/lib/javascript.php/171284
newContext/emit/<

ln: 289
https://tst-www.e-lde.it/lib/javascript.php/171284
each

ln: 9469
https://tst-www.e-lde.it/lib/javascript.php/171284
emit

ln: 7174
https://tst-www.e-lde.it/lib/javascript.php/171284
check

ln: 9036
https://tst-www.e-lde.it/lib/javascript.php/171284
newContext/enable/</<

ln: 814
https://tst-www.e-lde.it/lib/javascript.php/171284
bind/<

ln: 9498
https://tst-www.e-lde.it/lib/javascript.php/171284
newContext/emit/<

ln: 289
https://tst-www.e-lde.it/lib/javascript.php/171284
each

ln: 9469
https://tst-www.e-lde.it/lib/javascript.php/171284
emit

ln: 7174
https://tst-www.e-lde.it/lib/javascript.php/171284
check

ln: 9363
https://tst-www.e-lde.it/lib/javascript.php/171284
enable

ln: 5721
https://tst-www.e-lde.it/lib/javascript.php/171284
init

ln: 4287
https://tst-www.e-lde.it/lib/javascript.php/171284
h

ln: 12091
https://tst-www.e-lde.it/lib/javascript.php/171284
completeLoad

**Comment by georgmaisser** [comment]
Hello, we can't reproduce this, adding dates seems to work fine, also in our automated tests.

You can do the following to help us with finding the error:

- First, here you could turn off javascript caching. we would then see, which script actually throws the error: ../admin/settings.php?section=ajax
- Second, you could have a look in the Chrome Developer Tools -> Network and see, which Ajax calls actually is sent and what the response is. Often in the response we get the error message, if such error occurs:

<img width="1570" alt="Bildschirmfoto 2024-04-16 um 13 11 34" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/7524621/2ecfd183-bc1e-413f-aebe-061bd1066e24">

Additional information which might help us is, if you used booking before, if you recently updated, if this is the first booking option you create with dates or if this has worked before. We see that you also created a semester. Can you also send a screenshot of your semester configuration?

**Comment by beppemandara** [comment]
I made a new installation of the plugin, on another virtual host, starting from scratch and installing version 8.2.4. In this case there were no problems with the dates when creating the editions. I suspect that in previous tests the problems were due to plugin upgrades from version 8.1.26 to version 8.2.3 and from this to version 8.2.4. .
Thank you and have a nice day.
