### ISSUE TITLE
delete_responses_activitycompletion() mehotd cannot work

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#474]
The delete_responses_activitycompletion() method of the booking_opttion class cannot works as described.
It expects to delete users who complete booking completed == 1
```
$users = $DB->get_records('course_modules_completion',
                ['coursemoduleid' => $bookingsettings->completionmodule]);
```
But it calls user_delete_response() method of the same calss which delete only booking answers with 
completed == 0 :

```
$results = $DB->get_records('booking_answers',
                ['userid' => $userid, 'optionid' => $this->optionid, 'completed' => 0]);

        if (count($results) == 0) {
            return false;
        }
```
Should this method is in use not at all?
PS: I [ptoposed ](https://github.com/semteacher/moodle-mod_booking/commit/60710049ff70990c26c0efab3afce4259b1cfa44)possible imporviement for delete_responses_activitycompletion method itself but not changed user_delete_response

**Comment by georgmaisser** [comment]
@semteacher Thanks for finding this issue. We should fix it. the delete_user_response triggers all the events and I am not sure if we want that at this point. But until smbd complains, I think it would be best to still use the method and just add a param to make sure that we ONLY delete the completed answers.
