### ISSUE TITLE
The booking_activitycompletion() function of lib.php cause debug messages on Moodle 4.1 and 4.2

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#475]
The booking_activitycompletion() funcion of lib.php cause debug messages on Moodle 4.1 and 4.2
```
Unexpected debugging() call detected.
Debugging: *_get_completion_state() callback functions such as booking_get_completion_state have been deprecated and should no longer be used. Please implement the custom completion class mod_booking\completion\custom_completion which extends \core_completion\activity_custom_completion.
* line 734 of /lib/completionlib.php: call to debugging()
* line 671 of /lib/completionlib.php: call to completion_info->internal_get_state()
* line 1364 of /mod/booking/lib.php: call to completion_info->update_state()
* line 153 of /mod/booking/tests/booking_option_test.php: call to booking_activitycompletion()
* line 1548 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to mod_booking\booking_option_test->test_delete_responses_activitycompletion()
...
```
This not appears on Moodle 4.3
PS: Error (debug message) confirmed if phpunit being executed on Moodle4.1 VM. However debug message does not visible during manual tests

**Comment by semteacher** [comment]
refactoring has started within https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/a380fa6a155f5b80d9b4c3dca62045ad29bfa615

**Comment by semteacher** [comment]
This issue is also related to #629 and [#474](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/474)

**Comment by semteacher** [comment]
@eynimeni @georgmaisser   answering the following question:
![Image](https://github.com/user-attachments/assets/0c264448-a132-4a39-b167-6bb4b050accb)
I had only started on it and only created a basic class / method which only retrieve current completion state (there https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/a380fa6a155f5b80d9b4c3dca62045ad29bfa615).
I have not altered current logic of  how completion has been granted to user - see my comment there
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/629#issuecomment-2389290745
It is how I can see it working now. 
It is not wrong. But it simply does not match with completion settings under Moodle's activity completion settings.. 

**So: the decision has to be made about what condition must be met in order to consider boking activity to be marked as completed by student.** 

As for me, simplest way to show that current behavior of booking completion is more or less correct - is to change the description of condition: 
- at the comletion settings form
![Image](https://github.com/user-attachments/assets/84c8ac3d-fc1b-4232-b66f-8391a3f68674)
- and in code I have updated: stirng "At least one of the booked options has to be marked as completed" 
- to something like "At least one of the booked options has to be marked as completed **BY BOOKING TEACHER / MANAGER**"
**_It will explicitly demonstrates, that there is no automatic completion now - teacher must takes action._**

**Comment by georgmaisser** [comment]
I think it should be fixed so that the booking option is completed when a user books the required number of booking options. That's how it worked before... is there any reason against it?

**Comment by eynimeni** [comment]
With the decision taken and strings changed as you suggested, would you consider this issue to be solved @semteacher ?

**Comment by semteacher** [comment]
@georgmaisser  I was thinking that current behaviour (check if me description is OK https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/629#issuecomment-2389290745) is the only correct way for booking option to be marked as completed (I mean - only teacher could tetermine if it done). But if simple completion based on booking event (with given number of option) is enough as well - OK, than appropriate fixes have to be made.
An additional fix will be required for this bug https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/629#issuecomment-2389348958 as well

**Comment by eynimeni** [comment]
You were right @semteacher about the behaviour of completion, so I added information about the behaviour to make it more transparent. 
So am I right that only issues raised in https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/629#issuecomment-2389348958 remain? The rest being solved with the better descriptions?

**Comment by semteacher** [comment]
@georgmaisser  It was. I have just pushed fix.
