### ISSUE TITLE
Moodle upgrade to 4.4 failed due to mod_booking requires question/category_class.php

### ISSUE THREAD

**Issue by baltaner** [Wunderbyte-GmbH/moodle-mod_booking#476]
Hi,
I tried to upgrade to Moodle 4.4 - but it fails due to mod_booking requires question/category_class.php

**Versions uses**
Moodle version: 4.4
Boooking version: 8.2.4

**To Reproduce**
1. upgrade Moodle 4.3.4 to Moodle 4.4

In Moodle 4.4 /question/upgrade.txt is noted:
* The following previously deprecated files have been removed and can no longer be used:
  - `question/amd/src/edit_tags.js`
  - `question/amd/src/repository.js`
  - `question/amd/src/selectors.js`
  - `question/category_class.php`
  - `question/category_form.php`
  - `question/export_form.php`
  - `question/import_form.php`
  - `question/move_form.php`
  - `question/previewlib.php`
  - `question/yui/src/preview/js/preview.js`

Thank you

**Comment by baltaner** [comment]
...seems to work when I remove the following line in booking/lib.php:
require_once($CFG->dirroot . '/question/category_class.php');

**Comment by georgmaisser** [comment]
Hi We fixed this 085d440aea0b4c36fe606e17660cd0ce4d56f1be

for the moment, please use MOODLE_401_DEV Branch
