### ISSUE TITLE
Error On Booking view page due to local 'wunderbyte_table'

### ISSUE THREAD

**Issue by nsverma** [Wunderbyte-GmbH/moodle-mod_booking#480]
**Describe the bug**

**Versions uses**
Moodle version: 4.3.4
Booking version: 8.2.4(2024041100)

**To Reproduce**
1. Go to click on add new booking course
2. Click on 'Save and Display'
3. Scroll down to bottom you will see erro
Debug info: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'sql,usermodified,timecreated,timemodified) VALUES('4d99d8fcdf1176da61bc775455...' at line 1
INSERT INTO mdl_local_wunderbyte_table (hash,tablehash,idstring,userid,page,jsonstring,sql,usermodified,timecreated,timemodified) VALUES(?,?,?,?,?,?,?,?,?,?)
[array (
0 => '4d99d8fcdf1176da61bc775455518e7den_filterjson',
1 => '4d99d8fcdf1176da61bc775455518e7d',
2 => 'ba0b59638705eb1587b5852163c861c2',
3 => 0,
4 => 678,
5 => '{"filtersettings":{"id":{"localizedname":"ID","id_wb_checked":1},"teacherobjects":{"jsonattribute":"name","localizedname":"Teachers","wbfilterclass":"local_wunderbyte_table\\\\filters\\\\types\\\\standardfilter","teacherobjects_wb_checked":1},"location":{"localizedname":"Location","wbfilterclass":"local_wunderbyte_table\\\\filters\\\\types\\\\standardfilter","location_wb_checked":1},"institution":{"localizedname":"Institution","wbfilterclass":"local_wunderbyte_table\\\\filters\\\\types\\\\standardfilter","institution_wb_checked":1},"coursestarttime":{"localizedname":"Course time","local_wunderbyte_table\\\\filters\\\\types\\\\datepicker":true,"datepicker":{"Course time":{"checkboxlabel":"Apply Filter","columntimestart":"coursestarttime","columntimeend":"courseendtime","labelstartvalue":"Course time","labelendvalue":"courseendtime","defaultvaluestart":"now","defaultvalueend":"now + 1 year","possibleoperations":["within","overlapboth","overlapstart","overlapend","before","after","flexoverlap"]}},"coursestarttime_wb_checked":1,"wbfilterclass":"local_wunderbyte_table\\\\filters\\\\types\\\\datepicker"},"bookingopeningtime":{"localizedname":"Booking time","local_wunderbyte_table\\\\filters\\\\types\\\\datepicker":true,"datepicker":{"Booking time":{"checkboxlabel":"Apply Filter","columntimestart":"bookingopeningtime","columntimeend":"bookingclosingtime","labelstartvalue":"Booking time","labelendvalue":"bookingclosingtime","defaultvaluestart":"now","defaultvalueend":"now + 1 year","possibleoperations":["within","overlapboth","overlapstart","overlapend","before","after","flexoverlap"]}},"bookingopeningtime_wb_checked":1,"wbfilterclass":"local_wunderbyte_table\\\\filters\\\\types\\\\datepicker"}}}',
6 => 'SELECT
DISTINCT s1.*
FROM (
SELECT DISTINCT bo.id, bo.bookingid, bo.text, bo.maxanswers, bo.maxoverbooking, bo.minanswers, bo.bookingopeningtime, bo.bookingclosingtime, bo.courseid, bo.coursestarttime, bo.courseendtime, bo.enrolmentstatus, bo.description, bo.descriptionformat, bo.limitanswers, bo.timemodified, bo.addtocalendar, bo.calendarid, bo.pollurl, bo.groupid, bo.sent, bo.location, bo.institution, bo.address, bo.pollurlteachers, bo.howmanyusers, bo.pollsend, bo.removeafterminutes, bo.notificationtext, bo.notificationtextformat, bo.disablebookingusers, bo.sent2, bo.sentteachers, bo.beforebookedtext, bo.beforecompletedtext, bo.aftercompletedtext, bo.shorturl, bo.duration, bo.parentid, bo.semesterid, bo.dayofweektime, bo.invisible, bo.annotation, bo.identifier, bo.titleprefix, bo.priceformulaadd, bo.priceformulamultiply, bo.priceformulaoff, bo.dayofweek, bo.availability, bo.status, bo.responsiblecontact, bo.credits, bo.sortorder, bo.json , GROUP_CONCAT(bt1.teacherobject SEPARATOR \', \') as teacherobjects , f.filename FROM {booking_options} bo LEFT JOIN
(
SELECT bt.optionid, CONCAT_WS(\'\', \'{"id":\', u.id, \', "firstname":"\', u.firstname, \'", "lastname":"\', u.lastname, \'", "name":"\', u.lastname, \', \', u.firstname, \'"}\') as teacherobject
FROM {booking_teachers} bt
JOIN {user} u
ON bt.userid = u.id
) bt1
ON bt1.optionid = bo.id LEFT JOIN {files} f
ON f.itemid=bo.id and f.component=:componentname3
AND f.filearea=:bookingoptionimage
AND f.mimetype LIKE \'image%\' GROUP BY bo.id , bo.bookingid , bo.text , bo.maxanswers , bo.maxoverbooking , bo.minanswers , bo.bookingopeningtime , bo.bookingclosingtime , bo.courseid , bo.coursestarttime , bo.courseendtime , bo.enrolmentstatus , bo.description , bo.descriptionformat , bo.limitanswers , bo.timemodified , bo.addtocalendar , bo.calendarid , bo.pollurl , bo.groupid , bo.sent , bo.location , bo.institution , bo.address , bo.pollurlteachers , bo.howmanyusers , bo.pollsend , bo.removeafterminutes , bo.notificationtext , bo.notificationtextformat , bo.disablebookingusers , bo.sent2 , bo.sentteachers , bo.beforebookedtext , bo.beforecompletedtext , bo.aftercompletedtext , bo.shorturl , bo.duration , bo.parentid , bo.semesterid , bo.dayofweektime , bo.invisible , bo.annotation , bo.identifier , bo.titleprefix , bo.priceformulaadd , bo.priceformulamultiply , bo.priceformulaoff , bo.dayofweek , bo.availability , bo.status , bo.responsiblecontact , bo.credits , bo.sortorder , bo.json , f.filename
) s1
WHERE 1=1 AND bookingid = 2
1[]local/wunderbyte_table:canaccess',
7 => '2',
8 => 1714038705,
9 => 1714038705,
)]
Error code: dmlwriteexception

**Expected behavior**

**Screenshots**
![error_on_booking_view_page](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/4129161/bf77e4f5-fec1-4170-a28a-e74757410837)

If applicab
![error_on_booking_view_page](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/4129161/10975c1c-b4f8-420b-b99b-55807af952e1)
le, add screenshots to help explain your problem.

**Additional context**
This issue is happening because of dependency local module 'wunderbyte_table'. Local module 'wunderbyte_table' 's demo page is also not working.

**Comment by georgmaisser** [comment]
Hello, we would strongly advise to go here:

/admin/category.php?category=local_wunderbyte_table

and uncheck all the boxes of the experimental features.

We'll look into it more in depth, but right now, this is not meant for productive environments.

After you unchecked the boxes, please truncate the table local_wunderbyte_table and purge your cache.

We will make all the features productive, but this will take some time.

**Comment by nsverma** [comment]
Thank you so much for quick reply. It is working now after disabling experimental features for plugin local_wunderbyte_table.
