### ISSUE TITLE
Subboking: depedency to shopping_cart and other issues

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#491]
During development on behat test for subboking the following issues has been found:

- [x] 1. Duplication of constants definiotions in bo_subinfo.php (had been already defined in bo_info.php).

 Solved [there](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/e26dcbf3e266248c8ff482aff29cf31e028f103d) but CR required. It might be better to move all constnts into lib.php but will require even more refactoring. @georgmaisser what do you think?

- [x] 2. JS error appears when shopping_cart plugin has not installed. Solution proposed [there](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/f3f77c8e8cae348d41d9e8d2b176916479d9cc87) 

UPD: JS error solved. Hovewer general booking outcome remains incorrect

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/e2a4b18a-e815-46cd-b250-024c4b8367ee)

(booking has not been completed)

- [x] 3. When modal has been opened, but nothig being filled in, than closed (cancelled) with "esc" and page being reloaded - user has been booked (require to reload page): [there](https://screenrec.com/share/4bf3jyO9oC)  

- [x]  4. there are 4 behat test fails after 2.3 have been fixed. 

- Scenario: Configure bookingoption-dependent availability condition - now requires  of page reload after dependent option has been boked. Should not be necessary. 
- Scenario: Configure availability to fill modal agreement form - return "Unfortunately, there was an error when booking Option..." at confirmetion step (like 2 above) 
- Scenario: Configure availability to fill inline agreement form - same case as previous
- Scenario: Booking policy: book option with policy as student - same case as previous
UPD: 3 ;of 4 fixed. 
- [x] 4.1 remainiang issue 
- Scenario: Configure bookingoption-dependent availability condition - now requires  of page reload after dependent option has been boked. Should not be necessary. 

- 

- [ ] 5. Subboking seem does not working properly whn shopping cart had installed. Details are in the [commnet ](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/491#issuecomment-2106200161)

**Comment by semteacher** [comment]
Continuous debugging of 2 reveals even more inconsistences 
1.
- for manual tests load_pre_booking_page() intecepted twice (before modal opened and after "continue" pressed at "add person" subboking model page)
- for behat tests load_pre_booking_page() intecepted once (after "continue" pressed at "add person" subboking model page) 
2. For 1st case (only manual tests) referred values are 

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/b445e6ac-2471-4316-8a74-ac04e79b283a)


3. For 2nd case of interception (both manual and behat) referred values in the load_pre_booking_page() are

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/e61c3869-ad81-4dcf-bc34-0f6b3d5aeffb)


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/bd7ca621-8f88-403c-9264-0815093395cf)

4. During manual test the following artifacts happens
a) 
![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/89e56463-17b8-4da7-bd55-a189acb064eb)

reason unknow, finally option became booked sucesfully
b) 

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/67992768-49c1-4cd3-b1c9-49bb2a06852f)

reason unknow,  finally opton was not booked

**Comment by semteacher** [comment]
2 and 3 solved, [there](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/78d94449b2233c265111ec04f4a174c77b92833b) and [there](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/49c33a6d428bf3d8f99fc23e0bf970dd0be24143)
but 4 emerged

**Comment by semteacher** [comment]
4. Fixed 3 of 4. 
Reamins: - Scenario: Configure bookingoption-dependent availability condition - now requires  of page reload after dependent option has been boked. Should not be necessary. 
upd: fixed 4 of 4

PS: All above issues have to be re-tested for cases
a) prices have been configured (probably with yet another behat or(and) phpunit tests)
b) shopping cart installed and prices have not been configured
c) shopping cart installed and prices have been configured

**Comment by georgmaisser** [comment]
@semteacher We can close this, no?

**Comment by semteacher** [comment]
@georgmaisser Code is complete but this:

> PS: All above issues have to be re-tested for cases
> a) prices have been configured (probably with yet another behat or(and) phpunit tests)
> b) shopping cart installed and prices have not been configured
> c) shopping cart installed and prices have been configured

Have not done yet

**Comment by semteacher** [comment]
Additional tests (manual)
**a) Shopping cart NOT installed, price(s) have been configured ( price category has been set:)** 
- option with NO price: **_value saved in modal but not activated_**

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/a8281363-33d2-461c-99ec-389ebacacf39)
(note default price from category has shown)

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/fdc46dc5-f2f3-43e1-b3e6-12c7944b83a3)

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/7bebafca-2429-4d94-b9b3-d55ae44d99bc)

feature working as if no price.

- option with price being configured - same behavior, **_value saved in modal but not activated_**

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/d64a819e-b30e-4c1b-bcc5-bc8497b655ff)
(note default price from category has NOT being shown)

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/22de3734-5987-43d1-a6ea-617d5c357a7b)

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/2a414e3a-2b38-4d11-aac3-78ca553fe03c)

option inacessible for booking by students because no shoppingcart (looks correct)... 


**b) Shopping cart installed and prices have not been configured**
subboking being configured but not applied at all (except modal confirmation dialog beig called)

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/fd6148c5-9649-44f8-b7db-0bd8693f0182)

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/18d783e4-9d49-439c-8c2c-86cc0003eb11)



**c) shopping cart installed and prices have been configured**

subboking being configured but not applied at all (except modal confirmation dialog beig called)

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/ac82ff44-e7f4-4305-ae3e-2a9678c5a5ea)

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/5a819112-f705-4825-8d27-c0a52bd437c3)

**Comment by semteacher** [comment]
- [x] It looks like that b) and c) above have caused by the workflow in the bookit.js 


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/99542a25-41a2-465c-b33b-adb565a67770)

When shopping_cart is ibstalled, allow_add_item_to_cart() has returned LOCAL_SHOPPING_CART_CARTPARAM_ALREADYBOOKED which is ==5 instaed of ==1 . So load_pre_booking_page not being called and actual subboking has been skipped....   
I am not sure how to fix it properly - alter response from allow_add_item_to_cart() (by adjusting shopping_cart::allow_add_item_to_cart() ) or provide alrenative criteria in JS?

UPD: fixed in https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/0af2ae11192fbedbc1baa783cb632cc176be645f
