### ISSUE TITLE
Crash intall :-(

### ISSUE THREAD

**Issue by jmd87fr** [Wunderbyte-GmbH/moodle-mod_booking#492]
Hi,
I downloaded the .zip from Moodle.org 
Moodle 4.4
PHP 8.1 
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/5038301/b6a024e4-1b41-406e-b70b-71af448cc732)

**Comment by dasistwas** [comment]
Which version did you use? Moodle 4.4 ist not yet tested.

**Comment by jmd87fr** [comment]
4.4 dont work :-(

**Comment by dasistwas** [comment]
please provide the version of the booking module.

**Comment by dasistwas** [comment]
There is the question class included. Not sure if that is still necessary:

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/blob/8c1c1c2e7bf229500885617a82609051b210f03d/lib.php#L30

@eynimeni could you have a look?

**Comment by jmd87fr** [comment]
> please provide the version of the booking module.

8.2.4 (2024041100)

**Comment by georgmaisser** [comment]
This inclusion is seven years old and nobody knows why it's there in the first place. We just take it out and have a look if all the tests are still green, ok?

**Comment by jmd87fr** [comment]
> This inclusion is seven years old and nobody knows why it's there in the first place. We just take it out and have a look if all the tests are still green, ok?

Yes Good :-) I'm waiting with a beer ;-)

**Comment by georgmaisser** [comment]
Here you can see the tests after the commit was pushed: [Note: it's green!]
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/actions/runs/8939653570

When all tests are green, you can install from the corresponding branch:

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tree/MOODLE_401_DEV

**Comment by jmd87fr** [comment]
:( I'm on 4.4
