### ISSUE TITLE
Issues with combinations of settings for "enrolled in cohort" availability condition

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#495]
**1. When limited  booking option has to be hidden:**

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/bd997cb5-ccfe-4d94-98b8-ad893c48c4f1)

1.1 When the "Operatior" filed has been set to "AND"

- [x] a)

>  even if user not enrolled in any cohort - he can see option with message (incorect ) 

**Fixed**. Option is hidden (correct)

b) if user enrolled in one cohort - he cannot not see option (correct)
c) if user enrolled in both cohorts - visible and can be booked (correct)

1.2 When the "Operator" filed has been set to "OR"

- [x] a) 

> even if user not enrolled in any cohort - he can see option with message (incorect ): 

**Fixed**. Option is hidden (correct)

- [x] b) if user enrolled in one cohort - he cannot not see option. (**incorrect**) - option must be visible

- [x] c) if user enrolled in both cohorts - he cannot see option. (**incorrect**) - option must be visible 

**2. When limited booking option could be visible:**

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/f6d8f17b-bcc3-45be-ba84-d2bfc6e3274b)

2.1 When the "Operatior" filed has been set to "AND"
a) if user not enrolled in any cohort - visible but cannot be booked (correct)
b) if user enrolled in one cohort  - visible but cannot be booked (correct)
c) if user enrolled in both cohorts - visible and can be booked (correct)

2.2 When the "Operator" filed has been set to "OR"
a) if user not enrolled in any cohort - visible but cannot be booked (correct)

- [x] b) if user enrolled in one cohort  - visible but cannot be booked (**incorrect**) - must be bookable

- [x] c) if user enrolled in both cohorts - visible but cannot be booked (**incorrect**) - must be bookable

3. Could it be related to return_sql() method? Debugging indicates that is_available() not being called at all if user not enrolled in any of cohorts.

- [x] 3.1 UPD: Upon active usere view list of booking option - return_sql() has been called not in all cases. Hard to debug exact circumstances because of regular breacks like this:

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/122e4443-eff9-4e05-93c9-24c70839a717)

(I would expect debug interception it for 4 user except admin but managed to catch only 2)

- [x] 4. Under automated testing env I cannot set "Hide bookingoption when condition not met" to be unchecked. 

Always "ON" (checked) when option edit page opens
(have tried to solve it as well as improve [there ](https://github.com/semteacher/moodle-mod_booking/commit/bf2d410ccaf0b049bf3128bf73cea9160ebe51c5)but it does not help)
Same feature working properly for maual tests. 
Behavior is tha same for both my texting VMs
The only noticeable difference in behavior on "option edit" page 
- for ONLY manual tests the following error has been shown

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/cc2806d5-7e8a-4616-8d45-8b9722cb9fca)

**Comment by georgmaisser** [comment]
Let's make this systematically:

FOR POSTGRES:

User is enrolled in no cohort:
- [x] At least one cohort works for student with button (display with alert)
- [x] At least one cohort works for student sql (is hidden)
- [x] At least one cohort works for teacher with button (display with alert)
- [x] At least one cohort works for teacher sql (is not hidden) (display with alert)
- [x] Both cohort works for student with button (display with alert)
- [x] Both cohort works for student sql (is hidden)
- [x] Both cohort works for teacher with button (display with alert)
- [x] Both cohort works for teacher sql (display with alert)


User is enrolled in one cohort:
- [x] At least one cohort works for student with button (display)
- [x] At least one cohort works for student sql (display)
- [x] At least one cohort works for teacher with button (display)
- [x] At least one cohort works for teacher sql (display)
- [x] Both cohort works for student with button (display with alert)
- [x] Both cohort works for student sql (is hidden)
- [x] Both cohort works for teacher with button (display with alert)
- [x] Both cohort works for teacher sql (display with alert)

User is enrolled in both cohorts:
- [x] At least one cohort works for student with button (display)
- [x] At least one cohort works for student sql (display)
- [x] At least one cohort works for teacher with button (display)
- [x] At least one cohort works for teacher sql (display)
- [x] Both cohort works for student with button (display)
- [x] Both cohort works for student sql (display)
- [x] Both cohort works for teacher with button (display)
- [x] Both cohort works for teacher sql (display)


FOR MARIADB

Let's make this systematically:

User is enrolled in no cohort:

- [x]  At least one cohort works for student with button (display with alert)
- [x]  At least one cohort works for student sql (is hidden)
- [ ]  At least one cohort works for teacher with button (display with alert)
- [ ]  At least one cohort works for teacher sql (is not hidden) (display with alert)
- [x]  Both cohort works for student with button (display with alert)
- [x]  Both cohort works for student sql (is hidden)
- [ ]  Both cohort works for teacher with button (display with alert)
- [ ]  Both cohort works for teacher sql (display with alert)

User is enrolled in one cohort:

- [x]  At least one cohort works for student with button (display)
- [x]  At least one cohort works for student sql (display)
- [ ]  At least one cohort works for teacher with button (display)
- [ ]  At least one cohort works for teacher sql (display)
- [x]  Both cohort works for student with button (display with alert)
- [x]  Both cohort works for student sql (is hidden)
- [ ]  Both cohort works for teacher with button (display with alert)
- [ ]  Both cohort works for teacher sql (display with alert)

User is enrolled in both cohorts:

- [x]  At least one cohort works for student with button (display)
- [x]  At least one cohort works for student sql (display)
- [ ]  At least one cohort works for teacher with button (display)
- [ ]  At least one cohort works for teacher sql (display)
- [x]  Both cohort works for student with button (display)
- [x]  Both cohort works for student sql (display)
- [ ]  Both cohort works for teacher with button (display)
- [ ]  Both cohort works for teacher sql (display)

**Comment by eynimeni** [comment]
@semteacher 
I fixed 1 & 2 in my earlier commits today and all cases that @georgmaisser pointed out behave as expected in my postgres container. 
is there still a problem with 3 and 4 or is this outdated with the new fixes?

**Comment by semteacher** [comment]
Manual tests: all looks OK.
Automated (behat) test: same issue as in the point 4 above.
Could you try to run the following behat test "Option availability: check users cohort settings" and check if it fails and on which step?

**Comment by georgmaisser** [comment]
Hi Andrii,

The behat test fails at the last check, when you log in as student 1, the user should see the button, but the option is still hidden.

When you look in the behat DB, you see that the returnsql is still set to 1. So the error happens here, it should be 0.

This is done here:

`And I set the field "bo_cond_enrolledincohorts_sqlfiltercheck" to ""`

There is no error, but the value is not written in the db upon save. I tried this

`And I set the field "bo_cond_enrolledincohorts_sqlfiltercheck" to "0"`

No effect. So I tried to use this method:

`And I set the field "Hide bookingoption when condition not met" to "unchecked"`

But there I get an error:
`Origin element is not displayed (Facebook\WebDriver\Exception\MoveTargetOutOfBoundsException)`

So what I did now was to set a breakpoint during behat to see if the information about the unchecked box was properly transmitted. (option_form.php, breakpoint in the process_dynamic_submission method).

There I saw that it was not the case. Actually, the key was not there at all. The reason was, that we used wrongly "checkbox" instead of "advcheckbox" in the form. "checkbox" just omits the key, when the box is not checked! @eynimeni , please mind that, we should NEVER use "checkbox" for that reason, only "advcheckbox".

With these changes, the test passes ok.

**Comment by semteacher** [comment]
@georgmaisser 
I knew difference in return calue of the "chekbox" (do not return nothig) and "advcheckbox". 
But I consider it should not be a problem in relatively simple case - so not only not reported it but even made a fix in favor of further usage of plain "chekbox" control.
What I actually do not understand - that usage of "chekbox" was working properly when I did test manually and was not working at the SAME VM during execution of automated behat test (the only spotted difference in site's behaviour - that JS error I posted in point 4 above). 
Of course emplying "advcheckbox" which explicitly return 0 for uncheked should solve this case. But I am worring about similar things will emerge somewhere else in similar circumstamces. In fact - simple "chekbox" has been widely used in Moodle without issues - so it shoyld not cause any pronblems there too. 
If you will cehck other behat tests I made - there are a lot of steps
And I set "name_of_checkbox" to "" (I meanan - uncheked)
And those are works....

**Comment by georgmaisser** [comment]
I think the reason for failure here is a combination of things. First, there was an error thrown because of accessing key which was not present, but it was caught by the booking_options update routine which routinely catches any errors during update errors, so it did not appear in the behat test. would have been easier otherwise.

I think the reason for difference between behat & manual was, that in behat, it was a (caught) error, while during normal manipulation it's just a warning.

anyways, checkbox is also ok, if we catch the not present key with "?? 0", which I also did in my last commit.

BTW, USI & DEV branch have a few errors. If you have time, please take a look at these.

The failures in unit tests seem to come from this commit 5066815dfbfe3247068f1b1fdb49f70743dc34bc

If you need help solving these, please tell me.

**Comment by semteacher** [comment]
@georgmaisser just pushed MOODLE_401_TESTING. Re-used my commit from testing_feature_sqlfilter. phpunit fixed

**Comment by semteacher** [comment]
Since those commits
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/9241f4df7f3ffc01c1e164a0ec3e2bbf30eb701e
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/d81e1fd8f90436828f7903e16528b0744a0e9ade
- phpunit test working on both pgsql and mysql.

Remaining issues:
- on pgsql - grunt JS error "file is stale..."
- on mysql -    the behat scenario "Option availability: check users cohort settings" still fails. I do not have suitable VM with mysql to perform behat test (existing too slow, only phpunit possible to be executed without timeout errors)

**Comment by semteacher** [comment]
"And" and "OR" conditions works as well as "show/hide" options:
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/80797fafec33aa793f69728ee966a0cb0c29878a 
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/16663291c1333ae8a2331b76c470b8fba0df5055
So feature looks OK.
