### ISSUE TITLE
Student can find bookings of other students just by entering the name in the search form

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#50]
Privacy leak: Student search for other students in the search form and get a list of bookings these students made. The only thing they need to do is searching for the name/lastname in the search form.

**Comment by johnnylupino** [comment]
Hi David,
Looks like this issue is still present

**Comment by dasistwas** [comment]
yes, it is not solved. won't be solved until someone is interested in solving it.

**Comment by bernhard-wunderbyte** [comment]
With Booking 8 this should not be possible anymore. So I close this.
