### ISSUE TITLE
Error during Moodle upgrade - Table "booking_customreport" does not exist Debug

### ISSUE THREAD

**Issue by TheEmpireDigital** [Wunderbyte-GmbH/moodle-mod_booking#506]
**Describe the bug**
During Moodle upgrade process from Moodle 3.10.1 to 4.1.10, I got the following error:

Default exception handler: Table "booking_customreport" does not exist Debug:
Error code: ddltablenotexist
* line 814 of \lib\ddl\database_manager.php: ddl_table_missing_exception thrown
* line 2102 of \mod\booking\db\upgrade.php: call to database_manager->add_index()
* line 934 of \lib\upgradelib.php: call to xmldb_booking_upgrade()
* line 677 of \lib\upgradelib.php: call to upgrade_plugins_modules()
* line 1953 of \lib\upgradelib.php: call to upgrade_plugins()
* line 721 of \admin\index.php:

**Versions uses**
Moodle version: 4.1.10
Boooking version: 8.2.4 (2024041100)

**To Reproduce**
1. Upgrade from Moodle 3.10.1 - 4.1.10

**Expected behavior**
A seamless successful upgrade process.

**Screenshots**
Didn't take one unfortunately.

**Additional context**
<img width="988" alt="Screenshot 2024-05-17 at 14 10 50" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/22657647/dcbfe41c-41e1-4c28-aecd-4197f90e3e73">

I had to jump to the line that was causing the error and moved the if block under `// Conditionally launch create table for booking_customreport.` comment above line `2100`. The reason being that the code was checking if the `course` index exist (line `2101`) on a table that has not been created yet. So I moved the block that was responsible for creating the table above the logic that checks if an index exist before creating it. 

[Update:]
After changing the order of above highlighted 2 code blocks, I ran into another error caused by the module trying to alter `tempateid` column from `booking` table to not allow `NULL` values yet the table had a few rows with `NULL` values and that caused a error. I managed to get past that error by updating booking table and setting `templateid` to `0`.
If this is an actual error I think the module should check if there are any `booking` table rows with NULL value on the `templateid` before updating the column's properties. Below is the second error:
 
![Screenshot 2024-05-17 at 16 44 31](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/22657647/7955fcc7-b630-4a99-a0a9-44ea73b55e42)

That's the workaround I had to do in order to be able to upgrade my Moodle to 4.1

**Comment by georgmaisser** [comment]
Thank you very much, also for delivering the solution with it. We fixed it and it will become part of main ASAP

**Comment by TheEmpireDigital** [comment]
> Thank you very much, also for delivering the solution with it. We fixed it and it will become part of main ASAP

My pleasure! Glad that I could assist.
