### ISSUE TITLE
The send_copy_of_mail booking rule action has stopped to working

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#507]
The send_copy_of_mail booking rule action has stopped to working. 
Related behat teasts 
- Booking rule for: copy to relateduser a custom message sent to users who booked option
- Booking rule for: copy to admin a bulk custom message sent to 3 users who booked option

As result of debugging 2 minor fixes provided but it does nort help.
I failed to determine exact reasons. just, send_copy_of_mail -> execute() has not being called

**Comment by eynimeni** [comment]
fixed with 3804337eb7bb9a6cbfcb1bf50c56c6e7ca8e0728
