### ISSUE TITLE
LMS-125 Nachvollziehbarkeit der Korrespondenz

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-mod_booking#510]
We use the same class as for looking in the log store (lazy wb table in collapsible), just integrate it on report.php

mod_booking\output\eventslist
(See also classes/option/fields/eventslist)

- [x] Add eventslist like in the optionform on report.php
- [x] Filter the eventlist  to only Show all messages sent regarding this particular booking option

**Comment by eynimeni** [comment]
Done with 279c485db530528560a8645d591b2a8c86dbfaa0
