### ISSUE TITLE
Poll URL fields in booking_options are very small

### ISSUE THREAD

**Issue by danbuntu** [Wunderbyte-GmbH/moodle-mod_booking#515]
**Describe the bug**
The pollurl and pollurlteachers are set to varchar(255). This is a very small number. We regularly see users with teams.microsoft.com urls that are push 500 chars or safelink.protection urls that can push 800 chars

**Versions uses**
Moodle version: 4.1
Boooking version: current

**To Reproduce**
Create a booking with a pollurl over 255 chars long such as one from MS teams

**Expected behavior**
I think it might be worth setting the poll urls to varchar(1000)

**Comment by eynimeni** [comment]
Hi @danbuntu 
we propose that you shorten the URLs before the insert.
but to make it even more convenient, we upgraded the db fields in the new version [8.3.6](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.3.6)
Enjoy 😊
