### ISSUE TITLE
Complete Activity, Delete Responses, and Custom Message gives error

### ISSUE THREAD

**Issue by demontech** [Wunderbyte-GmbH/moodle-mod_booking#53]
In the develop code, the sections where you Complete Activity, Delete Responses, and Send Custom Messages gives the following error:

A required parameter (sesskey) was missing.

**Comment by dasistwas** [comment]
could you write the exact steps how to reproduce in an ordered list? which version do you use?

**Comment by atlet** [comment]
Fixed - in my git.

**Comment by dasistwas** [comment]
Great. Thank you.
