### ISSUE TITLE
Test Track Changes Feature

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#535]
I have made a screenrecording explaining the new feature changes that tracks changes in updated bookingoptions.
there is a new placeholder {changes} in the rules that will replace the mailtemplates in the future. 
could you please 
a) have a look at the failing actions ins the branch: track_changes_in_boform
and b) write tests about this new feature

here are the recordings. Let me know if anything is unclear.
https://we.tl/t-Mk88AUK8LF

Behat tests:
- [x] review option editing changes using in-place table
- [x] use rule to email list of changes (via live logs it is only possible to verify the subject but not the body of message)
- [x] on/off deprecated email settings

===========================
phpunit tests
- [x] review option editing changes using event data

**Comment by semteacher** [comment]
Bug: I have changed teacher for option but it does not registerd under "recent changes". Instead this has been added


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/3e6de872-c975-41f8-9088-b5f95f0f7b5f)

**Comment by semteacher** [comment]
@eynimeni  about "Still use legacy mail templates ( booking | uselegacymailtemplates )" feature
It works now significantly differnt than in your video (2nd recording).
With negation of settings there

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/3b6d91d8-5973-48f5-8c15-fffa05076b7c)

I can see "deprecated templates" only plugin setting unchecked

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/29c6bc6e-95d4-4cc7-abf5-a78316470c77)

Moreover I see category and editboxes for messages under booking settings - not under option settings


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/1da736bf-d2ee-48dc-abca-661dac85f8f6)

 This part under option settings always the same 


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/71acdc68-4298-496d-a196-ccd8f6e28191)


Please, verify how and where this has to work

**Comment by semteacher** [comment]
- [x] **fixed**
There is a php 7.4 compatibility issue:


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/9160fd13-6daa-4587-99a5-3e65665353eb)


Despite all my attempts to fix (commit not in "origin" repo)


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/b251f4da-417d-4324-b9a5-6955cc463b6b)


Still got the same error



![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/889081eb-cea3-44d6-8545-4a4ff28e056f)

**Comment by eynimeni** [comment]
> There is a php 7.4 compatibility issue:
> 
> ![Image](https://private-user-images.githubusercontent.com/1571998/339266168-9160fd13-6daa-4587-99a5-3e65665353eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzk3NDcsIm5iZiI6MTcxODI3OTQ0NywicGF0aCI6Ii8xNTcxOTk4LzMzOTI2NjE2OC05MTYwZmQxMy02ZGFhLTQ1ODctOTlhNS0zZTY1NjY1MzUzZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMTE1MDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjAzYmRjNzAyY2MzZjBlM2UzMjIwNDZkNGQzMTVmNDQyZDMzMjc3ZmEzNTRmOWNjZGNjMWMzZTAyMmM2MzEzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cR2fc_vR6vhwNRd6hOVZhDo8arcS38QAG2zEnjtBh0Q)
> 
> Despite all my attempts to fix (commit not in "origin" repo)
> 
> ![Image](https://private-user-images.githubusercontent.com/1571998/339266332-b251f4da-417d-4324-b9a5-6955cc463b6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzk3NDcsIm5iZiI6MTcxODI3OTQ0NywicGF0aCI6Ii8xNTcxOTk4LzMzOTI2NjMzMi1iMjUxZjRkYS00MTdkLTQzMjQtYjlhNS02OTU1Y2M0NjNiNmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMTE1MDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjZjMjY5ZmIwNWE0ZjkwODBkZmZkM2Q1OGViMjA5ZjBmYzg5MTUzOTEwYjQzODM1ZGM4NDA2N2ViYjVkM2Q2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6WAOl8Yh2XXHWIq0YxafELPNsaq4hwxyYhaPLyyLVSc)
> 
> Still got the same error
> 
> ![Image](https://private-user-images.githubusercontent.com/1571998/339272284-889081eb-cea3-44d6-8545-4a4ff28e056f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzk3NDcsIm5iZiI6MTcxODI3OTQ0NywicGF0aCI6Ii8xNTcxOTk4LzMzOTI3MjI4NC04ODkwODFlYi1jZWEzLTQ0ZDYtODU0NS00YTRmZjI4ZTA1NmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMTE1MDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2M0NjBkZTMyOTUyZjAxZWY1ZDkzNTcyZmU3NzdjNzUxZDgzZWFiZGRlN2I5YTdlNjJkMzcwZjI5YzRmM2MyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.i0YJ372bUmoAf-QwLxnCRpGoGV_W4n8Nw6vbbMVNJzc)

yes, I also tried already different ways to fix this. just commited another one. hope it works this time.

**Comment by eynimeni** [comment]
> @eynimeni about "Still use legacy mail templates ( booking | uselegacymailtemplates )" feature It works now significantly differnt than in your video (2nd recording). With negation of settings there
> 
> ![Image](https://private-user-images.githubusercontent.com/1571998/339257242-3b6d91d8-5973-48f5-8c15-fffa05076b7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzk3NDcsIm5iZiI6MTcxODI3OTQ0NywicGF0aCI6Ii8xNTcxOTk4LzMzOTI1NzI0Mi0zYjZkOTFkOC01OTczLTQ4ZjUtOGMxNS1mZmZhMDUwNzZiN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMTE1MDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA3NDkyZTZhYjE1YjY0YzU5MzJlNzgxZGI4ZDU3Y2IyZDQwMjZhOGRkMmNhNWNmMGI4YmY1NGNiNjE1YmRiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PK9JNUoZ9OPDBAWy8npLvYE5lCSkhN2MwnaWxxwl7nI)
> 
> I can see "deprecated templates" only plugin setting unchecked
> 
> ![Image](https://private-user-images.githubusercontent.com/1571998/339256499-29c6bc6e-95d4-4cc7-abf5-a78316470c77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzk3NDcsIm5iZiI6MTcxODI3OTQ0NywicGF0aCI6Ii8xNTcxOTk4LzMzOTI1NjQ5OS0yOWM2YmM2ZS05NWQ0LTRjYzctYWJmNS1hNzgzMTY0NzBjNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMTE1MDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzU5YWE5YjU1OGUyMzdjYWE2YWFlM2YyYzZiZGQxZTU2MmIwOTkzNjRiNDUxMDZmODY1N2MwZjljMjcwMmM0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PcdAmDFaWXCqhh7l2_l0qw1VaHXRgE1YN6nGAeTej4w)
> 
> Moreover I see category and editboxes for messages under booking settings - not under option settings
> 
> ![Image](https://private-user-images.githubusercontent.com/1571998/339259081-1da736bf-d2ee-48dc-abca-661dac85f8f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzk3NDcsIm5iZiI6MTcxODI3OTQ0NywicGF0aCI6Ii8xNTcxOTk4LzMzOTI1OTA4MS0xZGE3MzZiZi1kMmVlLTQ4ZGMtYWJjYS02NjFkYWM4NWY4ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMTE1MDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTI5NjVjNGY2YTVmYWIxMTI2YWI5ZDA4YjFiNDQxYzhhY2RjYTAzYmI3NzFhYmYyMmViNGY0MTBiMjdmMTdlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lZm30qQ_tjIU6YoXnaHrWa2D-bqFhXQvhZIgxcsUGiA)
> 
> This part under option settings always the same
> 
> ![Image](https://private-user-images.githubusercontent.com/1571998/339259693-71acdc68-4298-496d-a196-ccd8f6e28191.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzk3NDcsIm5iZiI6MTcxODI3OTQ0NywicGF0aCI6Ii8xNTcxOTk4LzMzOTI1OTY5My03MWFjZGM2OC00Mjk4LTQ5NmQtYTE5Ni1jY2Q4ZjZlMjgxOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMTE1MDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njc2YjRiNGM0YTVkYTM4NzgzZWQyMmUzZDRlMmQwY2ZlNWVjMjExZTk2ZGFhN2Q3MTYyNDQ3MTcwMjU1NTg1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wlZSYW1XKtxoa0NxSi10ndorgMH2UCYGltUWiuGppds)
> 
> Please, verify how and where this has to work

Yes! Sorry for that. I misunderstood what was deprecated and made the screenrecording with the old version and forgot to give you the update.
Correct behaviour is implemented now.
Find deprecated forms in: 
- Pluginsettings
- Booking Instance settings (new with 9e1877b67020fd561a8a90ff2a5ebd1bc84b7610)
   - only visible when setting in plugin defined
   - pro version is not required anymore
   - information about deprecate status
   - link to booking rules
  
In the settings of a bookinoption NO deprecation warning and display always.

**Comment by semteacher** [comment]
@eynimeni By writing phpunit tests I found number of occurences like this in the list of recorded changes

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/2e36cb9b-0044-4b35-9f31-5d73499dd39d)

I think that change of kind of empty value should not being registered as change.
OR @georgmaisser  - should we standartize defaults between bookig_option::create() and  bookig_option::update() ?

**Comment by semteacher** [comment]
There is strange behavior relate to dates at Github
- local run of test looks like

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/0e555619-dfbe-4c42-843e-d1b689cd376f)

- run of the same test at Githib shows (date was not assigned at option creation)

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/4ea190f1-7395-4d75-a202-f0464f11f56e)

**Comment by semteacher** [comment]
A potential issue with dates processing for changes exist.
At github option dates not being assigned at option creation all the time.
- local run of test_option_changes() test

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/74dd6f45-f388-43a4-9bc1-5b6cb2bcf26b)

- run of test_option_changes() at github

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/e49a3e0c-37c5-465f-adf6-012e95dc58e1)

UPD: additional test run at github with var_dump


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/8957d6b5-00e5-41b1-90e0-650359528607)

**Comment by eynimeni** [comment]
remaining problem see #545

**Comment by semteacher** [comment]
During debugging of phpunit faced the following error when tried to use {changes} placeholder in the email template:
1) mod_booking\rules_test::test_rule_on_teacher_added
Error: Object of class stdClass could not be converted to string

/var/www/html/lib/mustache/src/Mustache/Template.php:66
/var/www/html/lib/outputrenderers.php:208
/var/www/html/mod/booking/classes/output/renderer.php:491
/var/www/html/mod/booking/classes/event/bookingoption_updated.php:83
/var/www/html/mod/booking/classes/placeholders/placeholders/changes.php:84
/var/www/html/mod/booking/classes/placeholders/placeholders_info.php:115
/var/www/html/mod/booking/classes/message_controller.php:327
/var/www/html/mod/booking/classes/message_controller.php:272
/var/www/html/mod/booking/classes/task/send_mail_by_rule_adhoc.php:107
/var/www/html/lib/phpunit/classes/advanced_testcase.php:722
/var/www/html/mod/booking/tests/booking_rules/rules_test.php:147
/var/www/html/lib/phpunit/classes/advanced_testcase.php:81
Error has been raised just at renderring


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/19251c84-c867-4d42-9ef6-9e2f112239f5)


debugger tried to create a file


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/cd9603ec-10c1-4a6f-b2b2-b86d32d94046)


During manual tests no error occurs...

**Comment by semteacher** [comment]
above fixed there
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/422ed09332d7f4eaa4602e17d8542ca598103f4d
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/1f1c57a4b51f12bc98916b2c0f9083c29abb064b
