### ISSUE TITLE
Fehler in "mybookings"-query unter PostgreSQL

### ISSUE THREAD

**Issue by cre-eledia** [Wunderbyte-GmbH/moodle-mod_booking#536]
**Describe the bug**

Im Profil beim Klick auf "My booked Options" erhalte ich untenstehende Meldung. Die Meldung zeigt auf, dass "name" und "text" als Spaltenaliase verwendet wurden.

**Versions uses**
Moodle version: 4.1.10
PostgreSQL version: 13.12
Boooking version: 8.2.4

**Screenshots**
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/136428060/9aa54052-9456-4dea-84dd-6c12aa0f13ab)

**Comment by eynimeni** [comment]
Hi @cre-eledia ! 
Kannst du es bitte mal mit der Booking Version 8.3.7 versuchen, also z.B. main Branch pullen?

**Comment by cre-eledia** [comment]
Danke @eynimeni, ich habs versucht, es klappt leider immer noch nicht.
Allerdings, wurde auch nichts am main gemacht in Bezug auf dieses Problem:

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/blob/main/mybookings.php#L55

**Comment by cre-eledia** [comment]
Es reicht die Spaltenaliase "name" und "text" umzubenennen (oder AS einfuegen) und es laeuft wieder.

**Comment by cre-eledia** [comment]
@eynimeni, wann gibt es den naechsten Release mit dem Fix?
Hab ein paar hunderttausend Leute die daran interessiert sind.

**Comment by eynimeni** [comment]
Ich hab die zusätzlichen AS statements in die heutige v8.4.1 rein genommen. im moodle_401_dev branch. wann die nächste lts kommt, kann ich gerade nicht sagen. 
details können wir auch gern per mail besprechen: info@wunderbyte.at

**Comment by cre-eledia** [comment]
Danke @eynimeni, das ist schon mal gut. Wir ziehen normalerweise die aktuellen Releases automatisch aus moodle.org, weshalb es fuer uns vorteilhaft waere, wenn dort auch der Fix mit drin waere.
