### ISSUE TITLE
Testing connection bookingoption - moodle course

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#538]
We introduced / improved a (pro) feature, the "Automatic creation of Moodle courses" from bookingoptions.
In a bookingoption there is a section "Moodle Courses" where it can be chosen if users of a bookingoption should be enroled into a moodle course. It can also be a moodle course newly created. 
If a course is to be created, the setting config newcoursecategorycfield gives the name of the custom option field of the booking option (in section "other fields"). If there is a value found here, course will be created in a category of this name. If the name doesn't exists yet, the new category is created. 
If a template is selected in the config section, all courses with these tags can be used as templates for the course creation. 

Could you please write tests for scenarios like:
behat tests
 - [x] in configsettings no category selected, bookingoption "create new empty Moodle course", checkbox unchecked -> new empty course created in first category with users of bookingoption enroled
- [x] in configsettings no category selected, bookingoption "create new empty Moodle course", checkbox checked -> new empty course created in first category, users of bookingoption enroled after coursestart
- [x] in configsettings customoptionfield name selected, bookingoption "create new empty Moodle course", in bookingoption other fields for customoptionfield name value given entered for existing category -> new empty course created in category of mentioned name
- [x] in configsettings customoptionfield name selected, bookingoption "create new empty Moodle course", in bookingoption other fields for customoptionfield name value given entered NOT for existing category -> new empty course created in newly created category of mentioned name
- [x]  use course template
... and so on

phpunit tests

- [x]  in configsettings no category selected, bookingoption "create new empty Moodle course", checkbox unchecked -> new empty course created in first category with users of bookingoption enroled

- [x]  in configsettings no category selected, bookingoption "create new empty Moodle course", checkbox checked -> new empty course created in first category, users of bookingoption enroled after coursestart

- [x]  in configsettings customoptionfield name selected, bookingoption "create new empty Moodle course", in bookingoption other fields for customoptionfield name value given entered for existing category -> new empty course created in category of mentioned name

- [x]  in configsettings customoptionfield name selected, bookingoption "create new empty Moodle course", in bookingoption other fields for customoptionfield name value given entered NOT for existing category -> new empty course created in newly created category of mentioned name

- [x]  use course template

**Comment by eynimeni** [comment]
screenrecording here: https://we.tl/t-5xcbHGiJoE

**Comment by semteacher** [comment]
1. @eynimeni Thank you for screen recording.
2. I have already started with simplest case but faced an issue
 - for the simple "connected course"
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/798d677b-1e14-44c4-967e-85b2de6989e7)
- when student has booked it
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/2c319e99-622c-438b-8b78-73f463df3fe0)
- it not become enrolled. Button "goto Moodle course" leads to
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/d527e31b-d7e1-4c90-9429-567a2eaebed3)

Does this feature supposed to be still working?

**Comment by eynimeni** [comment]
I didn't cover it in my recording. did you enable Auto-enrol in you settings?
<img width="358" alt="Screenshot 2024-06-18 at 10 24 51" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/78353570/70eecbe1-382c-4cf3-900e-a08551e053f9">
<img width="1365" alt="Screenshot 2024-06-18 at 10 27 48" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/78353570/9d022a4c-61b3-46d9-97a5-87b1694b376f">

Does the error persist with this setting?

**Comment by semteacher** [comment]
For case of simple commection of existing course (https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/ccf8fdb8ad23bbddc2162c5fc9ae1e953a3de5b9):
- automatic test passed OK
- manual test still fails (all settings as above, booking option in course 1, connected course 2, student has been enrolled in course 1, book option, got confirmation but "go to course" show "You cannot enrol yourself in this course" page), have tried with 2 students... (could it be issue with dev env?)
