### ISSUE TITLE
Confirmation Emails: ical not attached

### ISSUE THREAD

**Issue by johnsto34** [Wunderbyte-GmbH/moodle-mod_booking#54]
We are using Moodle 3.0 and the Diane Selwyn 1.0 version of the Booking plugin. We are not getting confirmation emails for booking onto a course despite the setting being enabled/Yes. Only cancellation emails are being sent. Is there a workaround for this please?

**Comment by dasistwas** [comment]
@johnsto34 Could you provide the exact version number. Format is like 2016071202

**Comment by jamaur** [comment]
I will be out of the office starting  21/07/2016 and will not return until
03/08/2016.

Je vais répondre à votre message quand je reviens.

Pour des enquêtes liées à la zone d'apprentissage en ligne, contactez Jamil
Bhatti (jamil.bhatti@muhc.mcgill.ca ou x34043) ou Saskia Weber

## (saskia.weber@muhc.mcgill.ca ou x71855).

I will respond to your message when I return.

For inquiries related to the eLearning Zone, contact either Jamil Bhatti
(jamil.bhatti@muhc.mcgill.ca or x34043) or Saskia Weber
(saskia.weber@muhc.mcgill.ca or x71855).

**Comment by johnsto34** [comment]
dasistwas: thanks you for getting back to me. Versions are as follows:

Windows Server 2008 R2 (IIS 7.5)
MySQL
PHP 5.5
Moodle 3.0.5
Booking - Diane Selwyn 1.0 (2016042500)

**Comment by dasistwas** [comment]
Please upgrade to the latest version 2016071202. This is that latest one available on moodle.org. These are known issues that have been fixed in this version.

Kind regards
David

**Comment by johnsto34** [comment]
Using the new version now (2016071202). We are now not getting any emails but needed to set cron.php to run every minute to then send emails. Is this the correct setup? One more thing. ical events are now not being attached to emails even with the setting on in the plugin. Has this feature been removed?

**Comment by dasistwas** [comment]
@johnsto34 In the new version, sending mails is now done with an adhoc cron task https://docs.moodle.org/dev/Task_API#Adhoc_tasks
That means: The mail will be sent when cron job is running the next time. If it is important for you to send it within a minute, then running the cron job every minute is OK. But I would recommend to send it all five minutes, if mail delivering should be as fast as possible. The reason for this was: I can subscribe multiple users at once to a booking option. Sending e-mails would enormously delay that process.
Concerning iCal: It might be possible that there is a problem with the adhoc task, when iCal is attached. But I did not verify that yet. If you want any changes within a certain timeframe you can always contract me. There is a lot to do for this plugin, for example automated testing to be sure, that everything works as expected. But all this needs some funding, as I do have other things to do in my free time.

**Comment by dasistwas** [comment]
fixed in dc27a366f3c30d41022e293cc1c6eb611055ce3c

**Comment by johnsto34** [comment]
Oh fantastic. Thank you very much.
