### ISSUE TITLE
mod_booking 8.4.3: Legacy mail templates are deprecated - but Booking_Rules are PRO-functions

### ISSUE THREAD

**Issue by baltaner** [Wunderbyte-GmbH/moodle-mod_booking#547]
Hi,
after installing mod_booking 8.4.3 I got following message:

This function is deprecated and will be removed in the near future. We strongly encourage you to migrate your templates & settings to [Booking Rules](webserver/moodle/mod/booking/edit_rules.php). Be careful: If you uncheck this box, your email templates in your booking-instances won't be shown and used anymore.

In mod/booking/edit_rules.php:
Booking: Rules PRO
You need a Booking PRO license if you want to use this feature. [Contact Wunderbyte](https://wunderbyte.at/en/contact) if you want to buy a PRO license.

**Versions uses**
Moodle version: 4.4.1+ (Build: 20240614) 
Boooking version: 8.4.3

Is this a bug - or should we need to pay for emal-notifications?

Thanks
Bertold

**Comment by dasistwas** [comment]
As for now it is only deprecated. Basic notification should be still available, but rules are way more powerful.

**Comment by baltaner** [comment]
Thank you for this information.
Thank you for this great module!

Bertold
