### ISSUE TITLE
Sign-in sheet header logo

### ISSUE THREAD

**Issue by PavelK24** [Wunderbyte-GmbH/moodle-mod_booking#550]
**Describe the bug**
Sign-in sheet header logo missing (footer logo runs ok)

**Versions uses**
Moodle version: 4.1.9 and 4.3.3
Boooking version: 8.2.4 (2024041100)

**To Reproduce**

1. set Logo in header and footer to display on the sign-in sheet 

1. Go to Booking module in course
2. Click on exist booking session with minimal one booked user
3. Download sign-in sheet
4. PDF was generated but without header logo

**Expected behavior**
Generate PDF with logo in header and footer

**Comment by dasistwas** [comment]
Thank you for submitting the problem. We will have a look at it.

**Comment by georgmaisser** [comment]
I think we can close this.
