### ISSUE TITLE
Question on "feature-berta" and courseid and booking rules

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#551]
Question was inspiried by message

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/7e4a2070-d74f-4495-8201-206e622b77f4)

1. At this moment most of tests on rules had failed. 
1.1 Some of them because of typo changes in the log text. So could be fixed relatively easy (will be done soon)
1.2 But it looks like an additional messages appears... 
For example for the Scenario: Booking option: send custom reminder mail to participant 

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/f709c94e-f568-42b2-9e00-1848ba5124b1)

(2 such messages for each student)

Another example is the Scenario: Booking rule for: copy to relateduser a custom message sent to users who booked option
- the following messages have been seent

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/4927da83-633d-4246-9515-aa2b215c840f)

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/65c9c7a3-209b-484b-ab2c-ad7af0f0a7f0)

(different IDs because of 2 test passes have been used to take screens in this case )

Similar case for the most of the rules tests... 
**Question**. Does it is correct? (Sorry I amslightly lost in amount of messages has to be sent)

2, Clarification. If I clearly understand  "if courseif present - only teacher has been subscribed to option" so students are not? and they should not receive any messages? But in case of rules - it has to be an "override"? Or I do not understand current logick of subscription / messaging? Please, clarify/explain correct logick of this.
 
3.  Important general qurestion
For a long time Behat tests contains declaration of options like 

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/4baea05a-0ab1-40dc-92a1-346991e486a4)

Moreover, "course" was a mandatory element of declaration of options.
Hovewer, relatively recently to achieve a course connection like 

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/f0b86e3a-edf1-4061-9013-c92183da83a1)

It will be necessary to have declaration of option like 

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/eea2a4bc-f961-4115-91ab-d9b6ceb73c41)

But after dealing with course connection task and because of top message and be re-checking option settings of old oprions in the DB of dev I use - I conclude that it rather more common case when option does not have a connected course. Am I correct? It was not pointed nor discussed before but it seems like very important matter?   
So 
- should I remove "course" from required parameters in "create_option" generator method (of course it possible and working)?
- how I have to update all existing tests - keep courses, or remove... 
- and, actially, where (except "course connection" tests) presence of connected course is critical? 
(Sorry , maybe some of those questions have to be asked long in the past but I come to it only now)

**Comment by semteacher** [comment]
An additional questions related to points 1 and 2 above:
**Behat Scenario: Booking rules: create booking rule for teacher substituing event**
Expexting email to admin being semt

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/f6c5abee-d438-4148-9b49-7e31a105e637)

`And I should see "An e-mail with subject 'teacher subst' has been sent to user with id: '2'"`

But only the following email has been sent

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/d5e224cd-9955-465b-b06c-2f5c8068d76a)

**I have to know is it expected canges in behavior now? (But it will means that booking rules no longer applicable?)**

The same case with **behat Scenario: Booking rules: create booking rule for option cancellation event and notify students**
Expecting message being sent to students


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/371cc1c2-1784-4afd-80ba-391e248271c5)

but actually in the logs I see a message(s) had been sent from students to teacher

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/e8a31aa2-89a3-4fd6-bbe0-23750ca52ddb)

(Or am I wrong?)

**Next: behat Scenario: Booking rules: create booking rule for teacher removal event and notify other teachers**

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/0f4955fb-5dda-4560-beaf-f01aa4c00ffb)

there are 3 teachers initially: teacher2, teacher1, admin.
Teacher 2 has been removed.

Previously I expected and had seen an atleast the email to remaining teacher (admin)

`And I should see "An e-mail with subject 'teacher removed' has been sent to user with id: '2'"`

Now I see 3 emails:
- from teacher1 to admin

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/ee79f76d-beac-49a7-8577-dddffe97570c)

- from teacher1 to teacher1 (?)

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/d5fe3e4c-92f8-4953-9f25-97382d16b6eb)

- from teacher2 (he was removed?) to teacher1

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/a17342e7-0a37-4d7f-9690-b0344af941ee)

**_The last one rule on the "401_testing" branch looks like this:_**
- email from teacher1 to admin (as a teacher) 

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/f1d86a25-5912-4e10-93e2-4148237f12c8)

- email from teacher1 to teacher1

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/fa1b1577-5ef2-4b48-9baf-a39dfd974365)

- email from teacher1 to (ex)teacher2 (such a direction at least make sense as for me)


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/38cfa39d-f3d2-4c56-bb65-9f4980457ee1)

**Comment by georgmaisser** [comment]
Hi, I didn't do it on my system now, but a few ground rules:

Actually, I have the impression that as for your first tests, everything ist fine. When you have a rule, which sends a mail when a custom mail is sent, you would expect two messages, when one is sent. First the initial message, then the one from the rule.

As for the second point:
There was a change indeed. Please be aware of the following points.

- The course is optional. We have booking options with or without courses, this really is just a choice.
- When there is a course, teachers should be inscribed immediately, students should be inscribed on booking the option.
- If students are already booked, when the course is added, they should be added to the new course. But if this does not work (I am not sure), it would still be ok.
- We added further options in the booking option form: Before, -1 meant that you wanted to create a new course. Now, -1 does not exist anymore. We have the second setting, where we can choose one of these options A) no course, B) existing course C) new Course D) course from template course.

In all cases except A) the courseid of the connected course will be stored. On reloading the booking option, the selector will be set on Option B), as the newly created course from Option C & D will then just be an existing course.

**Comment by georgmaisser** [comment]
Back to the messages:

I guess we need to be careful not to create a loop, where the reaction to a sent message will trigger another reaction to the newly sent message.

I think the intended logic is clear.

- When there is no booking rule, a custom message of a teacher should just be sent to all students. No further reaction.

- when there is a rule, where smb is notified of custom messages being sent, this notification should be triggered exactly once for every message sent. If a teacher sends to ten students, the notification of the custom message should also be sent ten times.

**Comment by semteacher** [comment]
- [x]  Just to keep note: noticed from "Duplicate booking option with multiple customized settings"  that under "feature berta" branch teacher now can be assigned to option ONLY if course is assigned which probably is an incorrect behavior.
UPD. Incorrect behavior, fixed there https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/3f001db6b12b6db6c73dbbbd2b884b5543c88b0e

**Comment by semteacher** [comment]
- [x] Investigation of 4 failed "courseconnected" behat tests shown that:

- booking has been succesfull but instead of "Booked"+"Go to course" buttons something new (only link to course?) has to be shown:

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/66b67907-b6e6-4098-8c67-89d692021ee6)

- but it looks like some uncompleted development related to this


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/4036930c-8c67-4fe4-8a0d-87e07c5a6dc3)

**Comment by semteacher** [comment]
- [x] Failed behat Scenario: Booking rules: create booking rule for option update and notify teachers about it

Option being updated without errors. But it look like that "bookingoption_updated" even not being fired at all. Cannot intercept nothing with the following breakpoints:


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/d4abbf13-7aa4-4f38-bf7e-024337266bcf)

 
UPD. Fixed there https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/3f001db6b12b6db6c73dbbbd2b884b5543c88b0e along with Teacher/course dependency

**Comment by georgmaisser** [comment]
The "Start" button is intended behaviour, why do you think it's not? You see in the code the "get_config" call and it's linked to this setting. If you take away the checkbox, it would be the old behaviour again.

<img width="841" alt="Bildschirmfoto 2024-06-30 um 09 21 34" src="https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/7524621/3d710545-761f-494e-913e-fbecb127fa50">

**Comment by georgmaisser** [comment]
> Failed behat Scenario: Booking rules: create booking rule for option update and notify teachers about it
> Option being updated without errors. But it look like that "bookingoption_updated" even not being fired at all. Cannot intercept nothing with the following breakpoints:

Please describe the problem again, I don't understand what you mean.

**Comment by semteacher** [comment]
> The "Start" button is intended behaviour, why do you think it's not? You see in the code the "get_config" call and it's linked to this setting. If you take away the checkbox, it would be the old behaviour again.
> 
> <img alt="Bildschirmfoto 2024-06-30 um 09 21 34" width="841" src="https://private-user-images.githubusercontent.com/7524621/344449800-3d710545-761f-494e-913e-fbecb127fa50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzI1NTAsIm5iZiI6MTcxOTczMjI1MCwicGF0aCI6Ii83NTI0NjIxLzM0NDQ0OTgwMC0zZDcxMDU0NS03NjFmLTQ5NGUtOTEzZS1mYmVjYjEyN2ZhNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMDcyNDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWVkNDlhNjgxMjAxNjVmY2MxNGZkM2Q1MjMwYjVkODVhODZmZjEwNTk1NDg4OWRmMzAzYThlNzhjMGRiNTExNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._C3uSUEa9RoKbePqvfV5MnrBIVui1GCOVmQrbvtRw-A">

Have fixed ENG string and adjusted 4 behat tests to support it. One of them modified to support new approach ("linktomoodlecourseonbookedbutton" is "ON"  so only "Start" link to the connected course being shown) other 3 still set to old way ("linktomoodlecourseonbookedbutton" is "OFF", so "Booked" label and "Go to course" link to the connected course being shown)

**Comment by semteacher** [comment]
> > Failed behat Scenario: Booking rules: create booking rule for option update and notify teachers about it
> > Option being updated without errors. But it look like that "bookingoption_updated" even not being fired at all. Cannot intercept nothing with the following breakpoints:
> 
> Please describe the problem again, I don't understand what you mean.

Fixed there https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/3f001db6b12b6db6c73dbbbd2b884b5543c88b0e along with Teacher/course dependency
