### ISSUE TITLE
The "My booked options" report is not applying the multilingual filters "Contenu Multilingue (v2)"

### ISSUE THREAD

**Issue by jrojas-garrido** [Wunderbyte-GmbH/moodle-mod_booking#552]
**Describe the bug**
The "My booked options" report is not applying the multilingual filters "Contenu Multilingue (v2)".  {mlang} opening and closing labels are shown but no translation is made.

**Versions uses**
Moodle version: 4.1.11
Boooking version: 8.2.4 (2024041100)

**To Reproduce**
1. Go to 'Go to the profile of a user who has bookings in booking modules that contain the {mlang} tags in the name of the booking options. /user/profile.php'
2. Click on 'My booked options or /mod/booking/mybookings.php'
3. On the table My booked options {mlang} opening and closing labels are shown but no translation is made.

**Expected behavior**
For a content like this ...
_[Excel 2013/2016](https://mdl41.ena.qa.muhc.mcgill.ca/mod/booking/view.php?id=56203) ([{mlang en}Computer Training Program - Winter 2022{mlang}{mlang fr_ca}Programme de formation bureautique - Hiver 2022{mlang}](https://mdl41.ena.qa.muhc.mcgill.ca/course/view.php?id=11275))_
... when consulting in english language you should see the content in english and if you consult in french language the text in fr. 

**Screenshots**

![mlang](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/3809902/29b12ff6-b844-4c29-973f-dab7de963fb2)

**Comment by georgmaisser** [comment]
Thank you for reporting this. We have fixed it in a dev branch and it will become move to main shortly.
