### ISSUE TITLE
Exception Moodle 4.4 category_class.php

### ISSUE THREAD

**Issue by LukeDuffy98** [Wunderbyte-GmbH/moodle-mod_booking#560]
**Describe the bug**
After installing the plugin an error occurs and no Moodle access is possible : 

Exception - Failed opening required '[dirroot]/question/category_class.php' (include_path='[dirroot]/lib/pear:.:/opt/bitnami/php/lib/php')

**Versions uses**
Moodle version: 4.4
Booking version: 8.2.4 (2024041100)

**To Reproduce**
1. Instal Plugin
2. Pass checks
3. System fails

**Expected behavior**

**Screenshots**

![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/31847926/aee5c2fb-efa3-4df1-8845-4af8649766f1)

**Additional context**
My version of Moodle is 4.4 based on Bitnami and so I understand a supported version is not out. This may be helpful for future development and also if anyone else has an issue

This command creates an empty file and places in the target location
touch /opt/bitnami/moodle/question/category_class.php

After that all seems OK for now, but not sure what I may encounter

**Comment by georgmaisser** [comment]
Hello, thank you for reporting that. We have fixed that quite a while ago ( 085d440aea0b4c36fe606e17660cd0ce4d56f1be ), but we have not yet updated the stable version. See also #492 

This is a quite recent development branch which should work well also with 4.4.

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.4.5

You might want to give it a try.
