### ISSUE TITLE
It is not possible to add functions to an external webservice

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#563]
**Describe the bug**
In Moodle Site Admin create an external web service and then try to add a function. 

**Versions uses**
Moodle version: 4.1.11
Boooking version: 8.3.7

**To Reproduce**
1. Go to Site admin -> Server -> Webservices
2. Add external service, for allowed users only
3. Try to add a function to the service

Exception - Class 'core_external\external_multiple_structure' not found

[More information about this error](http://docs.moodle.org/401/en/error/moodle/generalexceptionmessage)
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 65 of /mod/booking/classes/external/get_submission_mobile.php: Error thrown
    line 123 of /lib/externallib.php: call to mod_booking\external\get_submission_mobile::execute_parameters()
    line 199 of /admin/webservice/forms.php: call to external_api::external_function_info()
    line 214 of /lib/formslib.php: call to external_service_functions_form->definition()
    line 63 of /admin/webservice/service_functions.php: call to moodleform->__construct()

**Expected behavior**
The error should not appear.

**Comment by dasistwas** [comment]
@eynimeni please, this is an urgent matter. Could you fix it ASAP?

**Comment by eynimeni** [comment]
Hello, thank you for reporting that. We have fixed that quite a while ago, but we have not yet updated the stable version. We will update it soon to make sure, this bugfix is included.

This is a quite recent development branch which should work well also with 4.4.

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.4.5

You might want to give it a try.
