### ISSUE TITLE
instal bug

### ISSUE THREAD

**Issue by jmd87fr** [Wunderbyte-GmbH/moodle-mod_booking#574]
**Describe the bug**
I try to install the pugins by downloading 

**Versions uses**
Moodle version:  4.4.1
Boooking version:  last 

![image](https://github.com/user-attachments/assets/dc9de2a8-c2a6-4b67-8017-8162236f0400)

**Screenshots**
If applicable, add screenshots to help explain your problem.  YES

**Comment by dasistwas** [comment]
last is not a valid booking version. that issue has been resolved in the latest version. You are using a wrong branch. Try this one: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tree/USI
