### ISSUE TITLE
Problems with updating content (editing titles, displaying my bookings)

### ISSUE THREAD

**Issue by AntonT76** [Wunderbyte-GmbH/moodle-mod_booking#578]
Dear Wunderbyte-Team,

I am currently testing the booking plugin 8.2.4 (2024041100) on Moodle 4.1.11+ LTS and have encountered the following problems:

**Tab "My bookings" is not updated**

- If a user completes a booking, it should appear under "My bookings".
- but this booking is not displayed ("No data found")
- only when you refresh the browser (e.g. by pressing F5) the booking will be displayed
- the booking disappears again when you go to the tab "My bookings"

**Editing the title of a booking does not seem to be implemented**
- If you create a booking and change the title in the course overview (e.g. from "Trainings" to "Trainings Summer 2024") and press "Enter", the change does not appear to be made
- However, if you go to the settings of the activity, the change is displayed there
- Here too, the title only changes when you refresh the browser

Browser: Edge 1.26 64bit
OS: Windows 10 22H2 (build 19045.4529)
Moodle 4.1.11+ LTS (Theme: Boost Union v4.1-r28)

br, Anton

**Comment by dasistwas** [comment]
Could you verify if the problem still persists with the latest version 8.4.7:
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tags

**Comment by georgmaisser** [comment]
The issue with "my bookings" was fixed here d58315d3ec3363cee6a7a902ab52798a291dbd49

Please test again with the latest version, as David proposed.

**Comment by AntonT76** [comment]
Hi @georgmaisser , I did some tests with your fixed version and it works.
br, Anton
