### ISSUE TITLE
Booking cannot be cancelled

### ISSUE THREAD

**Issue by AntonT76** [Wunderbyte-GmbH/moodle-mod_booking#579]
Dear Wunderbyte-Team,

I am currently testing the booking plugin 8.2.4 (2024041100) on Moodle 4.1.11+ and have encountered the following problem: It is not possible for a user to cancel a booking

As a teacher I set booking to "Cancelling is only possible until certain date: DD-MM-YYYY", but for a user there is no button for cancelling.

Browser: Edge 1.26 64bit
OS: Windows 10 22H2 (build 19045.4529)
Moodle 4.1.11+ LTS (Theme: Boost Union v4.1-r28)

br, Anton

**Comment by dasistwas** [comment]
Could you verify if the problem persists in the latest version:
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tags

**Comment by AntonT76** [comment]
Hi @dasistwas ,

actually I could not do an update on this Moodle Version 4.1.11+, because we do not have direct access to it. But we have an other developer Moodle (also 4.1.11+, Booking 8.2.4) and there was an other issue:

With the "old" Booking (8.2.4) and also your beta booking version (8.4.7) I'm not able to config a new booking option. I got the error message: 

_Fehler: Undefined constant "mod_booking\option\fields\MOD_BOOKING_OPTION_FIELD_SHORTURL"_

We have provided our developer Moodle with sub-URLs (eg: https://mymoodle.com/devmo1, https://mymoodle.com/devmo2, https://mymoodle.com/devmo3, ... Maybe it has something to do with that?

br, Anton

**Comment by dasistwas** [comment]
What PHP version are you using?

**Comment by dasistwas** [comment]
Concerning users can't cancel: You have to allow that in booking instance settings. We are running automated tests against that feature so it should work. See screenshot: Activate the last option in advanced settings:
![Screenshot 2024-07-18 at 10-15-01 Editing Booking Wunderbyte](https://github.com/user-attachments/assets/07fd6186-6fd3-4280-a42e-61c997d499fe)

**Comment by AntonT76** [comment]
> What PHP version are you using?

we are using PHP Version 8.1.29

**Comment by AntonT76** [comment]
> Concerning users can't cancel: You have to allow that in booking instance settings. We are running automated tests against that feature so it should work. See screenshot: Activate the last option in advanced settings: ![Screenshot 2024-07-18 at 10-15-01 Editing Booking Wunderbyte](https://private-user-images.githubusercontent.com/1620975/349874652-07fd6186-6fd3-4280-a42e-61c997d499fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTgyOTgsIm5iZiI6MTcyMTI5Nzk5OCwicGF0aCI6Ii8xNjIwOTc1LzM0OTg3NDY1Mi0wN2ZkNjE4Ni02ZmQzLTQyODAtYTQyZS02MWM5OTdkNDk5ZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MThUMTAxOTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNmNzYyYmRmZWNlOTNlZTJkOWI4ODI4MjM5MzA2ZmNmYTQ0ZWYwZThhZGIzYTJmNTAwNzk4MzY5ZmMzZDdjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.seOB1mEC9e3oXepYn3M7qnKhU4HeaMQsUFpA4ALOHU8)

ok, thank you and sorry for the confusion. I didn't see this feature - now canceling is possible.
br, Anton

**Comment by dasistwas** [comment]
> _Fehler: Undefined constant "mod_booking\option\fields\MOD_BOOKING_OPTION_FIELD_SHORTURL"_

Hi, we think there is a problem with your $CFG->dirroot. We can't reproduce the problem and all automated tests, that are actually doing configurtation of booking options constantly are passing.

**Comment by AntonT76** [comment]
Hi, thank you, I will check the dirroot options. br Anton
