### ISSUE TITLE
Moodle 4.4 version?

### ISSUE THREAD

**Issue by turf212** [Wunderbyte-GmbH/moodle-mod_booking#580]
**Describe the bug**
Trying to upgrade to Moodle 4.4 and the change in core files is causing a required library open failure.

**Versions uses**
Moodle version: 4.4
Boooking version: 

**To Reproduce**
Install Moodle 4.4
Install latest mod booking plugin

`Exception - Failed opening required '[dirroot]/question/category_class.php' (include_path='[dirroot]/lib/pear:.:/usr/share/php')
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 30 of /mod/booking/lib.php: Error thrown
line 932 of /lib/classes/component.php: call to include_once()
line 7552 of /lib/moodlelib.php: call to core_component::get_plugin_list_with_file()
line 855 of /lib/setup.php: call to get_plugins_with_function()
line 46 of /config.php: call to require_once()
line 94 of /admin/index.php: call to require()`

**Additional context**

The question bank code has been moved to question/bank/ and the class files are now under this. Not sure which one you would need for it but it looks like there will need to be a separate 4.4+ version for the plugin.

`public_html/question# find . -name \*category\*
./bank/managecategories/templates/category_condition.mustache
./bank/managecategories/templates/choose_category.mustache
./bank/managecategories/templates/category_condition_advanced.mustache
./bank/managecategories/classes/question_category_object.php
./bank/managecategories/classes/form/question_category_edit_form.php
./bank/managecategories/classes/question_category_list_item.php
./bank/managecategories/classes/question_category_list.php
./bank/managecategories/classes/category_condition.php
./bank/managecategories/tests/question_category_object_test.php
./bank/managecategories/category.php
./format/xml/tests/fixtures/export_category.xml
./format/xml/tests/fixtures/category_with_description.xml
./format/gift/tests/fixtures/questions_in_category.gift.txt
`

**Comment by eynimeni** [comment]
Could you please try if it works if you upgrade your booking version to 8.4.7 ?

**Comment by gemguardian** [comment]
@eynimeni I tried it with the M4.3 version that is available on Moode.org and got the same error on a clean installation

no error with the 8.4.7 version in https://github.com/Wunderbyte-GmbH/moodle-mod_booking

**Comment by dasistwas** [comment]
We are working on getting everything green for m4.4. But I think next week we will release a 4.4 version
