### ISSUE TITLE
Präfix in Buchungsoption doppelt sichtbar 

### ISSUE THREAD

**Issue by woi-srh** [Wunderbyte-GmbH/moodle-mod_booking#585]
**Describe the bug**
Der Präfix der Buchungsoption wird in der Einzelansicht der Buchungsoption doppelt angezeigt. Z.B. Hier lautet der Präfix "MONTAG": 
![grafik](https://github.com/user-attachments/assets/694e0d00-f82c-44f4-b1a3-cd5a03893ac2)

**Versions uses**
Moodle version: 4.3
Boooking version: 8.2.4

**To Reproduce**
Eine Buchungsoption mit Präfix anmelden. Auf die Buchungsoption klicken. Im Titel wird der Präfix 2x hintereinander angezeigt.

**Expected behavior**
Präfix nur einmal sichtbar.

**Screenshots**
Siehe oben

**Additional context**
-

**Comment by eynimeni** [comment]
Vielen Dank für den aufmerksamen Hinweis @woi-srh , wir haben den Fehler nun behoben, ab Version 8.6.1. wird der Fix dann enthalten sein.
