### ISSUE TITLE
Stornieren-Button trotz korrekter Grundeinstellungen nicht verfügbar

### ISSUE THREAD

**Issue by woi-srh** [Wunderbyte-GmbH/moodle-mod_booking#586]
**Describe the bug**
Stornieren-Button trotz der korrekten Grundeinstellungen nicht verfügbar. Workaround möglich (siehe unten).

**Versions uses**
Moodle version: 4.3
Booking version: 8.2.4

**To Reproduce**
Wenn in den Buchungsinstanz-Einstellungen Folgendes eingestellt ist, gibt es _keine Möglichkeit zum Stornieren_.
![grafik](https://github.com/user-attachments/assets/b2cead3b-d092-4ea2-a49e-fe6c38b56458)

Wenn der Haken gesetzt wird (ohne die Tage spezifischer zu definieren), ist der Stornieren-Button verfügbar.
![grafik](https://github.com/user-attachments/assets/a2cf2573-b81d-4d9d-9ae6-e8987a25dd62)

**Expected behavior**
Haken nicht gesetzt --> Stornieren immer verfügbar.

**Screenshots**
siehe oben

**Additional context**

**Comment by dasistwas** [comment]
Please checkout this solution: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/579

**Comment by woi-srh** [comment]
@dasistwas 

Thank you. I checked out the suggested solution but the settings shown do not seem to be available to me: 

![grafik](https://github.com/user-attachments/assets/5ec19675-44f7-4365-b8ed-3d0991b39560)

I can only (and have to) tick the box to allow users cancellation after the booking option has begun.

This seems quite misleading to me, even though it works in the end. :)

**Comment by dasistwas** [comment]
We will adapt the German language string. It is incorrect and misleading.

**Comment by woi-srh** [comment]
Perfect. Thank you for reacting so quickly!

**Comment by woi-srh** [comment]
Unfortunately, this issue seems to persist in the German string. The cancel button only appears for users when I select define "Stornodatum relativ zu Beginn der Buchungsoption"

![grafik](https://github.com/user-attachments/assets/d83c5243-1f11-41d1-b930-f04c2158b4d9)
