### ISSUE TITLE
Adding custom user fields to email body or subject

### ISSUE THREAD

**Issue by johnsto34** [Wunderbyte-GmbH/moodle-mod_booking#59]
Is there any way to include user fields such as email address or a custom user field into the body of emails sent to the user?

**Comment by dasistwas** [comment]
Hi, available tags are:
    {status}
    {participant}
    {title}
    {duration}
    {starttime}
    {endtime}
    {startdate}
    {enddate}
    {courselink}
    {bookinglink}
    {pollurl}
    {pollurlteachers}
    {location}
    {institution}
    {address}
    {eventtype}
    {teacher}
    {teacherN} - N is number of teacher ex. {teacher1}
    {pollstartdate}
    {qr_id} - Insert QR code with user id
    {qr_username} - Insert QR code with user username
    {times} - Session times

Other tags are possible, but not on a feature list.

Kind regards,
David
