### ISSUE TITLE
Grade section dissappears when you edit booking settings M3.0

### ISSUE THREAD

**Issue by demontech** [Wunderbyte-GmbH/moodle-mod_booking#60]
Hi David,

There's a new section called Grade between the Connected Booking and the Ratings sections. 
![image](https://cloud.githubusercontent.com/assets/8148238/17609665/08bab968-5fec-11e6-8e7b-f6bc3f1cf4d5.png)

...but after saving it and when you go back to edit the settings this section disappears. 
![image](https://cloud.githubusercontent.com/assets/8148238/17609685/3f56b670-5fec-11e6-872e-06dd9ea62474.png)

**Comment by dasistwas** [comment]
thank you for bringing up this issue. I will investigate.

**Comment by dasistwas** [comment]
Just found the solution: When you want to use grading, you have to define the ratings options first. If you do not use rating, then you can not use grade neither.

**Comment by dasistwas** [comment]
I just compared with the module forum: There it is the same. When you do not use ratings for the forum, then the "Grade" option is not available neither. This seems to be a general moodle issue. Also using AJAX for updating the settings directly when editing it, is very difficult and not really supported by Moodle.

So if you want to use grade (in a booking instance you chose not to use ratings when you saved it for the first time): Define ratings, then save, then edit again and set the grade settings.
