### ISSUE TITLE
Bericht herunterladen: Fatal Error

### ISSUE THREAD

**Issue by VOOM108** [Wunderbyte-GmbH/moodle-mod_booking#605]
**Describe the bug**
Wenn ich auf Bericht herunterladen klicke, kommt ein 500 Fehler,

![image](https://github.com/user-attachments/assets/ae76f6c8-8cc1-4261-af26-910b9f41e6ac)
 oder in den Logs
Fatal error: Cannot acquire reference to $GLOBALS in /homepages/24/d902941652/htdocs/moodle-418plus01/mod/booking/TinyButStrong/tbs_class.php on line 647
wenn ich Debugging dev anschalte

**Versions uses**
Moodle version: [4.1.8+ (Build: 20240208)]
Boooking version: 8.2.4 - 2024041100

**To Reproduce**
1. Go to Seite mit den Teilnehmern einer Option
2. Click on Bericht herunterladen
3. See error

**Comment by dasistwas** [comment]
Please check if the problem persists in the latest 8.6 version:
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/tags

**Comment by VOOM108** [comment]
Unfortunately yes. The error shown with debugging on is the same as above. 

Question in context: Is this the report the one that, with the Pro setting "Report from all options of the instance" (or something similar), covers the entire instance?

**Comment by georgmaisser** [comment]
Hi, this is quite old, I think it should be fixed (we use this report quite a lot). But there could be an error linked to certain special field etc. which we don't use. If you encounter an error on download, please send further information and screenshots, especially about customfields.
