### ISSUE TITLE
No access to booking rules

### ISSUE THREAD

**Issue by woi-srh** [Wunderbyte-GmbH/moodle-mod_booking#608]
**Describe the bug**
A get a hint that I am supposed to transfer my settings to the new feature "booking rules", however when I click on the associated link "booking rules" I have no access.

**Versions uses**
Moodle version: 4.1
Boooking version: 8.2.4

**To Reproduce**
1. Go to booking activity settings
2. Got to e-mail settings.
3. Click on link "booking rules"

**Expected behavior**
Landing in the "booking rules" area.

**Screenshots**
![fehlermelderung_buchungsregeln_meldung](https://github.com/user-attachments/assets/f3a0e679-92f4-4582-a077-ffbf964c5e56)
![fehlermelderung_buchungsregeln_kein zugriff](https://github.com/user-attachments/assets/3008a569-8936-41e6-907f-40f3d259637a)

**Additional context**

**Comment by georgmaisser** [comment]
Guten Tag, wir sind dazu ja schon im Austausch ;-)

Booking rules will be partially opened for non Pro Users, we need to implement this properly, but we wanted to have the deprecation warning as soon as possible.
