### ISSUE TITLE
Reminder E-Mails coming from language package and templates twice for same info, also placeholders not correct

### ISSUE THREAD

**Issue by VOOM108** [Wunderbyte-GmbH/moodle-mod_booking#626]
**Describe the bug**
There is an email text that can be configured for "Benachrichtigung vor dem Beginn" which I suppose is the message, that can be configured to be sent on up to two occasions set as days before the beginning of the event.   

Also, there is a text in the language files for reminder emails. It seems, both are being sent, which is redundant, and the text from the language files does not fill all placeholders correctly. 

<p>Erinnerung: Sie haben den folgenden Termin gebucht:</p> <p>{$a->optiontimes}</p> <p>##########################################</p> <p>{$a->sessiondescription}</p> <p>##########################################</p> <p>Buchungsstatus: {$a->status}</p> <p>Teilnehmer: {$a->participant}</p>

optiontimes and status in the emails are shown as placeholders, not the content that should be there. 

Ideally, I would like to disable the language file email completely and only use the email that can be configured in the booking instance. Where could I disable it? And if I cannot disable it, at least the content should be correct. 

**Versions uses**
Moodle version: 4.4.1 (Build: 20240610)
Booking version: 2024071500 (Pro)

![image](https://github.com/user-attachments/assets/4420c621-be55-42f4-b811-463fea9d65c5)
![image](https://github.com/user-attachments/assets/2a52f87f-456d-4078-a178-9f724722d51a)
![image](https://github.com/user-attachments/assets/9e2c563d-827c-44e6-8717-a79394352dc6)
![image](https://github.com/user-attachments/assets/06ef185a-b8c3-48b6-9dc4-863b504104f5)

**Comment by eynimeni** [comment]
Dear @VOOM108 , 

thank you for reaching out!

Please note that the templates you are referring to are deprecated and should be replaced by the much preciser "Rules" feature. 
We are currently working on a detailed documentation of this feature. But maybe you can already find your way around. 

To disable the sessionremindermails (from strings) open the dates section and set "notification n days before start" to 0 (zero).

![Screenshot 2024-09-23 at 11 56 19](https://github.com/user-attachments/assets/bcf6fa5d-ed39-475b-b1d7-06bcf09fed0d)

**Comment by VOOM108** [comment]
We know about the rules feature, but the customer wants to work with the mails for now, as long as they are still available. What you suggest, does not solve the problem: it would completely disable the reminder mails. Not just the one from the strings. The issue is, that two reminders are sent: one from the strings and one from the mail templates in the booking instance. When there was a template in the instance, the reminders used to come only from the templates. Now there are two mails for the same reminder.

**Comment by eynimeni** [comment]
Thank you for your message, and I’m sorry that my previous answer wasn’t as helpful as I had hoped. Unfortunately, I’m not entirely familiar with this older method of sending reminder emails. For now, I would suggest double-checking the settings for each booking option (under "Dates" and "Text depending on booking status"), as well as reviewing the plugin settings within the mail templates section. Additionally, I highly recommend migrating your templates to the Rules feature, which I’d be happy to assist you with.

At the moment, I’m unable to take the time to set up a testing environment or explore this deprecated functionality in more detail, as I need to prioritize work for our paying customers. I apologize for any inconvenience this may cause. Should you need more in-depth support, our hourly rate is €120 (net).

Thank you for your understanding!
