### ISSUE TITLE
Completion Condition not triggered

### ISSUE THREAD

**Issue by JoshuaAuthement** [Wunderbyte-GmbH/moodle-mod_booking#629]
**Describe the bug**
When the completion condition is set to 'Add requirements' then choosing 'Count of entries', we set it to 1. The condition is not marked as completed when a user books a session. 

**Versions uses**
Moodle version: 4.3
Booking version: 8.2.4

**To Reproduce**
1. Go to the booking activity settings.
2. Click on completion conditions. Select 'Add requirements' then check the box for 'Count of entries' and enter 1 into the text box. Save changes.
3. Have a user enroll in a booking session.
4. The activity is not marked as complete.

**Expected behavior**
Once a user books a session, the activity should be marked as complete.

**Screenshots**

Booking Settings:
![image](https://github.com/user-attachments/assets/0fe95f2f-d0ca-4378-8e81-717d71d295be)

User booked:
![image](https://github.com/user-attachments/assets/479d8a61-1534-48d7-900b-cf969081e2db)

Activity for user not marked complete:
![image](https://github.com/user-attachments/assets/b777a594-08ae-481c-b931-2128e3120686)

**Comment by dasistwas** [comment]
Could you try if the issue still persists in the latest release:
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.6.19

**Comment by dasistwas** [comment]
Any news about this @JoshuaAuthement  ?

**Comment by dasistwas** [comment]
It is possible that this feature does not work right now.

**Comment by dasistwas** [comment]
@semteacher could you have a look at that?

**Comment by JoshuaAuthement** [comment]
> Any news about this @JoshuaAuthement ?

We are working on installing the plugin from GitHub.

**Comment by semteacher** [comment]
As I can see from code and recent tests, completion feature now working in the following way:
- Even with all settings as above, student's completion has to be confirmed by teacher / booking manager.
- For this in booking instance for the option student has booked, the followng settings has to be done:
![image](https://github.com/user-attachments/assets/8860ba09-e8a6-44f7-8c59-afaf6254e515)
![image](https://github.com/user-attachments/assets/01711c5d-eb23-48ac-91fc-8b603fc2e716)
- This lead to the "complete" state in the "activity completion" report
![image](https://github.com/user-attachments/assets/adb88a78-af17-42ec-9a66-f13bea7157de)
- Which, in turn, will indicates for student that activity has been completed:
![image](https://github.com/user-attachments/assets/0e0c7484-979a-4127-a923-c6bdb9fa16d2)

**Comment by JoshuaAuthement** [comment]
We created a blank dev site to test the plugin.  I was going to say that the completion condition was not triggered, but I see from the post above that it has to be manually confirmed. Something else that was noticed related to the completion condition is that it is not listed on the course home page.
![image](https://github.com/user-attachments/assets/669afb14-42c5-4d82-9a1f-43b1f76e10ba)

Also, when you go to the settings and click save, the completion condition is triggered without manually confirming it. However, when another user books a session, the condition is still not triggered.

**Comment by semteacher** [comment]
@georgmaisser  I have fixed above bug (https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/629#issuecomment-2389348958):
![image](https://github.com/user-attachments/assets/91f9f381-dec2-444a-8a66-9285a3b9af56)
Once teacher (manager / admin) marks designated number of booked options as completed - status has been updated properly
![image](https://github.com/user-attachments/assets/997809f4-2754-4adb-9fa7-fc3a5fb07faf)
Fix under 401_testing branch. 
The only remaining issues - stings in German has to be updated according to English
UPD: I think #474 has to be addressed too in order to fix all related things. Can do it but will takes some time

**Comment by eynimeni** [comment]
can this be closed as completed now @semteacher ? The german strings were added

**Comment by gemguardian** [comment]
@dasistwas This changed is causing a bug in 4.1

![image](https://github.com/user-attachments/assets/6f0629fd-3782-4d20-98e7-7ba412486555)
