### ISSUE TITLE
Institution and Teacher shows on the same row

### ISSUE THREAD

**Issue by demontech** [Wunderbyte-GmbH/moodle-mod_booking#63]
Hi David,

This is probably an easy fix. The institution name and the teacher name are displayed on one row rather than in different rows (in the latest version.)

![image](https://cloud.githubusercontent.com/assets/8148238/18565116/5dbd78b6-7b43-11e6-8ea9-e729a7d63ce3.png)

Thanks!

**Comment by dasistwas** [comment]
Fixed in https://github.com/dasistwas/moodle-mod_booking/commit/f7b10641438dacf54a14624ec2197c0f3ee4dc21
