### ISSUE TITLE
Unenrolled users on Sign-In Sheet.

### ISSUE THREAD

**Issue by JoshuaAuthement** [Wunderbyte-GmbH/moodle-mod_booking#632]
**Describe the bug**
The root issue is that when a user unenrolls from the course, they are not unenrolled from the booking. The user is still listed in the booking list, so they are reflected on the sign-in sheet/attendance activity.

**Versions uses**
Moodle version: 4.3
Booking version: 8.2.4

**To Reproduce**
1. Go to the booking activity and have a user book a session.
2. Unenroll the user from the course.
3. Go to the booking activity.
4. The user will be listed in the sign-in sheet/attendance activity for the booking.

**Expected behavior**
When a user unenrolls from the course, they are no longer on the sign-in sheet/attendance activity. So, people who are enrolled into the course can join the session.

**Screenshots**

Left side shows the sign-in sheet/attendance activity. Right side shows the enrolled users.
![image](https://github.com/user-attachments/assets/2b466c48-1a2f-41e6-b87e-05f53e6bcafc)

**Additional context**
The issue is present in release version 8.6.19 which we test on a blank dev site.

**Comment by georgmaisser** [comment]
Hi,
this is not a bug.
When a users is enrolled via the booking option, but then deleted via the course participants list, the user will not automatically be deleted from the booking option.

A direct link between those two would not be expected by must of booking users. If you need this, you should change your routine and unenroll users via the booking option. Then they should also be unsubscribed from the linked course.

We could implement a feature to optionally support unsubscription from a booking option if one is unsubscribed from a course. But it would be sth you would need to order and pay for. It would be about half a days work.

(You should be aware that there needs to be a special treatment if a user is booked to the same course via two different booking options)
