### ISSUE TITLE
When clicking on an MS teams booking link for a meeting that isn't open yet an error is thrown

### ISSUE THREAD

**Issue by danbuntu** [Wunderbyte-GmbH/moodle-mod_booking#634]
**Describe the bug**
When clicking on an MS teams booking link for a meeting that isn't open yet an error is thrown:

Exception - Class "booking_option" not found

I believe that this is a logic flow issue and I have attached a patch 

[bookinglink.patch](https://github.com/user-attachments/files/17256802/bookinglink.patch)

**Versions uses**
Moodle version: 4.1.13
Boooking version: 8.4.7 

**To Reproduce**
1. Create a booking option
2. Add a date and select 'add a custom field'
3. Select the 'Teams meeting' option
4. Set a date for the meeting in the future
5. In the ical link that is emailed click on the link to the teams meeting and it will display the error message

**Expected behavior**
Click the link for a Teams meeting in the future displays a message saying that the meeting is not yet open and includes the open time.

**Comment by dasistwas** [comment]
Thank you for providing detailed information of this bug. We fixed it in https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.7.1
