### ISSUE TITLE
Moodle Group enrollment does not work

### ISSUE THREAD

**Issue by felipecalixtoreis** [Wunderbyte-GmbH/moodle-mod_booking#635]
**Describe the bug**
When creating a scheduling option, the group is created within Moodle groups, which is correct, however, when a user makes a booking using the plugin feature, that user is not registered in the group and the server log generates this error :

**Versions uses**
Moodle version:  4.4.3+
Boooking version: 8.7.2  (2024100800)

**To Reproduce**
1. Go to booking activitie
2. Click on 'book now'
3. After user booked, look the group status of the user

**Expected behavior**
The user must be subscribed to the group for which he booked.

**Additional context**
Server log error here:

[STDERR] Debugging: Coding problem: $PAGE->context was not set. You may have forgotten to call require_login() or $PAGE->set_context(). The page may not display correctly as a result in 
* line 575 of /lib/pagelib.php: call to debugging()
* line 972 of /lib/pagelib.php: call to moodle_page->magic_get_context()
* line 43 of /mod/booking/classes/booking_context_helper.php: call to moodle_page->__get()
* line 311 of /mod/booking/classes/output/bookingoption_description.php: call to mod_booking\booking_context_helper::fix_booking_page_context()
* line 477 of /mod/booking/locallib.php: call to mod_booking\output\bookingoption_description->__construct()
* line 311 of /mod/booking/classes/calendar.php: call to get_rendered_eventdescription()
* line 111 of /mod/booking/classes/calendar.php: call to mod_booking\calendar::booking_optiondate_add_to_cal()
* line 1372 of /mod/booking/classes/booking_option.php: call to mod_booking\calendar->__construct()
* line 1132 of /mod/booking/classes/booking_option.php: call to mod_booking\booking_option->after_successful_booking_routine()
* line 557 of /mod/booking/classes/booking_bookit.php: call to mod_booking\booking_option->user_submit_response()
* line 453 of /mod/booking/classes/booking_bookit.php: call to mod_booking\booking_bookit::answer_booking_option()
* line 659 of /mod/booking/classes/bo_availability/bo_info.php: call to mod_booking\booking_bookit::bookit()
* line 83 of /mod/booking/classes/external/load_pre_booking_page.php: call to mod_booking\bo_availability\bo_info::load_pre_booking_page()
* line ? of unknownfile: call to mod_booking\external\load_pre_booking_page::execute()
* line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

**Comment by dasistwas** [comment]
@felipecalixtoreis thank you for reporting the bug. I could reproduce the problem. May I ask you if you purchased a pro license?

**Comment by felipecalixtoreis** [comment]
@dasistwas I believe I bought it a few years ago, but the version I use today is not the PRO.

**Comment by georgmaisser** [comment]
Hi, @felipecalixtoreis , it's not a pro feature anyways. We'll fix it asap.

**Comment by eynimeni** [comment]
Thank you @felipecalixtoreis for reaching out and sorry that this took so long. 
The exception you get isn't critical and not really related to the enrolement.
The enrolment works for the course that is selected in the settings of the bookingoption. The users who booked are enroled in a group in this course, not in the course where the booking is located (as one might suppose).
I have adapted the description to make this clearer.

I hope my anwer was helpful.
Please don't hesitate contacting us again if anything is still unclear or if you encouter other problems.

Here's a screenshot of the settings to link courses in bookingoption settings.
![Image](https://github.com/user-attachments/assets/394b2077-beed-48f9-a03e-31c501e4463d)
