### ISSUE TITLE
Testing privacy checkbox

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#636]
It is now possible to activate an option to delete data from a form filled out before booking an option after the bookingoption is over.
Usecase:
Users have to give supplementary information about their preferences when booking an option. Example: The bookingoption is a seminar including food and the users submit their preferences and allergies. 
These informations can be deleted automatically after the end of the bookingoption - for example for respecting privacy regulations.
There are now two new ways to handle this: 
a) data for all users is deleted automatically: check the checkbox "Delete the data provided by the user after the option has ended.": 

![Screenshot 2024-10-10 at 12 08 14](https://github.com/user-attachments/assets/d94b8832-fd4e-445d-aac1-dd9cce3f8398)

b) Users should decide for themselves if they want the data to be deleted:

![Screenshot 2024-10-10 at 12 09 36](https://github.com/user-attachments/assets/dc2060c1-98a0-4569-a585-73ff0e4ea5c4)

In this case, when a user books the corresponding option, the checkbox will be rendered. 

![Screenshot 2024-10-10 at 12 15 31](https://github.com/user-attachments/assets/fd3920e1-a15a-400a-91d2-4bc0dd82c093)

If the admincheckbox (as described in a) ) is active, the checkbox will not be rendered for users (since data will be deleted in any case)

When a user books this option, data from the form is stored in the booking_answers table in the JSON field under key "condition_customform".

After the bookingoption is over (bookingclosingtime) and cron was executed, and any of the checkboxes is checked, all "condition_customform"-data is deleted from booking_answer.

To make sure the deletion is executed, configure a rule like:
<img width="875" alt="Screenshot 2024-10-25 at 07 48 30" src="https://github.com/user-attachments/assets/bace2de1-4a23-4e04-9f8f-84986c2694b4">

**Comment by semteacher** [comment]
After the initial analysis of tesk's description, I can assume the following:

- [x] 1. Behat test(s) could be useful to validate behavior of user-level ceckbox

- [x] 2. To verify settings enforced as admin and actual deletion of data - I think that the only phpunit has to be used.

**Comment by eynimeni** [comment]
ok please implement the tests as you can

**Comment by semteacher** [comment]
Have created 
- the behat test to check UI (working OK)
- phpunit to check answers. Confirms custom form data in option answers. But it persists after I call adhoctasks and even when I call cron in phpunit (works with another warning).

@eynimeni @georgmaisser   What exact circumstances / settings are required to execute deletion? I noticed presence of rule's action. Have tried it as well but without success too.    
UPD: even manually - I cannot figure-out conditions for custom form data to be deleted or debugging would intercept execution process.

**Comment by georgmaisser** [comment]
@eynimeni Can you help @semteacher here? BTW, did you check the problem where answers were deleted only from some people?

**Comment by eynimeni** [comment]
# What exact circumstances / settings are required to execute deletion?
@semteacher I have added a screenshot of the configuration of the rule in the description.
An example json in booking answer (for admin checkbox) would be:
{"condition_customform":{"id":"18960","userid":"2","deleteinfoscheckboxadmin":"1","customform_shorttext_1":"Neu"}}

You also need to set a timestamp in courseenddate (booking_option table). This is a bit tricky. You have to set the courseenddate to a value in the future when you save the bookingoption. This makes sure, ad hoc tasks are created because of the rule. 
When the courseenddate is in the past and cron is triggered, the deletion will be executed.
The above JSON in bookinganswer will then look like: {}

**Comment by eynimeni** [comment]
> BTW, did you check the problem where answers were deleted only from some people?

@georgmaisser I have tried to reproduce the problem but failed.
Some possible sources of behaviour:
- Rule didn't select "Users who booked" but for example "Users who booked and are on waitinglist"...
- It wasn't the admin-checkbox but the other checkbox and some users checked it, some others didn't.
- Some ad hoc tasks were deleted from table
- Cron execution failed during process (because of errors)

For debugging it would be great to have a look at the JSON of the booking answers where the condition_customform data still remained and the configuration of the rule. 

Did this reoccur?

**Comment by semteacher** [comment]
@eynimeni  Thank you for explanation.
Also confrimed error in task execution (despite status is "success" - yet another issue):
![image](https://github.com/user-attachments/assets/72e8498d-03c2-4112-9e38-78aa6a2eceb9)
I am trying to debug but having difficulties with interception get_records_for_execution() method

**Comment by semteacher** [comment]
managed with debugging. During manual tests  `$DB->get_records_sql()` command of the `get_records_for_execution()` method of the `rule_daysbefore` class returns duplicated records:
![image](https://github.com/user-attachments/assets/c88844e6-834e-445c-becb-f6de716b05a6)
Tried query manually and got the same
![image](https://github.com/user-attachments/assets/820b0814-db02-4aa6-a95d-a5bcb5dc2e28)
DB record is single
![image](https://github.com/user-attachments/assets/ab2a5665-014f-4640-aebf-99efa0e09a1d)

Sample of SQL for this case:
```
SELECT  '' || bo.id || '-' || ba.userid  uniqueid, ba.id as baid, bo.id optionid, cm.id cmid, bo.courseendtime datefield, ba.userid userid  FROM m_booking_options bo
                    JOIN m_course_modules cm
                    ON cm.instance = bo.bookingid
                    JOIN m_modules m
                    ON m.name = 'booking' AND m.id = cm.module
                    JOIN m_context c
                    ON c.instanceid = cm.id JOIN m_booking_answers ba ON bo.id = ba.optionid  WHERE  c.path LIKE '/1%' AND bo.courseendtime IS NOT NULL   AND bo.id = 285    AND ba.waitinglist = '0' AND ba.userid = 118
```

**Comment by semteacher** [comment]
@eynimeni  @georgmaisser  I have tried to improve query but not sure in approach such as it has been created in 2 classes - rules_daybefore and select_student_in_bo .
a) I have eliminated "bo.id", "'-'", "ba.userid" . The field ba.id was introduced alredy and it is definitely unique. But it does not help - same duplication happens (that is my main disappointment - I do not understand why).
b) Obvious solutions are to use SELECT DISTINCT (or Group BY) but I am not sure if it could be considered as feassible at all Despite usage of DISTINCT looks like not affects at least current phpunit tests - it will affect all rules if being added on  rules_daybefore (for example)
c) definitely changgin order of source tables (put booking_answers in FROM ) sovlve issue but cannot be used (FROM section created in rules_daybefore whereas booking_answers added as JOIN in select_student_in_bo)

**Comment by semteacher** [comment]
Have fixed 1 bug (non-cached readings) and applied approach with SELECT DISTINCT . All existing tests working OK...
