### ISSUE TITLE
Blank booking

### ISSUE THREAD

**Issue by demontech** [Wunderbyte-GmbH/moodle-mod_booking#64]
I just installed the newest version 1.9 on M3.0 PHP 5.6 with MySQL. Previous version was working fine, but when I upgraded to new version all the booking options were blank, they dissappeared, and I got this error:

Fatal error: Class 'core_tag_tag' not found in /pathto/moodle/mod/booking/view.php on line 339

I replaced the file view.php from the previous version, and it's working fine now. I don't know if this was a good idea.

**Comment by dasistwas** [comment]
Hi,

thank for reporting the problem. Fixed it in the latest commit.
