### ISSUE TITLE
Error when adding Dates: "Cannot read properties of undefined (reading 'container')"

### ISSUE THREAD

**Issue by icca-rnewton** [Wunderbyte-GmbH/moodle-mod_booking#649]
**Describe the bug**
When clicking "Add date" in the New Booking Option form, I receive the following error:
Cannot read properties of undefined (reading 'container')

With the Stack Trace:
TypeError: Cannot read properties of undefined (reading 'container')
    at updateForm (https://training.icca.ac.uk/lib/requirejs.php/1727968481/core/first.js:1716:5234)
    at e (https://training.icca.ac.uk/lib/javascript.php/1727968481/lib/jquery/jquery-3.6.1.min.js:2:30038)
    at t (https://training.icca.ac.uk/lib/javascript.php/1727968481/lib/jquery/jquery-3.6.1.min.js:2:30340)

**Versions uses**
Moodle Version: 4.1 (Build: 20230111)
Booking version: 8.2.4 

**To Reproduce**
1. Create a new Booking Activity
2. Select "New Booking Option"
3. Scroll down to "Dates"
4. Select "Add date"
5. See error

**Expected behavior**
When selecting "Add dates" I expect to see a box open where I can choose the start time and end time of the course. I should also be able to create a notification delay or add a custom field. Then select Apply.

**Screenshots**
![Booking Error](https://github.com/user-attachments/assets/b489d62d-5ae3-421a-a594-07cb1d2a0b73)

**Additional context**
This bug is happening on our Moodle Workplace site. I did not have this issue with the normal LMS Moodle (version 4.1.12). It didn't matter if the course had both a start and end date or semester. This bug also appeared when trying to delete a semester.

**Comment by georgmaisser** [comment]
You need to install the latest updates in your moodle version (you can stay on moodle 4.1, but you need to install the security updates. We fixed this bug with the dynamic forms in moodle core in April 2023.
