### ISSUE TITLE
Book for Number of User - send inskription Link

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-mod_booking#650]
- [x] In a Booking option, we can change the price according to params which can be changed - eg. Number of Licenses
- [x] For the change of price, we can set fixed price to certain values (add a towel or stuff).
- [x] We can create a formula (eg. when x times 15 Euros)
- [x] After Booking Action can generate a link, depending on the chosen value, which will allow inscription to the given booking option.

**Comment by eynimeni** [comment]
- [x] 3rd param accepts 0 for no limit set
- [x] price + (+ x EUR)
- [x] 1 => lmlkm, 2 => should be possible 
- [ ] nach empty cache sollte auch funktionieren

**Comment by eynimeni** [comment]
- [ ] create placeholder
