### ISSUE TITLE
MUSI-628 Kurse speichern und Vertreterpool automatisch befüllen

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#661]
- [ ] db fehler beim speichern über sparten.php
- [ ] automatisches eintragen in den vertreterpool

**Comment by bernhard-wunderbyte** [comment]
E-Mail von Johannes Koch:

"Habe es mir aber gerade am Prod System angeschaut und die Pools scheinen korrekt befüllt worden zu sein.. Keine Ahnung was das damals war, hab die Fehler aber zusammen mit Magdalena (@eynimeni ) „gefunden“, vielleicht weiß sie noch was das war..?
Sonst können wir das ja morgen kurz im Springwechsel besprechen?"

**Comment by bernhard-wunderbyte** [comment]
Derzeti nicht reproduzierbar. Sollte der Fehler noch einmal auftreten, wird ein neues Ticket erstellt.
