### ISSUE TITLE
MUSI-629 "Zum Buchen einloggen" Button im uneingeloggten Zustand

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#666]
Wenn man im nicht eingeloggten Zustand auf die Seite schaut, sollte über den Preisen ein Button erscheinen, der zum Login führt.

**Comment by eynimeni** [comment]
Hotfix required: Preise können momentan nicht eingeloggt nicht angezeigt werden

**Comment by eynimeni** [comment]
should be fixed and visible with 0c81b52fe557e637f4347ed41aa1c4e8132a0386 
has to be verified on musi testing as well, since they are using their own template

**Comment by bernhard-wunderbyte** [comment]
@eynimeni  Dependent on Wunderbyte-GmbH/Wunderbyte-GmbH#245 => Once we have green actions, we can deploy a new all-in-one on MUSI Testing to verify.

**Comment by bernhard-wunderbyte** [comment]
@eynimeni I tried it on https://musi.usi.at/mod/page/view.php?id=192 => The button is not shown there. So I moved the ticket back to In-Progress.

**Comment by bernhard-wunderbyte** [comment]
Button now visible on: https://musi.usi.at/testing/mod/page/view.php?id=192 - so I'll close this.
