### ISSUE TITLE
Error when deleting a booking option

### ISSUE THREAD

**Issue by demontech** [Wunderbyte-GmbH/moodle-mod_booking#68]
Hi David,

I'm getting this error when I tried to delete a booking option in M3.0 with your latest version:

image
![image](https://cloud.githubusercontent.com/assets/8148238/19544926/3d704642-9637-11e6-8ce3-264a6336e586.png)

Thanks!

**Comment by dasistwas** [comment]
Hi,

I can't reproduce this error. Does it still exist? Could you provide a course backup or backup of the booking instance in order to reproduce it.

Thanks,
David

**Comment by demontech** [comment]
It was happening for some booking not for all of them. I ended up deleted them from the database.

very strange

**Comment by dasistwas** [comment]
I close this. Does not seem to happen anymore.
