### ISSUE TITLE
Self-learning courses: New type of booking options with duration but no fixed dates

### ISSUE THREAD

**Issue by bernhard-wunderbyte** [Wunderbyte-GmbH/moodle-mod_booking#684]
**Objective**
There should be a new type of booking options for Moodle courses that have no specific start or end time but a **certain duration**, so-called "self-learning courses" (SLC). When a user books a self-learning course (s)he should be immediately enrolled into the connected Moodle course (if there is any) for the provided duration.

**Details / Tasks**
- [x] A SLC is identified by a json flag "selflearningcourse" and by a duration bigger than 0 (in seconds).
- [x] A SLC can still have a start time (coursestarttime). However, it will be used for sorting only but won't be shown in the interface.
- [x] Regarding coursestarttime, we have to make sure that it does not affect booking rules, booking actions etc. => So if a course has a duration (it's a SLC), we have to make sure that everything related to coursestarttime will be turned off.
- [x] This means: any rule that uses "coursestarttime" must not be executed for self-learning courses.
- [x] It should be possible to enter any duration (e.g. in days, weeks...)
- [x] The interface should adjust itself automatically, so a user cannot enter dates for self learning courses etc.
- [x] A user will be un-enrolled from the moodle course after the duration.
- [x] Store duration as an integer in seconds (use the already existing field "duration" of the booking options table).
- [x] Add interface elements for duration so we can enter weeks, days...
- [x] Validation: For SLC, it should be possible to add a sorting date (use field coursestarttime).
- [x] Make sure sessions (optiondates), start and end time are never shown in the UI for SLC.
- [x] Instead of sessions, the duration of the course should be clearly visible in the interface
- [x] Make sure condition optionhasstarted never blocks for SLC
- [x] "Disallow users to cancel their booking n days before start..." => How should we handle this for SLC?
- [x] Make sure users are enrolled immediately after booking.
- [x] Make sure users are un-enrolled after enrolment date + duration.
- [x] Make it a PRO feature that can be activated in plugin config settings.
- [x] Write tests for creation of SLC and tests for correct user enrolment.

Important note: We want to use this feature also independently from self learning courses for other courses without date. So, there should be a "label" field, that gives admins the possibility to override the "Self learning course" label visible to the users. And it should work also when no moodle course is linked to the booking option.

- [x] Implement this labelling functionality.

**Comment by bernhard-wunderbyte** [comment]
Hi @semteacher - I assigned this to you because we need tests for this new feature.

**Comment by bernhard-wunderbyte** [comment]
@semteacher When you're done with the behat tests, then please check the last checkbox ("Write tests...") and close this issue.

**Comment by semteacher** [comment]
@bernhard-wunderbyte I have created a single behat which covers exactly "Write tests for creation of SLC and tests for correct user enrolment.". Should I create more? List of properties for this type of option is clear but most of combinations looks very complicated to be tested within behat...

**Comment by bernhard-wunderbyte** [comment]
@georgmaisser I think, for now, this test is enough. Or do we need more?
