### ISSUE TITLE
Testing Campaigns

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#689]
Path: .../mod/booking/edit_campaigns.php

There are two types of campaigns:
a) Block certain booking options
b) Change price or booking limit

In the modal one can select for which booking options and for which users a specific campaign applies, and when it is applicable (timeperiod). 
Conditions are concatenated via AND. 

If a blocking campaign (a) is blocking, the message defined in the modal should be visible. Except for some kind of status in bookingoptios, like "Booked" that is not overruled by campaign.
Change campaign (b) should modify the price or limit. 

We need extensive tests for campaigns with different conditions and all kind of combinations to make sure, all works as expected.

**Comment by semteacher** [comment]
I have fixed currently existing tests (behat and phpunits) related to campaigns. They are working OK.
Howevwer, 13 of other behat tests fails. They all realted to sending of custom messages - via rules or directly. Those tests still working under Moodle_401_dev @eynimeni any suggestions why it has happenned? Same - 1 phpunit fails related to teacher emain remainder. Still OK under Moodle_401_dev

**Comment by eynimeni** [comment]
Thank you @semteacher 
The failures happened because I had based my branch on the commit b255bea2aff82e6a5596395b48d1a7214c2a415c

Watch out @bernhard-wunderbyte -> this is breaking many behat tests because the event custom message send isn't rendered correctly in the event log table

so @semteacher could you please extend the tests to the newly given options of campaigns? do you need further instructions to do so?

**Comment by semteacher** [comment]
@eynimeni I would be grateful about pointing me to the new features and how those have to work properly

**Comment by eynimeni** [comment]
New is that custom user profile field and bookingoptionfield can exclude values. 
Also blocking regardless of places wasn't there before

We should have tests for a maximum of given combinations like for example:

User1: profilefield1: student, profilefield2: no
User2: profilefield1: teacher, profilefield2: 
User3: profilefield1: , profilefield2: yes

Bookingoption1: customfield1: exclude, bookedusers: 5 maxansers 6
Bookingoption2: customfield1: , bookedusers: 0 maxansers 6
Bookingoption3: customfield1: include, bookedusers: 2 maxansers 6

With different settings of the campaigns, it should be tested which user sees which bookingoption.

Settings of Campaign1:
Booking option field: customfield1: NOT exclude
Custom user profile field: profilefield1: contains student
Timestamps: start now -1 day, end now +1 day
Operator block below 50

Expected result Campaign1:
User1 should see: Bookingoption2 & Bookingoption3
User2 & User3 no bookingoptions visible

Settings of Campaign2:
Booking option field: contains exclude
Custom user profile field: profilefield1: NOT student
Timestamps: start now -1 day, end now +1 day
Operator regardless

Expected result Campaign2:
User1 should not see any bookingoptions
User2 & User3 should see bookingoption1

ETC ETC

**Comment by semteacher** [comment]
@eynimeni I spent quite time on both behat and phpunit tests but even being incomplete - my resuls looks different than in comment above:
- for the following campaing1 settings
![image](https://github.com/user-attachments/assets/4dbdad8d-bca2-46d4-bce0-7c4fa152e09d)
![image](https://github.com/user-attachments/assets/f65bbdea-9aef-4c29-a4cb-23daf3c467b9)
- for the options
![image](https://github.com/user-attachments/assets/9628df62-4de1-42ef-a378-1f4b6822b1e9)
- and students
![image](https://github.com/user-attachments/assets/cf9f6829-abe6-4f80-98bd-5983986a53df)
- I am receiving:
a) student 1
![image](https://github.com/user-attachments/assets/51f79bc9-fc5d-4708-9fd4-b11908e8ba97)
(personally - seems correct, campaingn should be applied to opt2 and opt3  (not opt1) and to student1 )
b) students 2 and 3
![image](https://github.com/user-attachments/assets/5a9486e6-1639-4cdc-be70-1d65129178a6)
(personally - seems correct, campaingn should not be applied to those students - profilefield1 does not match)
Am I correct or my do my settings are wrong?
And above - it is only for 1st proposed campaign... 
I can cntinue but there are too many possible combinations and for me it is not easy to narrow set to realistic scenarios...

**Comment by eynimeni** [comment]
yes, this is great and correct behaviour!

- [x] please also make a campaign with that includes the customfield and excludes users with given user profile field

- [x] please also copy one campaign - user combination that is blocking and try to disable it by changing the dates of the campaign to future or past, so not blocking anymore

- [x] please also copy one campaign - user combination that is blocking and try to disable it by setting the block below operator to numbers that aren't reached. so it should not be blocking anymore.

this should be enough to cover all relevant cases. thank you very much!

**Comment by semteacher** [comment]
booking_campaigns_test has been updated, all listed cases already covered. I would consider this issue as completed

**Comment by eynimeni** [comment]
@semteacher thank you very much!
