### ISSUE TITLE
SQL Query error on Postgres when upgrading from an ancient version

### ISSUE THREAD

**Issue by abias** [Wunderbyte-GmbH/moodle-mod_booking#69]
Hi David,

I currently have the job to upgrade a Moodle 2.7 installation with version 2014062500 of mod_booking installed to Moodle 3.1. In the course of the Moodle core upgrade, I wanted to upgrade mod_booking to the latest version 2016092301.

Unfortunately I get a SQL Query error during the Moodle DB update process saying:

```
Debug info: ERROR: syntax error at or near "ba"
LINE 1: DELETE ba FROM mdl_booking_answers AS ba LEFT JOIN mdl_booki...
^
DELETE ba FROM mdl_booking_answers AS ba LEFT JOIN mdl_booking AS b ON b.id = ba.bookingid WHERE b.course = $1 AND ba.userid NOT IN (SELECT DISTINCT
eu1_u.id
FROM
mdl_user eu1_u
JOIN
mdl_user_enrolments eu1_ue ON eu1_ue.userid = eu1_u.id
JOIN
mdl_enrol eu1_e ON (eu1_e.id = eu1_ue.enrolid
AND eu1_e.courseid = $2)
WHERE
eu1_u.deleted = 0 AND eu1_u.id <> 1)
[array (
0 => '1074',
1 => '1074',
)]
Error code: dmlwriteexception
```

```
Stack trace:
line 477 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 712 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1173 of /mod/booking/db/upgrade.php: call to pgsql_native_moodle_database->execute()
line 726 of /lib/upgradelib.php: call to xmldb_booking_upgrade()
line 432 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1742 of /lib/upgradelib.php: call to upgrade_plugins()
line 683 of /admin/index.php: call to upgrade_noncore()
```

We are using Postgres 9.5.4 which might be untested by you, but I am not sure if this is really a problem with Postgres.
Reading the SQL Query in the debug message, I don't know what you really want to delete with "DELETE ba FROM mdl_booking_answers AS ba ..." as your SQL Query tries to delete something named with the table alias. 

Could you please give me a hint how I can upgrade from the ancient version of your plugin to a recent version?

Thanks,
Alex

**Comment by dasistwas** [comment]
Hi Alex,

please read https://moodle.org/plugins/mod_booking : Postgres is not supported anymore in current versions due to lack of financing. There are quite a view SQL queries, which are not compatible with Postgres. It will be quite a bit of work to make it compatible with Postgres. Fixing the upgrade script is only a small part of it. 

Kind regards,
David

**Comment by abias** [comment]
Hi David,

I am really sorry, I haven't read the plugin description again at all as the plugin was already installed on the Moodle instance and was used in production and the plugin "just needed an upgrade".

I fully understand what you are writing about the funding and as far as I understand it isn't only about funding the Postgres support but about a general funding of the plugin.

As the plugin upgrade was part of a job for a client of ours, I cannot say anything if funding would be possible. I will talk to the client and may come back to you with a private message.

Thanks,
Alex
