### ISSUE TITLE
Fix some placeholders

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-mod_booking#695]
In Benachrichtigungen, for teachers:

bitte bei Trainer*innen die ID ausblenden
bitte bei Trainer*innen mehrere Personen mit Komma trennen 
bitte Datum, Ort, etc. mit Komma trennen

**Comment by eynimeni** [comment]
ID war nicht ersichtlich
die anderen beiden umgesetzt in templates in lexa theme
