### ISSUE TITLE
Testing customform select

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#696]
More features added to availability condition select in customform
![Screenshot 2024-11-13 at 09 08 45](https://github.com/user-attachments/assets/299cef57-d5a4-423f-9286-d30cb4a080d3)

I have tried to add a meaningful description. Could you maybe have a look if you understand this?
The select should be visible as defined in bookingoption prepage (either inline or modal, depending on plugin settings)
In this case inline:
![Screenshot 2024-11-13 at 09 26 52](https://github.com/user-attachments/assets/f2430d2d-3013-4805-b7bb-e48b0a920d19)

for the different price options as defined via pricecategoryfield, this is the custom user profile field that is selected in the booking plugin settings as pricecategoryfield
![Screenshot 2024-11-13 at 09 29 03](https://github.com/user-attachments/assets/178e0c20-290c-4c94-814b-7bdabda5a566)

#669 

TESTS: 

- [x] behat
- [ ] phpunit

**Comment by semteacher** [comment]
Price categories does not being processed:
- for the following categories
![image](https://github.com/user-attachments/assets/1ac37570-82c2-45de-a0ff-5326cdf52291)
- and form settings 
![image](https://github.com/user-attachments/assets/bb888351-ceb6-433d-a4c3-40377f6d3231)
- I got 
![image](https://github.com/user-attachments/assets/f02afb81-9a8f-44ec-a65d-d31f4523d632)
 Same case with manual tests

**Comment by eynimeni** [comment]
@semteacher the pricecategories aren't fields of the bookingoption but of the user. they should be defined as followed. 
1) create custom user profile field
2) select field in pluginsettings as pricecategoryfield
3) enter value for user in this field

should I make a screenrecording for this?

**Comment by semteacher** [comment]
@eynimeni In fact - I made it yesterday that way:
![image](https://github.com/user-attachments/assets/f3264d5c-86bd-489e-ade2-a3e17136bf39)
But it dies not working for some reasons

**Comment by eynimeni** [comment]
And did you set in plugins profile_field_userpricecat as pricecategoryfield?
Like here in the interface setting
![Screenshot 2024-11-14 at 16 08 25](https://github.com/user-attachments/assets/b3caf02e-650d-4408-9d1a-cb8206c62fe0)

**Comment by semteacher** [comment]
@eynimeni yes:
![image](https://github.com/user-attachments/assets/b1afee0a-0d58-4ac6-93eb-938ffbafd379)

**Comment by semteacher** [comment]
Reasons for above error:
- (minor) it mast be OR stated explicitly in help that spaces are required before and after "=>" OR remove those spaces from 
$linearray = explode(' => ', $line);
- (major) code 
$price = (float) $pricedata
in the customformstore always return "0" if $pricedata contains non-numerical symbols like "discount2:100,discount1:200,default:150". So condition if (!is_float( ... always =false
Going to fix las one

**Comment by semteacher** [comment]
Have pushed further improvements to make same price style being used everywhere:
![image](https://github.com/user-attachments/assets/90884d7c-2f76-4244-a838-594a2ba4ea3a)

**Comment by eynimeni** [comment]
@semteacher thank you very much - great work!
