### ISSUE TITLE
Warning for self learning courses is shown when dates are added

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-mod_booking#713]
![Image](https://github.com/user-attachments/assets/6572679d-51a3-4790-b983-28667f085fec)

**Comment by bernhard-wunderbyte** [comment]
@georgmaisser I cannot reproduce this. I'll move it into "To discuss"

**Comment by bernhard-wunderbyte** [comment]
@eynimeni Please close this when you consider it done.
