### ISSUE TITLE
Selbstlernkurse Termin Warnung bei Add Date obwohl kein Selbstlernkurs

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-mod_booking#715]
- [x] Warnungen bei Selbstlernkurse überprüfen, wenn z.b. kein Kurs ausgewählt ist

**Comment by bernhard-wunderbyte** [comment]
@eynimeni  Bitte ebenfalls schließen, sobald getestet.

**Comment by eynimeni** [comment]
796bd6cf6962c9695d32c191b4500259fa57c97e should resolve it
unfortunately I can not verify if static is hidden correctly due to my moodle version <4.3
please check again on a newer environment @bernhard-wunderbyte
