### ISSUE TITLE
MUSI-636 Neue Variablen

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#717]
2) Buchungen verwalten - Download (CSV, XLSX...)
Nummerierung funktioniert nicht
Anordnung passt nicht (Namen)
"fehlend": inskriptionsart, tatsächlich bezahlter preis

see also: https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart/issues/102

**Comment by bernhard-wunderbyte** [comment]
Wird derzeit nicht umgesetzt. Es kommen ggf. neue Tickets dafür.
