### ISSUE TITLE
MUSI-638 ausgebuchte Kurse im ausgeloggten zustand

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#718]
Im ausgeloggten Zustand wird bei ausgebuchten Kursen der Preis nicht angezeigt, sondern das Benachrichtigungssymbol.

edit:Preise sollen immer angezeigt werden. (im eingeloggten Zustand nur der eigene Preis angezeigt)

Notification Bell soll immer in Kombi mit Preis sein

Ausgeloggt wird Bell nicht angezeigt

**Comment by bernhard-wunderbyte** [comment]
Verifiziert: Im ausgeloggten Zustand (MUSI Theme) werden die Preise auch bei ausgebuchten Kursen angezeigt.
