### ISSUE TITLE
Get rid of necessary "event type" setting when creating a new booking instance, as it is never used

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-mod_booking#725]

**Comment by georgmaisser** [comment]
![Image](https://github.com/user-attachments/assets/d839b1ac-19af-4134-9dc2-b2ba893aed2f)

**Comment by bernhard-wunderbyte** [comment]
@georgmaisser  The eventtype actually **is used**. But it will only be shown as string in some places. For example in the automatic naming of new booking options for an instance or at the coursepage_shortingo_and_button template.
