### ISSUE TITLE
Cannot add dates in a new booking option

### ISSUE THREAD

**Issue by jonadinedy** [Wunderbyte-GmbH/moodle-mod_booking#727]
![IMG_0184](https://github.com/user-attachments/assets/ded936be-ab41-4514-b289-9e9558d4259e)

**Describe the bug**

**Versions uses**
Moodle version: 4.5
Boooking version:  8.8.1 (2024112500)

**To Reproduce**
1. Go to a booking module
2. Click on 'New booking option '
3. Scroll down to Dates> then add dates
4. When you select a date later than date of today then click apply/add date or save.
5. See error

**Expected behavior**
After clicking apply/add date or save an empty box shows up.

**Screenshots**

**Additional context**
This is the free version of the booking module

**Comment by dasistwas** [comment]
Thank you for reporting this. What happens if you first save the booking option and then add the dates?

**Comment by jonadinedy** [comment]
> Thank you for reporting this. What happens if you first save the booking option and then add the dates?

As long as I use the date of "today" it works fine. but when I change the date it gives the error. 

another thing I tried is, when I save the date of today then go back to edit the date let's say - to tomorrow, it saves fine. But only when I click the 'Save button' at the bottom. Whenever I click the button 'Apply' it always gives me that empty box as shown on the screenshot.

**Comment by bernhard-wunderbyte** [comment]
@georgmaisser This seems to be a bug with Moodle **4.5**, as it does not happen on my local container (Moodle 4.3).
@semteacher Can you write test cases for this so we can verify this happens with Moodle 4.5 only?

**Comment by bernhard-wunderbyte** [comment]
@jonadinedy Can you install Booking 8.8.2 and test if this still happens: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.8.2 ?

**Comment by semteacher** [comment]
Moodle 4.5+ (Build: 20241101) booking 8.8.2 - I cannot reproduce that error manually. Moreover - we already have 5 tests which uses "Add date", 4 of which use future dates. They all passed OK

**Comment by bernhard-wunderbyte** [comment]
As it cannot be reproduced, I will close this for now. @jonadinedy Please let us know, if the error still happens with Booking 8.8.2. If so, I'll reopen this ticket.

**Comment by jonadinedy** [comment]
Hi, I tried doing another test I am still getting it but it turns out random, sometimes it works. I got this from inspect when the issue came out (please see screenshot).

I tried installing this as well into another Dev environment and it is working fine from there, so we are investigating what might be causing the issue.![image](https://github.com/user-attachments/assets/31983a29-76b9-4cdc-8940-19c5e4a85610)

**Comment by mlom100** [comment]
please help with the below bug, it happens every time I click to add a date and cause the booking system to freeze

Describe the bug
A clear and concise description of what the bug is: Cannot read properties of undefined (reading 'container')

Versions uses
Moodle version: 4.1.4 (Build: 20230612)]
Booking version:  2024041100

To Reproduce
Steps to reproduce the behaviour:

Go to a booking module
Click on 'New booking option '
Scroll down to Dates> then add dates
When you select a date later than date of today then click apply/add date or save.
See error - Cannot read properties of undefined (reading 'container')
Expected behavior
After clicking apply/add date or save an empty box shows up.


Additional context
This is the free version of the booking module

**Comment by bernhard-wunderbyte** [comment]
@georgmaisser Can you have one look at this again? It seems to happen with other versions of Moodle too.

@mlom100 Could you please check if this happens still in the newest versions? You can get them here:
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.8.2
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/releases/tag/v2.0.30-stable

**Comment by mlom100** [comment]
fixed with update thanks
