### ISSUE TITLE
Booking rules -  ical files are not attached

### ISSUE THREAD

**Issue by danbuntu** [Wunderbyte-GmbH/moodle-mod_booking#732]
**Describe the bug**
When using the new booking option option Ical attachments are being sent when a user confirms a booking or a booking is cancelled.
I've been though the booking rules option and I can't see anywhere that I need to set this as an option. the option to attach icals is set in the main plugin settings page.

**Versions uses**
Moodle version: 4.1
Boooking version: 8.8.0 and 8.8.0

**To Reproduce**
1. Enable 'Attach iCal file' in the settings
2. Create a booking rule for when a user books:

![image](https://github.com/user-attachments/assets/9a24bcc9-306f-49a2-9929-8c54fff73e2d)

4. Make a booking
5. Observe no ical attached

**Expected behavior**
Ical should be attached as per non booking rules version

**Comment by eynimeni** [comment]
Hi and thank you for reaching out!

We decided not to support ical because it is difficult to maintain them correctly, especially in case of changes in the appointments.

We recommend you to use the placeholder {coursecalendarurl} instead.

I hope this answer was somehow helpful.

**Comment by danbuntu** [comment]
I understand not using ical over ics. But would it be possible to add the ics file as an attachment? 

People are very used to receiving calender invites as attachments to an email. They are very likely to miss a link in an email.

**Comment by eynimeni** [comment]
hi @danbuntu 
I understand your point. 
We would be happy to add this functionality in the future, once we have paying customers interested in supporting its development.

**Comment by danbuntu** [comment]
Just to be clear this functionality is a regression from the prebooking rules system. So we have paid for the pro license and lost a feature.

**Comment by danbuntu** [comment]
We have also just noticed that {coursecalendarurl} has an ics that contains all of the booking option dates for a course. Ie not just the event that the user has booked on.

Is there a shortcode that contains just the booking option that the user has booked on so that they can add it to their calender?

**Comment by danbuntu** [comment]
ok {usercalandarurl} gives a slightly better experince. It outputs raw html though and not a nice link. I've submited #789 with the fix for this.

The end user experience is very confusing though. In my experience end users do not subscribe to calendars.  They expect to add individual meetings to add to their main calendar. We generally turn off moodle calenders for our clients for this reason. If I open the ics file and do import then it adds all the events across the moodle that I'm booking on to my calendar. If I then make another booking and click the ics file in that one it imports all the events again and thus causes a bunch of duplicates.

If I go down the add a calendar route then it's intially going to be confusing for the user as they rarely use this feature and then each booking email will give me a new ics file which they will likely import and end up with dozens of copies of the same calendar.

**Comment by danbuntu** [comment]
I have now created pull request  #801 
This includes working code for adding ics files as attachments to booking rules. I've pretty sure it can be done in better way by someone more familiar with the code base but it works and hopefully shortcuts having this functionality re-added.
