### ISSUE TITLE
Ordering by numbering on report.php causes sql error

### ISSUE THREAD

**Issue by danbuntu** [Wunderbyte-GmbH/moodle-mod_booking#741]
**Describe the bug**
When report.php displays the numbering column clickiing on it causes a sql error.

**Versions uses**
Moodle version: 4.1/13
Boooking version: 8.8.3

**To Reproduce**
1. Go to report.php
2. Click on 'Numbering'
3. See error below:

Unknown column 'indexnumber' in 'order clause'
SELECT
ba.id, u.firstnamephonetic, u.lastnamephonetic, u.middlename, u.alternatename, u.firstname, u.lastname,
ba.optionid,
u.username,
u.institution,
u.city,
u.department,
ba.completed,
ba.status,
ba.timecreated,
ba.userid,
ba.waitinglist,
ba.notes,
ba.places,

**Expected behavior**
No error when odering by numbering

**Comment by georgmaisser** [comment]
The reason for this bug ist that ordering by number does not make sense, so it should not be possible to click on the button.

Todo:

- [x] Turn off sorting option in tablesql class

**Comment by eynimeni** [comment]
By the way, will refactor the report.php soon
