### ISSUE TITLE
Translation fixes lang strings

### ISSUE THREAD

**Issue by danbuntu** [Wunderbyte-GmbH/moodle-mod_booking#742]
$string['dontmove'] = 'Do not move';
$string['bookingandcancelling'] = 'Booking and Cancelling';
$string['addtogroup_help'] = 'Automatically enrol users in group - group will be created automatically with name: Booking name - Option name';
$string['aftercompletedtext_help'] = 'Message shown after activity become completed';
$string['boactioncancelbookingvalue'] = "Activate immediate cancellation";
$string['cancelreason'] = "Reason for cancellation of this booking option";
$string['copytotemplatesucesfull'] = 'Booking option was successfully saved as template.';
$string['instancesuccessfullysaved'] = 'This booking instance was successfully saved as template.';
$string['sucesfullcompleted'] = 'Activity was successfully completed for users.';
$string['sucesfullytransfered'] = 'Users were successfully transfered.';

**Comment by eynimeni** [comment]
@danbuntu thank you very much for poiting this out! 😅
