### ISSUE TITLE
Add customfield Filter to courselist shortcode

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-mod_booking#752]
copy function from urise project. the goal ist to be able to add any filter on a customfield to the place where we use the shortcode

- [x] Fix standard custom field filter to be shown in standard filters menu - needs to work with "select" customfield (Auswahlliste)
- [x] Make sure actual values of customfield are shown, currently indexes are shown (1, 2,...)
- [x] Implement or copy pre-filter not to be shown in filter menu but to filter BEFORE booking options are shown
- [x] example: argument tag=Highlighted should only show booking options with a booking option customfield with shortname tag that has the value "Highlighted"
- [x] this should also work with for example category="Kommunikation" (see Sandra's screenshot)
- [x] implement filterontop

**Comment by bernhard-wunderbyte** [comment]
@plomersan

**Comment by plomersan** [comment]
![Image](https://github.com/user-attachments/assets/18c5f80a-0c9a-4c58-adc2-ba60f8296fe3)

**Comment by bernhard-wunderbyte** [comment]
@plomersan Important: When using shortcode for select (Auswahlliste) we cannot use the actual string value, but instead have to use the index.

Example: For a customfield with shortname "tag" [courselist cmid=12 all=true tag=Highlighted] won't work, but we can use [courselist cmid=12 all=true **tag=1**] if "Highlighted" is the value of the first row.

**Comment by bernhard-wunderbyte** [comment]
[courselist cmid=12 all=true filter=1 filterontop=1] will show the filter on top now.
