### ISSUE TITLE
coursecalendarurl shortcode generates text url not a html link

### ISSUE THREAD

**Issue by danbuntu** [Wunderbyte-GmbH/moodle-mod_booking#754]
**Is your feature request related to a problem? Please describe.**
When including the shortcode [coursecalendarurl] the url is rendered as text. Adding this is a link within the email ie.

`<a href="[coursecalendarurl ]">Link to calender</a>`

Fails to render the link correctly as a clickable link. Add the shortcode on it's own and it just renders as text,

**Describe the solution you'd like**
I think that the short code should render as a clickable link

I suggest the following change to classes/placeholders/placeholders/coursecalenderurl.php line 84

```
      $value = '<a href="' . $bu->booking_generate_calendar_subscription_link($user, 'courses') . '">' .
                    get_string('linktocalenderurltext', 'mod_booking') .
                '</a>';
```

**Comment by danbuntu** [comment]
This is essentially the same bug as #767 - i've checked and it appears there are onyl two occurances of this bug

**Comment by eynimeni** [comment]
@danbuntu thanks for bringing this to our attention. will be deployed in one of the next versions
