### ISSUE TITLE
On deleting a shorttime reserveration, bookinganswer_cancelled event is triggered (and messages might be sent).

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-mod_booking#759]
When putting an item in the shopping cart and deleting it, that's not the case.

But when deleting the shorttime reservation via the report.php of booking, the event is also triggered. Trigger should only occur when deleting Booked or reserved.

**Comment by eynimeni** [comment]
I also changed the title in the modal, since data about bookingoption couldn't be displayed correctly
