### ISSUE TITLE
Booking rules - booking updated event not firing

### ISSUE THREAD

**Issue by danbuntu** [Wunderbyte-GmbH/moodle-mod_booking#760]
**Describe the bug**
I have a booking rule with the event set to booking option updated

I also have the defualt settings in the 'settings for booking rules' as show in the screenshot below

When I change a booking - alerting the date - the booking doesn't seem fire and no emails are sent

**Versions uses**
Moodle version: 4.1
Boooking version: 8.8.3

**To Reproduce**
1. Create the booking rule as per screenshots
2. change an event date
3. ??
4. Wonder where the emails are

![image](https://github.com/user-attachments/assets/216f16d4-8525-4381-97bc-fd5df272a128)

![image](https://github.com/user-attachments/assets/57283e10-847e-4884-99cf-e2355f48d632)

![image](https://github.com/user-attachments/assets/54845e7a-6cb8-4b72-9367-a69de7ea1390)

**Expected behavior**
Event fires and emails are sent

**Comment by eynimeni** [comment]
Thank you for reporting this and providing all these details.

I have checked this functionality and it works perfectly fine in my environment. Are you sure, you don't exclude the execution of this rule in another rule?

**Comment by eynimeni** [comment]
and could you please take a look in the bookingoption settings if the changes of the dates are registered in the event log table there?
![Image](https://github.com/user-attachments/assets/702d2ad9-c7eb-4b82-965e-7da25c2ec751)

**Comment by danbuntu** [comment]
Ok I've double checked everything and this is now firing.

I believe the issue I was having was that there where adhoc jobs stuck in the task_adhoc table possibly from before I switched to the new rules system. truncating this table seems to have sorted it.
