### ISSUE TITLE
booking option link in emails is rendered as text

### ISSUE THREAD

**Issue by danbuntu** [Wunderbyte-GmbH/moodle-mod_booking#767]
**Describe the bug**
The goto booking option link in {bookingdetails} is rendered as url rather than nice text

https://domain/mod/booking/optionview.php?optionid=199&cmid=470&userid=197&returnto=url&returnurl
not
Go to bookiing link

This is not accessible and just plain ugaly

**Versions uses**
Moodle version: 4.13
Boooking version: latest stable

**To Reproduce**
1. Send an email that contains the {bookingdetails} shortcode
2. Read the email using a screenreader 
3. Cry as it trys to read out the url

**Expected behavior**
Link rendered as a nice link

I suggest classes\output\bookingoption_description line 521 changes to:

```
        $this->booknowbutton = get_string('gotobookingoption', 'booking') . ': ' .
                    '<a href = "' . $moodleurl . '" target = "_blank">' .
                        get_string('gotobookingoptionlink', 'booking') .
                    '</a>';

```
and lang string is added

**Comment by danbuntu** [comment]
This is essentially the same bug as #754  - i've checked and it appears there are onyl two occurances of this bug

**Comment by eynimeni** [comment]
@danbuntu thank you for your recommendation! in the next version of the plugin, the clickable text to be displayed can be overwritten in the string "gotobookingoptionlink"
