### ISSUE TITLE
bug with add to cart

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#768]
Dear all

I am sorry for sending this email to everyone. I really do not know who is more relevant to this technical issue that I am facing with booking plug-in. Our students are not able to add the course in card when they click on add to card on the front however when they click on the link of that particular booking instance and then add to card it goes in the card we have been facing this issue for more than three months and we could not really figure out but today we found that this is happening that they are able to add course into the card through the link of the instance but not from the front of the booking itself. Here is a link of what is happening please have a look and help me sorting this problem out. 
[Watch Video](https://www.loom.com/share/d0f8de2225474978bafdecd08eec67d7)

**Comment by eynimeni** [comment]
@bernhard-wunderbyte is taking care

**Comment by bernhard-wunderbyte** [comment]
See Wunderbyte-GmbH/Wunderbyte-GmbH#286
