### ISSUE TITLE
Booking options don't order by date

### ISSUE THREAD

**Issue by danbuntu** [Wunderbyte-GmbH/moodle-mod_booking#772]
**Describe the bug**
When multiple booking options are added they don't order by the booking date. see below

![image](https://github.com/user-attachments/assets/2ac16c21-9848-46aa-ae77-84a8716662bb)

**Versions uses**
Moodle version: 4.1.13
Boooking version: latest stable

**Expected behavior**
Correct ordering by the first date attached attached to a booking option. It this case: 17,18,19,20

**Comment by dasistwas** [comment]
Dear @eynimeni could you check if that's a bug?

**Comment by eynimeni** [comment]
hi @danbuntu in which table are you displaying this? are you applying sorting for start?
![Screenshot 2024-12-19 at 14 30 30](https://github.com/user-attachments/assets/7433d146-1805-4b1c-b034-8d95d2470e0b)

**Comment by danbuntu** [comment]
To be honest I hadn't really appreciated that sort dropdown was there untill you've just pointed it out. 

I've now found the setting to default the sort ordering by start.

I'll upate the templates toinclude this now.

Thanks for your help
