### ISSUE TITLE
Download table data does not respect moodle/site:viewuseridentity

### ISSUE THREAD

**Issue by abias** [Wunderbyte-GmbH/moodle-mod_booking#78]
Hi David,

in a recent version, you have added the "ID-Nummer" column which contains the "idnumber" user profile field (_not_ the "ID des Nutzers" column which was there for a long time and which contains each user's Moodle user id). Thanks for that.

Unfortunately, I noticed that you don't check if the teacher downloading the table data has the moodle/site:viewuseridentity capability or not. If he does not have this capability, the download table data must not contain this column or the column should at least be empty.

The function get_extra_user_fields() from /lib/moodlelib.php helps you checking which fields you can show to a user and which not. As far as I see, you have already used this function for another feature in mod_booking, but in the download table feature, the idnumber column is hardcoded.

Could you please check if you can fix this?

Thanks,
Alex

**Comment by dasistwas** [comment]
Hi,

I added the capability check viewuseridentity for idnumber and institution, which are currently being the only extra user fields used for the download. Does that fix this issue? Fix see b359336fb82094df868ec73981af417d74cdbad5

Kind regards,
David

**Comment by abias** [comment]
Hi David,

thank you for this patch. It fixes the immediate problem we were facing. 

Thanks,
Alex

**Comment by dasistwas** [comment]
Hi Alex,

perfect, so I will close this issue.

Kind regards,
David
