### ISSUE TITLE
language package doesn't change name on button

### ISSUE THREAD

**Issue by gemguardian** [Wunderbyte-GmbH/moodle-mod_booking#79]
Hi David,

I want to change the name of the "Book now" button permantly in my own language. 
In the language package there is a string called booknow, though this string doesn't seem to refer to the Book now button and/or at least not taking the translation. 

See enclosed screenshot. 
Can you take a look at it? 

Gemma 
![2017-03-05](https://cloud.githubusercontent.com/assets/16559999/23586243/5f7b8114-0191-11e7-9a26-0c8d26b893df.png)

**Comment by gemguardian** [comment]
In the end it was some bug on the site, language package takes the change now. 
CLosing this.

**Comment by dasistwas** [comment]
Alright. Thank you for rechecking.
