### ISSUE TITLE
time notation on session times

### ISSUE THREAD

**Issue by gemguardian** [Wunderbyte-GmbH/moodle-mod_booking#80]
Hi, 

I noticed that the time notation at the session dates does seem to have a different notation on the booking option 

If I fill in a session time notation: 12 june 2016 09:00 to 17:30
It will show on the option (and confirmation) as 12 june 2016 09:00 to 5:30. 

Can this be changed? Or is this a server setting? 

Thank you 

Gemma

**Comment by dasistwas** [comment]
Hi Gemma,

thank you for reporting this issue. It is now fixed in the latest version on github: https://github.com/dasistwas/moodle-mod_booking/commit/500178b062a609eeccc2801f1924b3c1e4c2b746

Kind regards,
David
