### ISSUE TITLE
Student name does not align under the student name column in sign-in sheet

### ISSUE THREAD

**Issue by demontech** [Wunderbyte-GmbH/moodle-mod_booking#89]
Hi David,

I'm using booking v 2017050600 with M 3.1 and 3.2, and I have the same issue:

![image](https://cloud.githubusercontent.com/assets/8148238/25786502/49ec32d0-334b-11e7-9123-abdf70fd721c.png)

Thanks !!

**Comment by atlet** [comment]
I'll take a look and fix it.

**Comment by atlet** [comment]
Fixed in my repo.

**Comment by dasistwas** [comment]
Thank you for reporting and fixing this. Fix is going to be part of todays relase at moodle.org.
