### ISSUE TITLE
Error on sign-in on sheet : logo

### ISSUE THREAD

**Issue by gemguardian** [Wunderbyte-GmbH/moodle-mod_booking#92]
Hello David 

I just upgraded the module from Moodle.org and when trying to generate a sign-in-sheet I had the error "TCPDF ERROR: [Image] Unable to get the size of the image: @" 

Before it actually did work, I am not sure if something has been changed that makes that the logo need to be a certain image size? 

For now I deleted the logo, so sign-in-sheets can be generated but would be nice if you would have time to check this.

Gemma

**Comment by dasistwas** [comment]
Hi Gemma,

thank you for reporting this. I should have noticed that during testing. This should be fixed now, there was an id-number missing in an sql statement. 

Kind regards,
David

**Comment by dasistwas** [comment]
... the update is already available at moodle.org.
