### ISSUE TITLE
Sign-in -sheet is not showing Booking Date(s):

### ISSUE THREAD

**Issue by gemguardian** [Wunderbyte-GmbH/moodle-mod_booking#94]
Hello David,
Think this is a small issue in the PDF (missing hook?) 

The Booking Date(s) are not showing on the sign-in-sheet. 
I am sure I saw it before, but might be mistaken? 

I enclosed a pdf (sorry for the dutch in the sheet but I think it is clear enough what I mean) 

Gemma
[09-11-2017 (1).pdf](https://github.com/dasistwas/moodle-mod_booking/files/1101772/09-11-2017.1.pdf)

**Comment by dasistwas** [comment]
Fixed in latest release. Uploaded on moodle.org.
